var $CLJS = module.exports = {};
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var ca,da,ea,fa,ja,ka;ca=function(){var a=$CLJS.aa.navigator;return a&&(a=a.userAgent)?a:""};da=function(a){return-1!=ca().indexOf(a)};ea=function(){return da("Firefox")||da("FxiOS")};fa=function(){return(da("Chrome")||da("CriOS"))&&!da("Edge")||da("Silk")};
$CLJS.ia=function(a,b){const c=Array.prototype.slice.call(arguments),d=c.shift();if("undefined"==typeof d)throw Error("[goog.string.format] Template required");return d.replace(/%([0\- \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(e,f,k,l,m,t,u,v){if("%"==t)return"%";const x=c.shift();if("undefined"==typeof x)throw Error("[goog.string.format] Not enough arguments");arguments[0]=x;return $CLJS.ia.zc[t].apply(null,arguments)})};ja=function(){return da("iPhone")&&!da("iPod")&&!da("iPad")};
ka=function(){ja()||da("iPad")||da("iPod")};$CLJS.la=$CLJS.la||{};$CLJS.aa=global;$CLJS.ma="closure_uid_"+(1E9*Math.random()>>>0);$CLJS.aa=global;$CLJS.na=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};var oa=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};$CLJS.pa=class{constructor(a,b){this.name=a;this.value=b}toString(){return this.name}};$CLJS.qa=new $CLJS.pa("OFF",Infinity);$CLJS.ra=[$CLJS.qa,new $CLJS.pa("SHOUT",1200),new $CLJS.pa("SEVERE",1E3),new $CLJS.pa("WARNING",900),new $CLJS.pa("INFO",800),new $CLJS.pa("CONFIG",700),new $CLJS.pa("FINE",500),new $CLJS.pa("FINER",400),new $CLJS.pa("FINEST",300),new $CLJS.pa("ALL",0)];$CLJS.ia.zc={};$CLJS.ia.zc.s=function(a,b,c){return isNaN(c)||""==c||a.length>=Number(c)?a:a=-1<b.indexOf("-",0)?a+oa(" ",Number(c)-a.length):oa(" ",Number(c)-a.length)+a};
$CLJS.ia.zc.f=function(a,b,c,d,e){d=a.toString();isNaN(e)||""==e||(d=parseFloat(a).toFixed(e));let f;f=0>Number(a)?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=Number(a)&&(d=f+d);if(isNaN(c)||d.length>=Number(c))return d;d=isNaN(e)?Math.abs(Number(a)).toString():Math.abs(Number(a)).toFixed(e);a=Number(c)-d.length-f.length;0<=b.indexOf("-",0)?d=f+d+oa(" ",a):(b=0<=b.indexOf("0",0)?"0":" ",d=f+oa(b,a)+d);return d};
$CLJS.ia.zc.d=function(a,b,c,d,e,f,k,l){return $CLJS.ia.zc.f(parseInt(a,10),b,c,d,0,f,k,l)};$CLJS.ia.zc.i=$CLJS.ia.zc.d;$CLJS.ia.zc.u=$CLJS.ia.zc.d;da("Opera");da("Trident")||da("MSIE");da("Edge");!da("Gecko")||-1!=ca().toLowerCase().indexOf("webkit")&&!da("Edge")||da("Trident")||da("MSIE")||da("Edge");-1!=ca().toLowerCase().indexOf("webkit")&&!da("Edge")&&da("Mobile");da("Macintosh");da("Windows");da("Linux")||da("CrOS");var sa=$CLJS.aa.navigator||null;sa&&(sa.appVersion||"").indexOf("X11");da("Android");ja();da("iPad");da("iPod");ka();ca().toLowerCase().indexOf("kaios");Date.now();ea();ja()||da("iPod");da("iPad");!da("Android")||fa()||ea()||da("Opera")||da("Silk");fa();!da("Safari")||fa()||da("Coast")||da("Opera")||da("Edge")||da("Edg/")||da("OPR")||ea()||da("Silk")||da("Android")||ka();