var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./lambdaisland.glogi.js");require("./lambdaisland.glogi.print.js");
'use strict';var yy=function(){},zy=function(a){return $CLJS.J.g($CLJS.nx,a).value},cfa=function(a){var b=zy(a);return $CLJS.n(function(){var c=zy($CLJS.Ex);return $CLJS.dk.g?$CLJS.dk.g(c,b):$CLJS.dk.call(null,c,b)}())?$CLJS.jy:$CLJS.n(function(){var c=zy($CLJS.Dx);return $CLJS.dk.g?$CLJS.dk.g(c,b):$CLJS.dk.call(null,c,b)}())?$CLJS.ty:$CLJS.n(function(){var c=zy($CLJS.Bx);return $CLJS.dk.g?$CLJS.dk.g(c,b):$CLJS.dk.call(null,c,b)}())?$CLJS.my:$CLJS.n(function(){var c=zy($CLJS.vx);return $CLJS.dk.g?
$CLJS.dk.g(c,b):$CLJS.dk.call(null,c,b)}())?$CLJS.sy:$CLJS.n(function(){var c=zy($CLJS.Cx);return $CLJS.dk.g?$CLJS.dk.g(c,b):$CLJS.dk.call(null,c,b)}())?$CLJS.uy:$CLJS.n(function(){var c=zy($CLJS.yx);return $CLJS.dk.g?$CLJS.dk.g(c,b):$CLJS.dk.call(null,c,b)}())?$CLJS.py:$CLJS.n(function(){var c=zy($CLJS.sx);return $CLJS.dk.g?$CLJS.dk.g(c,b):$CLJS.dk.call(null,c,b)}())?$CLJS.qy:$CLJS.ry},Ay=function(a){var b=$CLJS.I(a,0,null);a=$CLJS.I(a,1,null);return new $CLJS.Q(null,2,5,$CLJS.R,[[$CLJS.p.h(b),$CLJS.p.h(" ")].join(""),
a],null)},By=function(a,b,c){var d=$CLJS.I(a,0,null);a=$CLJS.I(a,1,null);return new $CLJS.Q(null,2,5,$CLJS.R,[[$CLJS.p.h(d),"%c",$CLJS.p.h(b),"%c"].join(""),$CLJS.de.l(a,["color:",$CLJS.p.h($CLJS.J.g($CLJS.xy,c))].join(""),$CLJS.H(["color:black"]))],null)},Cy=function(a,b,c){var d=$CLJS.I(a,0,null);a=$CLJS.I(a,1,null);return new $CLJS.Q(null,2,5,$CLJS.R,[[$CLJS.p.h(d),"%c",$CLJS.p.h(b),"%c"].join(""),$CLJS.de.l(a,["color:",$CLJS.p.h($CLJS.J.g($CLJS.xy,$CLJS.vy)),";background-color:",$CLJS.p.h($CLJS.J.g($CLJS.xy,
c))].join(""),$CLJS.H(["color:black;background-color:inherit"]))],null)},dfa=function(a){function b(c,d){return d>=c}a=zy(a);if(b(zy($CLJS.Ex),a))return"error";if(b(zy($CLJS.Dx),a))return"warn";if(b(zy($CLJS.Bx),a))return"info";b(zy($CLJS.vx),a);return"log"},Dy=function(a){return function(b){var c=$CLJS.O(b),d=$CLJS.J.g(c,$CLJS.tx),e=$CLJS.J.g(c,$CLJS.ns);b=$CLJS.J.g(c,$CLJS.Fx);e=dfa(e);e=$CLJS.Da(console,e);e=$CLJS.n(e)?e:console.log;$CLJS.P.g(e,a.h?a.h(c):a.call(null,c));return $CLJS.n(b)?(c=["[",
$CLJS.p.h(d),"]"].join(""),d=$CLJS.p.h(b),b=b.stack,e.v?e.v(c,d,"\n",b):e.call(null,c,d,"\n",b)):null}},Ey=function Ey(a,b){for(;;){if($CLJS.E.g($CLJS.iy,b))return By(a,", ",$CLJS.ry);if($CLJS.E.g($CLJS.ky,b))return Ay(a);if(b instanceof $CLJS.M)return By(a,b,$CLJS.my);if(b instanceof $CLJS.r)return By(a,b,$CLJS.sy);if("string"===typeof b)return By(a,$CLJS.Oh.l($CLJS.H([b])),$CLJS.ly);if($CLJS.Bf(b)){var d=Ay(function(){var f=a,k=$CLJS.Fb(b);return Ey.g?Ey.g(f,k):Ey.call(null,f,k)}()),e=$CLJS.Gb(b);
return Ey.g?Ey.g(d,e):Ey.call(null,d,e)}if(b instanceof $CLJS.h||b instanceof $CLJS.Jg)return d=a,d=By(d,"{",$CLJS.wy),d=$CLJS.fb(Ey,d,$CLJS.hf($CLJS.iy,b)),By(d,"}",$CLJS.wy);if($CLJS.yd(b))return d=a,d=By(d,["#",$CLJS.p.h(function(){var f=$CLJS.bb(b),k=f.name;return $CLJS.ud(k)?$CLJS.Oh.l($CLJS.H([f])):k}())," "].join(""),$CLJS.ny),d=By(d,"{",$CLJS.wy),d=$CLJS.fb(Ey,d,$CLJS.hf($CLJS.iy,b)),By(d,"}",$CLJS.wy);if($CLJS.wd(b))return d=a,d=By(d,"#{",$CLJS.wy),d=$CLJS.fb(Ey,d,$CLJS.hf($CLJS.ky,b)),By(d,
"}",$CLJS.wy);if($CLJS.Ad(b))return d=a,d=By(d,"[",$CLJS.wy),d=$CLJS.fb(Ey,d,$CLJS.hf($CLJS.ky,b)),By(d,"]",$CLJS.wy);if(b instanceof $CLJS.Tf)d=By(a,"#queue ",$CLJS.ny),e=$CLJS.gg.g($CLJS.Ef,b),a=d,b=e;else{if($CLJS.Ed(b))return d=a,d=By(d,"(",$CLJS.ny),d=$CLJS.fb(Ey,d,$CLJS.hf($CLJS.ky,b)),By(d,")",$CLJS.ny);if(null!=b?b.I&16384||$CLJS.Cc===b.$i||(b.I?0:$CLJS.ab(yy,b)):$CLJS.ab(yy,b))d=By(a,"#atom ",$CLJS.ny),e=$CLJS.q(b),a=d,b=e;else if($CLJS.gi(b))d=By(a,"#uuid ",$CLJS.ny),e=$CLJS.p.h(b),a=d,
b=e;else if($CLJS.Za(b))d=By(a,"#js ",$CLJS.ny),e=$CLJS.fb(function(f,k){return function(l,m){return $CLJS.T.j(l,$CLJS.Bh.h(m),$CLJS.Da(k,m))}}(a,b),$CLJS.N,Object.keys(b)),a=d,b=e;else if($CLJS.Va(b))d=By(a,"#js ",$CLJS.ny),e=$CLJS.gg.g($CLJS.Ef,b),a=d,b=e;else return By(a,$CLJS.Oh.l($CLJS.H([b])),$CLJS.oy)}}};$CLJS.efa=Dy(function(a){a=$CLJS.O(a);$CLJS.J.g(a,$CLJS.ns);var b=$CLJS.J.g(a,$CLJS.tx),c=$CLJS.J.g(a,$CLJS.Li);$CLJS.J.g(a,$CLJS.Fx);return new $CLJS.Q(null,2,5,$CLJS.R,[["[",$CLJS.p.h(b),"]"].join(""),c],null)});
$CLJS.ffa=Dy(function(a){var b=$CLJS.O(a),c=$CLJS.J.g(b,$CLJS.ns);a=$CLJS.J.g(b,$CLJS.tx);var d=$CLJS.J.g(b,$CLJS.Li);$CLJS.J.g(b,$CLJS.Fx);b=cfa(c);d=Ey(Ay(Cy(Cy(Cy(new $CLJS.Q(null,2,5,$CLJS.R,["",$CLJS.Ef],null),"[",b),a,b),"]",b)),d);a=$CLJS.I(d,0,null);d=$CLJS.I(d,1,null);return $CLJS.ge(a,d)});
$CLJS.gfa=Dy(function(a){a=$CLJS.O(a);$CLJS.J.g(a,$CLJS.ns);var b=$CLJS.J.g(a,$CLJS.tx),c=$CLJS.J.g(a,$CLJS.Li);$CLJS.J.g(a,$CLJS.Fx);return new $CLJS.Q(null,2,5,$CLJS.R,[["[",$CLJS.p.h(b),"]"].join(""),$CLJS.Oh.l($CLJS.H([c]))],null)});