var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./clojure.string.js");require("./medley.core.js");require("./metabase.lib.aggregation.js");require("./metabase.lib.binning.js");require("./metabase.lib.breakout.js");require("./metabase.lib.expression.js");require("./metabase.lib.field.js");require("./metabase.lib.hierarchy.js");require("./metabase.lib.join.js");require("./metabase.lib.join.util.js");require("./metabase.lib.metadata.js");require("./metabase.lib.metadata.calculation.js");require("./metabase.lib.normalize.js");require("./metabase.lib.schema.js");require("./metabase.lib.schema.id.js");require("./metabase.lib.temporal_bucket.js");require("./metabase.lib.util.js");require("./metabase.shared.util.i18n.js");require("./metabase.util.js");require("./metabase.util.malli.js");
'use strict';var Zsa,$sa,k7,ata,bta,cta,dta,eta,fta,gta,l7,m7,n7,hta,o7;
Zsa=function(a){return function(b){var c=$CLJS.bf($CLJS.dh);return function(){function d(l,m){var t=a.h?a.h(m):a.call(null,m);if($CLJS.Jd($CLJS.q(c),t))return l;c.md(null,$CLJS.de.g(c.Lb(null),t));return b.g?b.g(l,m):b.call(null,l,m)}function e(l){return b.h?b.h(l):b.call(null,l)}function f(){return b.o?b.o():b.call(null)}var k=null;k=function(l,m){switch(arguments.length){case 0:return f.call(this);case 1:return e.call(this,l);case 2:return d.call(this,l,m)}throw Error("Invalid arity: "+arguments.length);
};k.o=f;k.h=e;k.g=d;return k}()}};$sa=function(a,b,c){return $CLJS.gg.j($CLJS.Ef,$CLJS.hD(function(d){return $CLJS.P_.v(a,b,d,new $CLJS.h(null,2,[$CLJS.z_,c,$CLJS.t_,!1],null))}),$CLJS.BM.h($CLJS.DV(a,b)))};k7=function(a,b,c){return $CLJS.gg.j($CLJS.Ef,$CLJS.hD(function(d){return $CLJS.N_.v(a,b,d,c)}),$CLJS.BM.h($CLJS.DV(a,b)))};$CLJS.n3=function(a,b){return $CLJS.fb(function(c,d){return $CLJS.PV.l(c,d,$CLJS.T,$CLJS.H([$CLJS.P6,$CLJS.N_.j(c,d,$CLJS.DV(c,d))]))},a,$CLJS.ot(0,$CLJS.CV(a,b)))};
ata=function(a,b){a=$CLJS.DV(a,b);a=$CLJS.O(a);var c=$CLJS.J.g(a,$CLJS.Us),d=$CLJS.J.g(a,$CLJS.MU);b=$CLJS.P6.h(a);if($CLJS.n(b))return b;var e=$CLJS.lU.h(a);if($CLJS.n(e)&&$CLJS.n(function(){var k=$CLJS.E.g(c,$CLJS.$U);return k?k:d}())){var f=function(){var k=c instanceof $CLJS.M?c.S:null;switch(k){case "mbql.stage/native":return $CLJS.UY;case "mbql.stage/mbql":return $CLJS.NY;default:throw Error(["No matching clause: ",$CLJS.p.h(k)].join(""));}}();return $CLJS.Ie(function(){return function m(l){return new $CLJS.pe(null,
function(){for(;;){var t=$CLJS.y(l);if(t){if($CLJS.Bd(t)){var u=$CLJS.mc(t),v=$CLJS.D(u),x=$CLJS.se(v);a:for(var A=0;;)if(A<v){var C=$CLJS.ld(u,A);C=$CLJS.zk.l($CLJS.H([new $CLJS.h(null,2,[$CLJS.vY,$CLJS.U.h(C),$CLJS.KY,$CLJS.U.h(C)],null),C,new $CLJS.h(null,1,[$CLJS.IJ,f],null)]));x.add(C);A+=1}else{u=!0;break a}return u?$CLJS.ve($CLJS.xe(x),m($CLJS.nc(t))):$CLJS.ve($CLJS.xe(x),null)}x=$CLJS.z(t);return $CLJS.ge($CLJS.zk.l($CLJS.H([new $CLJS.h(null,2,[$CLJS.vY,$CLJS.U.h(x),$CLJS.KY,$CLJS.U.h(x)],
null),x,new $CLJS.h(null,1,[$CLJS.IJ,f],null)])),m($CLJS.Mc(t)))}return null}},null,null)}($CLJS.AV.h(e))}())}return null};
bta=function(a,b,c){return $CLJS.Ie(function(){return function f(e){return new $CLJS.pe(null,function(){for(;;){var k=$CLJS.y(e);if(k){if($CLJS.Bd(k)){var l=$CLJS.mc(k),m=$CLJS.D(l),t=$CLJS.se(m);return function(){for(var v=0;;)if(v<m){var x=$CLJS.ld(l,v),A=t,C=$CLJS.T,G=C.l,K=x,S=$CLJS.uz($CLJS.vY,$CLJS.U)(x);x=$CLJS.a1(a,x);x=c.h?c.h(x):c.call(null,x);C=G.call(C,K,$CLJS.IJ,$CLJS.ZJ,$CLJS.H([$CLJS.vY,S,$CLJS.KY,x]));A.add(C);v+=1}else return!0}()?$CLJS.ve($CLJS.xe(t),f($CLJS.nc(k))):$CLJS.ve($CLJS.xe(t),
null)}var u=$CLJS.z(k);return $CLJS.ge($CLJS.T.l(u,$CLJS.IJ,$CLJS.ZJ,$CLJS.H([$CLJS.vY,$CLJS.uz($CLJS.vY,$CLJS.U)(u),$CLJS.KY,function(){var v=$CLJS.a1(a,u);return c.h?c.h(v):c.call(null,v)}()])),f($CLJS.Mc(k)))}return null}},null,null)}($CLJS.p5.g(a,b))}())};
cta=function(a,b,c){return $CLJS.Ie(function(){return function f(e){return new $CLJS.pe(null,function(){for(;;){var k=$CLJS.y(e);if(k){if($CLJS.Bd(k)){var l=$CLJS.mc(k),m=$CLJS.D(l),t=$CLJS.se(m);return function(){for(var v=0;;)if(v<m){var x=$CLJS.ld(l,v),A=t,C=$CLJS.T,G=C.l,K=x,S=$CLJS.U.h(x);x=$CLJS.U.h(x);x=c.h?c.h(x):c.call(null,x);C=G.call(C,K,$CLJS.IJ,$CLJS.hK,$CLJS.H([$CLJS.vY,S,$CLJS.KY,x]));A.add(C);v+=1}else return!0}()?$CLJS.ve($CLJS.xe(t),f($CLJS.nc(k))):$CLJS.ve($CLJS.xe(t),null)}var u=
$CLJS.z(k);return $CLJS.ge($CLJS.T.l(u,$CLJS.IJ,$CLJS.hK,$CLJS.H([$CLJS.vY,$CLJS.U.h(u),$CLJS.KY,function(){var v=$CLJS.U.h(u);return c.h?c.h(v):c.call(null,v)}()])),f($CLJS.Mc(k)))}return null}},null,null)}($CLJS.W3.g(a,b))}())};
dta=function(a,b,c){var d=$CLJS.DV(a,b);if($CLJS.n(d)){d=$CLJS.O(d);var e=$CLJS.J.g(d,$CLJS.TD);return $CLJS.Ie(function(){return function l(k){return new $CLJS.pe(null,function(){for(;;){var m=$CLJS.y(k);if(m){if($CLJS.Bd(m)){var t=$CLJS.mc(m),u=$CLJS.D(t),v=$CLJS.se(u);return function(){for(var K=0;;)if(K<u){var S=$CLJS.ld(t,K),X=$CLJS.I(S,0,null),ba=function(){var ua=X;ua=ua instanceof $CLJS.M?ua.S:null;switch(ua){case "field":return $CLJS.SY;case "expression":return $CLJS.EY;default:throw Error(["No matching clause: ",
$CLJS.p.h(ua)].join(""));}}(),ha=$CLJS.c_.j(a,b,S);$CLJS.we(v,$CLJS.T.l(ha,$CLJS.IJ,ba,$CLJS.H([$CLJS.vY,$CLJS.G_.j(a,b,ha),$CLJS.KY,function(){var ua=$CLJS.a1(a,ha);return c.h?c.h(ua):c.call(null,ua)}()])));K+=1}else return!0}()?$CLJS.ve($CLJS.xe(v),l($CLJS.nc(m))):$CLJS.ve($CLJS.xe(v),null)}var x=$CLJS.z(m),A=$CLJS.I(x,0,null),C=function(){var K=A;K=K instanceof $CLJS.M?K.S:null;switch(K){case "field":return $CLJS.SY;case "expression":return $CLJS.EY;default:throw Error(["No matching clause: ",
$CLJS.p.h(K)].join(""));}}(),G=$CLJS.c_.j(a,b,x);return $CLJS.ge($CLJS.T.l(G,$CLJS.IJ,C,$CLJS.H([$CLJS.vY,$CLJS.G_.j(a,b,G),$CLJS.KY,function(){var K=$CLJS.a1(a,G);return c.h?c.h(K):c.call(null,K)}()])),l($CLJS.Mc(m)))}return null}},null,null)}(e)}())}return null};eta=function(a,b,c){return $CLJS.Ie($CLJS.gg.j($CLJS.Ef,$CLJS.hD(function(d){return d.j?d.j(a,b,c):d.call(null,a,b,c)}),new $CLJS.Q(null,2,5,$CLJS.R,[bta,cta],null)))};
fta=function(a,b,c){var d=$CLJS.l1(a,b);return $CLJS.n(d)?$CLJS.Ie(function(){return function k(f){return new $CLJS.pe(null,function(){for(;;){var l=$CLJS.y(f);if(l){if($CLJS.Bd(l)){var m=$CLJS.mc(l),t=$CLJS.D(m),u=$CLJS.se(t);return function(){for(var A=0;;)if(A<t){var C=$CLJS.ld(m,A);var G=$CLJS.uz($CLJS.KY,$CLJS.vY)(C);G=$CLJS.n(G)?G:$CLJS.G_.j(a,b,C);C=$CLJS.ak.l($CLJS.zk.l($CLJS.H([C,new $CLJS.h(null,3,[$CLJS.IJ,$CLJS.wY,$CLJS.vY,G,$CLJS.KY,c.h?c.h(G):c.call(null,G)],null),$CLJS.n($CLJS.f1.h(C))?
$CLJS.Hl(C,new $CLJS.Q(null,1,5,$CLJS.R,[$CLJS.f1],null)):null])),$CLJS.HV,$CLJS.H([$CLJS.rD]));u.add(C);A+=1}else return!0}()?$CLJS.ve($CLJS.xe(u),k($CLJS.nc(l))):$CLJS.ve($CLJS.xe(u),null)}var v=$CLJS.z(l),x=function(){var A=$CLJS.uz($CLJS.KY,$CLJS.vY)(v);return $CLJS.n(A)?A:$CLJS.G_.j(a,b,v)}();return $CLJS.ge($CLJS.ak.l($CLJS.zk.l($CLJS.H([v,new $CLJS.h(null,3,[$CLJS.IJ,$CLJS.wY,$CLJS.vY,x,$CLJS.KY,c.h?c.h(x):c.call(null,x)],null),$CLJS.n($CLJS.f1.h(v))?$CLJS.Hl(v,new $CLJS.Q(null,1,5,$CLJS.R,
[$CLJS.f1],null)):null])),$CLJS.HV,$CLJS.H([$CLJS.rD])),k($CLJS.Mc(l)))}return null}},null,null)}($CLJS.N_.j(a,d,$CLJS.DV(a,d)))}()):null};gta=function(a,b,c,d){return $CLJS.n(c)?(c=$CLJS.$Z(a,c),$CLJS.n(c)?$CLJS.Ie($CLJS.P_.v(a,b,c,d)):null):null};
l7=function(a,b,c){return $CLJS.Ie(function(){return function f(e){return new $CLJS.pe(null,function(){for(;;){var k=$CLJS.y(e);if(k){if($CLJS.Bd(k)){var l=$CLJS.mc(k),m=$CLJS.D(l),t=$CLJS.se(m);return function(){for(var v=0;;)if(v<m){var x=$CLJS.ld(l,v),A=t;var C=$CLJS.nA.h(x);var G=$CLJS.T.l,K=x,S=$CLJS.U.h(x);x=$CLJS.U.h(x);x=c.h?c.h(x):c.call(null,x);C=$CLJS.j1(G.call($CLJS.T,K,$CLJS.IJ,$CLJS.EY,$CLJS.H([$CLJS.vY,S,$CLJS.KY,x])),$CLJS.Ci,$CLJS.n(C)?C:$CLJS.lj);A.add(C);v+=1}else return!0}()?$CLJS.ve($CLJS.xe(t),
f($CLJS.nc(k))):$CLJS.ve($CLJS.xe(t),null)}var u=$CLJS.z(k);return $CLJS.ge(function(){var v=$CLJS.nA.h(u),x=$CLJS.T.l,A=u,C=$CLJS.U.h(u);var G=$CLJS.U.h(u);G=c.h?c.h(G):c.call(null,G);return $CLJS.j1(x.call($CLJS.T,A,$CLJS.IJ,$CLJS.EY,$CLJS.H([$CLJS.vY,C,$CLJS.KY,G])),$CLJS.Ci,$CLJS.n(v)?v:$CLJS.lj)}(),f($CLJS.Mc(k)))}return null}},null,null)}($CLJS.mpa.g(a,b))}())};
m7=function(a,b,c){var d=$CLJS.O(c),e=$CLJS.J.g(d,$CLJS.z_);return $CLJS.jk.g(function(f){return $CLJS.ak.l(f,$CLJS.$Y,$CLJS.H([$CLJS.HV,$CLJS.NV,$CLJS.WJ]))},function(){var f=fta(a,b,e);if($CLJS.n(f))return f;f=$CLJS.DV(a,b);f=$CLJS.O(f);var k=$CLJS.J.g(f,$CLJS.cO),l=$CLJS.J.g(f,$CLJS.MU),m=$CLJS.n(k)?function(){var t=$CLJS.YZ(a,k);return $CLJS.P_.v(a,b,t,d)}():null;if($CLJS.n(m))return m;l=$CLJS.n(l)?gta(a,b,l,$CLJS.T.j(d,$CLJS.t_,!1)):null;return $CLJS.n(l)?l:function v(u){return new $CLJS.pe(null,
function(){for(;;){var x=$CLJS.y(u);if(x){if($CLJS.Bd(x)){var A=$CLJS.mc(x),C=$CLJS.D(A),G=$CLJS.se(C);return function(){for(var S=0;;)if(S<C){var X=$CLJS.ld(A,S),ba=G,ha=$CLJS.T,ua=ha.l,Ua=X,Db=$CLJS.U.h(X);X=$CLJS.U.h(X);X=e.h?e.h(X):e.call(null,X);ha=ua.call(ha,Ua,$CLJS.IJ,$CLJS.UY,$CLJS.H([$CLJS.vY,Db,$CLJS.KY,X]));ba.add(ha);S+=1}else return!0}()?$CLJS.ve($CLJS.xe(G),v($CLJS.nc(x))):$CLJS.ve($CLJS.xe(G),null)}var K=$CLJS.z(x);return $CLJS.ge($CLJS.T.l(K,$CLJS.IJ,$CLJS.UY,$CLJS.H([$CLJS.vY,$CLJS.U.h(K),
$CLJS.KY,function(){var S=$CLJS.U.h(K);return e.h?e.h(S):e.call(null,S)}()])),v($CLJS.Mc(x)))}return null}},null,null)}($CLJS.AV.h($CLJS.lU.h(f)))}())};
n7=function(a,b){var c=$CLJS.I(a,0,null);$CLJS.I(a,1,null);var d=$CLJS.I(a,2,null);switch(c instanceof $CLJS.M?c.S:null){case "field":if("number"===typeof d||"string"===typeof d)return $CLJS.E.g(d,$CLJS.Si.h(b));throw $CLJS.ji("unknown type of :field ref in lib.stage/ref-to?",new $CLJS.h(null,2,[$CLJS.WQ,a,$CLJS.Ni,b],null));case "expression":return $CLJS.E.g(d,$CLJS.U.h(b));default:throw $CLJS.ji("unknown clause in lib.stage/ref-to?",new $CLJS.h(null,2,[$CLJS.WQ,a,$CLJS.Ni,b],null));}};
hta=function(a,b,c){var d=$CLJS.$E.h($CLJS.DV(a,b));return $CLJS.n(d)?function k(f){return new $CLJS.pe(null,function(){for(;;){var l=$CLJS.y(f);if(l){var m=l;if($CLJS.Bd(m)){var t=$CLJS.mc(m),u=$CLJS.D(t),v=$CLJS.se(u);return function(){for(var A=0;;)if(A<u){var C=$CLJS.ld(t,A);$CLJS.we(v,function(){var G=$CLJS.rG(function(X,ba){return function(ha){return n7(ha,ba)}}(A,C,t,u,v,m,l,d,d),d);if($CLJS.n(G)){var K=$CLJS.L6(G);G=$CLJS.c2(G);G=$CLJS.O(G);G=$CLJS.J.g(G,$CLJS.Ek);var S=C;K=$CLJS.n(K)?$CLJS.I4(S,
K):S;return $CLJS.n(G)?$CLJS.U2(K,G):K}return C}());A+=1}else return!0}()?$CLJS.ve($CLJS.xe(v),k($CLJS.nc(m))):$CLJS.ve($CLJS.xe(v),null)}var x=$CLJS.z(m);return $CLJS.ge(function(){var A=$CLJS.rG(function(K){return function(S){return n7(S,K)}}(x,m,l,d,d),d);if($CLJS.n(A)){var C=$CLJS.L6(A);A=$CLJS.c2(A);A=$CLJS.O(A);A=$CLJS.J.g(A,$CLJS.Ek);var G=x;C=$CLJS.n(C)?$CLJS.I4(G,C):G;return $CLJS.n(A)?$CLJS.U2(C,A):C}return x}(),k($CLJS.Mc(m)))}return null}},null,null)}(c):c};
o7=new $CLJS.M("metabase.lib.stage","stage","metabase.lib.stage/stage",1448689281);$CLJS.Sqa={};$CLJS.rE($CLJS.TU,o7);$CLJS.rE($CLJS.$U,o7);$CLJS.H0.m(null,$CLJS.TU,function(a){return $CLJS.G0(a,new $CLJS.h(null,2,[$CLJS.aF,$CLJS.Xe($CLJS.jk,$CLJS.H0),$CLJS.gV,$CLJS.Xe($CLJS.jk,$CLJS.H0)],null))});$CLJS.K_.m(null,o7,function(){throw $CLJS.ji("You can't calculate a metadata map for a stage! Use lib.metadata.calculation/returned-columns-method instead.",$CLJS.N);});
$CLJS.O_.m(null,o7,function(a,b,c,d){d=$CLJS.O(d);c=$CLJS.J.g(d,$CLJS.z_);var e=$CLJS.J.g(d,$CLJS.t_);a=$CLJS.n3(a,b);var f=$CLJS.O(d);var k=$CLJS.J.g(f,$CLJS.z_),l=$CLJS.J.g(f,$CLJS.x_),m=$CLJS.J.g(f,$CLJS.D_);f=$CLJS.jf.l(m7(a,b,f),$CLJS.n(m)?l7(a,b,k):null,$CLJS.H([$CLJS.n(l)?$sa(a,b,k):null]));k=$CLJS.jf.g;d=$CLJS.n(e)?(e=$CLJS.Wa($CLJS.MU.h($CLJS.DV(a,b))))?e:$CLJS.B_.h(d):e;return hta(a,b,k.call($CLJS.jf,f,$CLJS.n(d)?$CLJS.b1(a,b,f,c):null))});
$CLJS.M_.m(null,o7,function(a,b,c,d){c=$CLJS.O(d);d=$CLJS.J.g(c,$CLJS.z_);var e=ata(a,b);if($CLJS.n(e))return e;a=$CLJS.n3(a,b);e=eta(a,b,d);var f=dta(a,b,d);return $CLJS.n(e)?$CLJS.gg.g(e,f):$CLJS.n(f)?($CLJS.oh(f),$CLJS.gg.j($CLJS.Ef,Zsa(function(k){return $CLJS.ak.l(k,$CLJS.YY,$CLJS.H([$CLJS.IJ,$CLJS.t0,$CLJS.KY]))}),$CLJS.jf.g(f,k7(a,b,c)))):$CLJS.jf.l(m7(a,b,new $CLJS.h(null,2,[$CLJS.t_,!1,$CLJS.z_,d],null)),l7(a,b,d),$CLJS.H([k7(a,b,c)]))});$CLJS.E_.m(null,$CLJS.$U,function(){return $CLJS.LD("Native query")});
var p7=new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.cO,$CLJS.MU,$CLJS.BM],null),q7=new $CLJS.Q(null,5,5,$CLJS.R,[$CLJS.aF,$CLJS.$E,$CLJS.gV,$CLJS.LQ,$CLJS.iR],null);
$CLJS.E_.m(null,$CLJS.TU,function(a,b,c,d){var e=$CLJS.n3(a,b);a=$CLJS.Ie(function(){var f=$CLJS.gg.j($CLJS.N,$CLJS.hk.g($CLJS.mB,$CLJS.kf.h(function(l){return new $CLJS.Q(null,2,5,$CLJS.R,[l,$CLJS.Goa.j(e,b,l)],null)})),new $CLJS.Q(null,2,5,$CLJS.R,[p7,q7],null)),k=$CLJS.gs(" + ",$CLJS.ik.g($CLJS.Bz,$CLJS.kf.g(f,p7)));f=$CLJS.kf.g(f,q7);return $CLJS.gs(", ",$CLJS.ik.g($CLJS.Bz,$CLJS.ge(k,f)))}());if($CLJS.n(a))return a;a=$CLJS.l1(e,b);return $CLJS.n(a)?$CLJS.e_.v(e,a,$CLJS.DV(e,a),d):null});