var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./shadow.js.shim.module$crc_32.js");require("./clojure.set.js");require("./clojure.string.js");require("./medley.core.js");require("./metabase.lib.common.js");require("./metabase.lib.dispatch.js");require("./metabase.lib.hierarchy.js");require("./metabase.lib.options.js");require("./metabase.lib.schema.js");require("./metabase.lib.schema.common.js");require("./metabase.lib.schema.expression.js");require("./metabase.lib.schema.id.js");require("./metabase.lib.schema.ref.js");require("./metabase.mbql.util.js");require("./metabase.shared.util.i18n.js");require("./metabase.util.js");require("./metabase.util.malli.js");
'use strict';var qV,sma,tma,yV,uma,vma,xma,uV,yma,wma;qV=function(a){return a+1};$CLJS.rV=function(a){if("string"===typeof a){var b=$CLJS.ph(/[+-]?\d+/,a);return $CLJS.n(b)?(a=parseInt(a),a<=Number.MAX_SAFE_INTEGER&&a>=Number.MIN_SAFE_INTEGER?a:null):b}throw Error($CLJS.Nl(a));};
sma=function(a){var b=new $CLJS.Fa,c=$CLJS.st;$CLJS.st=new $CLJS.tc(b);try{var d=$CLJS.st,e=$CLJS.Wa($CLJS.Au(d)),f=$CLJS.st;$CLJS.st=e?$CLJS.ru(d):d;try{d=$CLJS.Cu;$CLJS.Cu=!0;try{$CLJS.Eu(a)}finally{$CLJS.Cu=d}$CLJS.E.g(0,$CLJS.zt($CLJS.st,$CLJS.Bt))||$CLJS.bc($CLJS.st,"\n");$CLJS.yt()}finally{$CLJS.st=f}$CLJS.wh($CLJS.p.h(b))}finally{$CLJS.st=c}};$CLJS.sV=function(a,b){return $CLJS.P.j($CLJS.ia,a,b)};
$CLJS.tV=function(a){var b=$CLJS.ou;$CLJS.ou=120;try{var c=new $CLJS.Fa,d=$CLJS.Ra,e=$CLJS.Sa;$CLJS.Ra=!0;$CLJS.Sa=function(f){return c.append(f)};try{sma(a)}finally{$CLJS.Sa=e,$CLJS.Ra=d}return $CLJS.p.h(c)}finally{$CLJS.ou=b}};
tma=function(a){a=$CLJS.O(a);var b=$CLJS.J.j(a,$CLJS.CU,$CLJS.Ud),c=$CLJS.J.j(a,$CLJS.zU,function(f,k){return[$CLJS.p.h(f),"_",$CLJS.p.h(k)].join("")}),d=$CLJS.Ze($CLJS.N),e=$CLJS.Ze($CLJS.N);return function(){function f(m,t){for(;;){var u=b.h?b.h(t):b.call(null,t),v=function(){var A=new $CLJS.Q(null,2,5,$CLJS.R,[m,u],null),C=$CLJS.q(d);return C.h?C.h(A):C.call(null,A)}();if($CLJS.n(v))return v;var x=$CLJS.J.g($CLJS.Qh.v(e,$CLJS.kk,u,$CLJS.RC(qV,0)),u);if($CLJS.E.g(x,1))return $CLJS.Qh.v(d,$CLJS.T,
new $CLJS.Q(null,2,5,$CLJS.R,[m,u],null),t),t;t=function(){var A=t,C=$CLJS.p.h(x);return c.g?c.g(A,C):c.call(null,A,C)}()}}function k(m){var t=l,u=t.g;null==uV&&(uV=$CLJS.Ze(0));var v=$CLJS.Hh.h([$CLJS.p.h("G__"),$CLJS.p.h($CLJS.Qh.g(uV,qV))].join(""));return u.call(t,v,m)}var l=null;l=function(m,t){switch(arguments.length){case 1:return k.call(this,m);case 2:return f.call(this,m,t)}throw Error("Invalid arity: "+arguments.length);};l.h=k;l.g=f;return l}()};
$CLJS.vV=function(a){var b=$CLJS.Ad(a);return b?(b=$CLJS.z(a)instanceof $CLJS.M)?(a=$CLJS.J.g(a,1),$CLJS.yd(a)&&$CLJS.Jd(a,$CLJS.AD)):b:b};$CLJS.wV=function(a){return $CLJS.vV(a)?$CLJS.rD.h($CLJS.HD(a)):null};$CLJS.xV=function(a,b){return $CLJS.JD($CLJS.vV(a)?a:new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.nj,new $CLJS.h(null,2,[$CLJS.AD,$CLJS.p.h($CLJS.KD()),$CLJS.Ci,$CLJS.OD(a)],null),a],null),function(c){return $CLJS.ak.l($CLJS.T.j(c,$CLJS.rD,b),$CLJS.U,$CLJS.H([$CLJS.nD]))})};
yV=function(a,b,c){var d=$CLJS.Jd(a,b)?$CLJS.kk.j(a,b,function(e){return $CLJS.Ad(e)&&$CLJS.E.g($CLJS.z(e),$CLJS.mr)?$CLJS.Ff($CLJS.df(1,e)):new $CLJS.Q(null,1,5,$CLJS.R,[e],null)}):a;return $CLJS.Jd(a,b)?$CLJS.xU(d,$CLJS.He([b,c])):d};uma=function(a){var b=$CLJS.Hl(a,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.cO,$CLJS.FP],null));b=zV.h?zV.h(b):zV.call(null,b);return $CLJS.nV($CLJS.T.l(yV($CLJS.ak.l(a,$CLJS.cO,$CLJS.H([$CLJS.FP])),$CLJS.NQ,$CLJS.rK),$CLJS.Us,$CLJS.jK,$CLJS.H([$CLJS.oK,b])))};
vma=function(a){return $CLJS.jk.g(uma,a)};xma=function(a){return $CLJS.n(a)?$CLJS.T.j($CLJS.kk.j($CLJS.ol(a)?new $CLJS.h(null,1,[$CLJS.AV,a],null):a,$CLJS.AV,function(b){return $CLJS.jk.g(function(c){return $CLJS.T.j($CLJS.yz(c,$CLJS.Zz),$CLJS.Us,$CLJS.GJ)},b)}),$CLJS.Us,wma):null};
$CLJS.BV=function(a){if($CLJS.E.g($CLJS.Us.h(a),$CLJS.fV))return a;var b=$CLJS.aj.h(a);b=b instanceof $CLJS.M?b.S:null;switch(b){case "native":return $CLJS.zk.l($CLJS.H([new $CLJS.h(null,2,[$CLJS.Us,$CLJS.fV,$CLJS.oK,new $CLJS.Q(null,1,5,$CLJS.R,[$CLJS.zk.l($CLJS.H([new $CLJS.h(null,1,[$CLJS.Us,$CLJS.$U],null),$CLJS.xU($CLJS.gP.h(a),new $CLJS.h(null,1,[$CLJS.HE,$CLJS.gP],null))]))],null)],null),$CLJS.ak.l(a,$CLJS.aj,$CLJS.H([$CLJS.gP]))]));case "query":return $CLJS.zk.l($CLJS.H([new $CLJS.h(null,
2,[$CLJS.Us,$CLJS.fV,$CLJS.oK,zV($CLJS.HE.h(a))],null),$CLJS.ak.l(a,$CLJS.aj,$CLJS.H([$CLJS.HE]))]));default:throw Error(["No matching clause: ",$CLJS.p.h(b)].join(""));}};$CLJS.CV=function(a,b){a=$CLJS.O(a);a=$CLJS.J.g(a,$CLJS.oK);var c=0>b?$CLJS.D(a)+b:b;if(c>=$CLJS.D(a)||0>c)throw $CLJS.ji($CLJS.iD("Stage {0} does not exist",$CLJS.H([b])),new $CLJS.h(null,1,[yma,$CLJS.D(a)],null));return c};
$CLJS.DV=function(a,b){a=$CLJS.BV(a);a=$CLJS.O(a);var c=$CLJS.J.g(a,$CLJS.oK);return $CLJS.J.g($CLJS.Ff(c),$CLJS.CV(a,b))};$CLJS.EV=function(a){return"string"===typeof a&&(a=$CLJS.qh(/^card__(\d+)$/,a),$CLJS.n(a))?($CLJS.I(a,0,null),a=$CLJS.I(a,1,null),$CLJS.rV(a)):null};$CLJS.GV=function(){return $CLJS.hk.g(FV,tma($CLJS.H([$CLJS.CU,$CLJS.Vz,$CLJS.zU,function(a,b){return FV.h([$CLJS.p.h(a),"_",$CLJS.p.h(b)].join(""))}])))};uV=null;
$CLJS.HV=new $CLJS.M("metabase.lib.field","temporal-unit","metabase.lib.field/temporal-unit",602312727);$CLJS.IV=new $CLJS.M("metabase.lib.util","cannot-remove-final-join-condition","metabase.lib.util/cannot-remove-final-join-condition",-470911224);$CLJS.JV=new $CLJS.M(null,"join","join",-758861890);$CLJS.KV=new $CLJS.M(null,"stage","stage",1843544772);yma=new $CLJS.M(null,"num-stages","num-stages",1426797535);$CLJS.AV=new $CLJS.M(null,"columns","columns",1998437288);
$CLJS.LV=new $CLJS.M("metabase.lib.field","original-effective-type","metabase.lib.field/original-effective-type",34164372);$CLJS.MV=new $CLJS.M(null,"table","table",-564943036);wma=new $CLJS.M("metadata","results","metadata/results",330329298);$CLJS.NV=new $CLJS.M("metabase.lib.field","binning","metabase.lib.field/binning",-222751823);var zma,Ama,Bma,Cma,Dma,zV,FV;zma=$CLJS.Ze($CLJS.N);Ama=$CLJS.Ze($CLJS.N);Bma=$CLJS.Ze($CLJS.N);Cma=$CLJS.Ze($CLJS.N);Dma=$CLJS.J.j(new $CLJS.h(null,1,[$CLJS.Jk,$CLJS.bB],null),$CLJS.Jk,$CLJS.Xh.o?$CLJS.Xh.o():$CLJS.Xh.call(null));$CLJS.OV=new $CLJS.fi($CLJS.Hh.g("metabase.lib.util","custom-name-method"),$CLJS.SA,Dma,zma,Ama,Bma,Cma);$CLJS.OV.m(null,$CLJS.ei,function(a){return $CLJS.vV(a)?$CLJS.uz($CLJS.nD,$CLJS.rD)($CLJS.HD(a)):null});
zV=function zV(a){a=$CLJS.O(a);var c=$CLJS.J.g(a,$CLJS.FP),d=$CLJS.J.g(a,$CLJS.PN);c=$CLJS.n(c)?zV.h?zV.h(c):zV.call(null,c):$CLJS.Ef;d=xma(d);var e=$CLJS.D(c)-1;c=$CLJS.n($CLJS.n(d)?!(0>e):d)?$CLJS.UK(c,new $CLJS.Q(null,2,5,$CLJS.R,[e,$CLJS.lU],null),d):c;d=$CLJS.n($CLJS.gP.h(a))?$CLJS.$U:$CLJS.TU;a=$CLJS.zk.l($CLJS.H([new $CLJS.h(null,1,[$CLJS.Us,d],null),$CLJS.ak.l(a,$CLJS.FP,$CLJS.H([$CLJS.PN]))]));a=$CLJS.y($CLJS.BM.h(a))?$CLJS.kk.j(a,$CLJS.BM,vma):a;a=yV(a,$CLJS.PE,$CLJS.gV);return $CLJS.de.g(c,
a)};
$CLJS.PV=function(){function a(c,d,e,f){var k=null;if(3<arguments.length){k=0;for(var l=Array(arguments.length-3);k<l.length;)l[k]=arguments[k+3],++k;k=new $CLJS.w(l,0,null)}return b.call(this,c,d,e,k)}function b(c,d,e,f){c=$CLJS.BV(c);c=$CLJS.O(c);var k=$CLJS.J.g(c,$CLJS.oK);d=$CLJS.CV(c,d);e=$CLJS.P.M($CLJS.kk,$CLJS.Ff(k),d,e,f);return $CLJS.T.j(c,$CLJS.oK,e)}a.A=3;a.B=function(c){var d=$CLJS.z(c);c=$CLJS.B(c);var e=$CLJS.z(c);c=$CLJS.B(c);var f=$CLJS.z(c);c=$CLJS.Mc(c);return b(d,e,f,c)};a.l=b;
return a}();
FV=function(){function a(d,e){if((new TextEncoder).encode(d).length<=e)return d;var f;a:for(f=($CLJS.lV.str(d,0)>>>0).toString(16);;)if(8>$CLJS.D(f))f=["0",$CLJS.p.h(f)].join("");else break a;e=new Uint8Array(e-9);e=(new TextEncoder).encodeInto(d,e);return[d.substring(0,e.read),"_",$CLJS.p.h(f)].join("")}function b(d){return c.g?c.g(d,60):c.call(null,d,60)}var c=null;c=function(d,e){switch(arguments.length){case 1:return b.call(this,d);case 2:return a.call(this,d,e)}throw Error("Invalid arity: "+arguments.length);
};c.h=b;c.g=a;return c}();$CLJS.QV=RegExp(" id$","i");