var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./clojure.string.js");require("./metabase.types.js");require("./metabase.util.malli.registry.js");
'use strict';var uga,pD,tD,FD;
$CLJS.gD=function(a,b){return function(){function c(l,m,t){return $CLJS.Fd(function(){var u=a.h?a.h(l):a.call(null,l);return $CLJS.n(u)?(u=a.h?a.h(m):a.call(null,m),$CLJS.n(u)?(u=a.h?a.h(t):a.call(null,t),$CLJS.n(u)?(u=b.h?b.h(l):b.call(null,l),$CLJS.n(u)?(u=b.h?b.h(m):b.call(null,m),$CLJS.n(u)?b.h?b.h(t):b.call(null,t):u):u):u):u):u}())}function d(l,m){return $CLJS.Fd(function(){var t=a.h?a.h(l):a.call(null,l);return $CLJS.n(t)?(t=a.h?a.h(m):a.call(null,m),$CLJS.n(t)?(t=b.h?b.h(l):b.call(null,l),
$CLJS.n(t)?b.h?b.h(m):b.call(null,m):t):t):t}())}function e(l){var m=a.h?a.h(l):a.call(null,l);l=$CLJS.n(m)?b.h?b.h(l):b.call(null,l):m;return $CLJS.Fd(l)}var f=null,k=function(){function l(t,u,v,x){var A=null;if(3<arguments.length){A=0;for(var C=Array(arguments.length-3);A<C.length;)C[A]=arguments[A+3],++A;A=new $CLJS.w(C,0,null)}return m.call(this,t,u,v,A)}function m(t,u,v,x){return $CLJS.Fd(function(){var A=f.j(t,u,v);return $CLJS.n(A)?$CLJS.Te(function(C){var G=a.h?a.h(C):a.call(null,C);return $CLJS.n(G)?
b.h?b.h(C):b.call(null,C):G},x):A}())}l.A=3;l.B=function(t){var u=$CLJS.z(t);t=$CLJS.B(t);var v=$CLJS.z(t);t=$CLJS.B(t);var x=$CLJS.z(t);t=$CLJS.Mc(t);return m(u,v,x,t)};l.l=m;return l}();f=function(l,m,t,u){switch(arguments.length){case 0:return!0;case 1:return e.call(this,l);case 2:return d.call(this,l,m);case 3:return c.call(this,l,m,t);default:var v=null;if(3<arguments.length){v=0;for(var x=Array(arguments.length-3);v<x.length;)x[v]=arguments[v+3],++v;v=new $CLJS.w(x,0,null)}return k.l(l,m,t,
v)}throw Error("Invalid arity: "+arguments.length);};f.A=3;f.B=k.B;f.o=function(){return!0};f.h=e;f.g=d;f.j=c;f.l=k.l;return f}()};$CLJS.hD=function(a){return $CLJS.hk.g($CLJS.kf.h(a),$CLJS.mB)};$CLJS.iD=function(a,b){a=$CLJS.Ms($CLJS.Az(a,/''/,"'"),/\{\d+\}/);return $CLJS.P.j($CLJS.Fs.t,$CLJS.Bk(a),$CLJS.Bk(b))};$CLJS.jD=new $CLJS.M("lib","metadata","lib/metadata",1798917220);$CLJS.kD=new $CLJS.M("metabase.lib.schema.common","positive-int","metabase.lib.schema.common/positive-int",-733946956);
$CLJS.lD=new $CLJS.M(null,"num-bins","num-bins",847672055);$CLJS.mD=new $CLJS.M(null,"mbql","mbql",69346710);$CLJS.nD=new $CLJS.M(null,"display-name","display-name",694513143);uga=new $CLJS.M("metabase.lib.schema.common","external-op","metabase.lib.schema.common/external-op",1918684841);$CLJS.oD=new $CLJS.M("metabase.lib.schema.common","semantic-or-relation-type","metabase.lib.schema.common/semantic-or-relation-type",-158604052);
pD=new $CLJS.M("metabase.lib.schema.common","relation-type","metabase.lib.schema.common/relation-type",1412287664);$CLJS.qD=new $CLJS.M("lib","external-op","lib/external-op",-1470923877);$CLJS.rD=new $CLJS.M("lib","expression-name","lib/expression-name",-1799326590);$CLJS.sD=new $CLJS.M("metabase.lib.schema.common","non-blank-string","metabase.lib.schema.common/non-blank-string",-2032366619);tD=new $CLJS.M("metabase.lib.schema.common","semantic-type","metabase.lib.schema.common/semantic-type",-1623124128);
$CLJS.uD=new $CLJS.M(null,"database-type","database-type",-426840562);$CLJS.vD=new $CLJS.M(null,"operator","operator",-1860875338);$CLJS.wD=new $CLJS.M("metabase.lib.schema.common","int-greater-than-or-equal-to-zero","metabase.lib.schema.common/int-greater-than-or-equal-to-zero",-1646435681);$CLJS.xD=new $CLJS.M("metabase.lib.schema.binning","bin-width","metabase.lib.schema.binning/bin-width",538632740);
$CLJS.yD=new $CLJS.M("metabase.lib.schema.common","options","metabase.lib.schema.common/options",-1078359294);$CLJS.zD=new $CLJS.M("metabase.lib.schema.common","positive-number","metabase.lib.schema.common/positive-number",2061626826);$CLJS.AD=new $CLJS.M("lib","uuid","lib/uuid",-2145250720);$CLJS.BD=new $CLJS.M(null,"x","x",2099068185);$CLJS.CD=new $CLJS.M("metabase.lib.schema.common","base-type","metabase.lib.schema.common/base-type",999524206);
$CLJS.DD=new $CLJS.M(null,"bin-width","bin-width",1377922579);$CLJS.ED=new $CLJS.M(null,"strategy","strategy",-1471631918);FD=new $CLJS.M("metabase.lib.schema.common","uuid","metabase.lib.schema.common/uuid",1172938098);$CLJS.Y($CLJS.sD,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.mr,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Bj,new $CLJS.h(null,1,[$CLJS.ln,1],null)],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Mi,new $CLJS.h(null,1,[$CLJS.ss,"non-blank string"],null),$CLJS.Ve($CLJS.Bz)],null)],null));$CLJS.Y($CLJS.wD,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.rr,new $CLJS.h(null,1,[$CLJS.ln,0],null)],null));$CLJS.Y($CLJS.kD,$CLJS.rl);
$CLJS.Y($CLJS.zD,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Mi,new $CLJS.h(null,1,[$CLJS.ss,"positive number"],null),$CLJS.gD($CLJS.dl,$CLJS.wl)],null));$CLJS.Y(FD,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Bj,new $CLJS.h(null,2,[$CLJS.ln,36,$CLJS.Hj,36],null)],null));
$CLJS.Y(tD,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Mi,new $CLJS.h(null,2,[$CLJS.ss,"valid semantic type",$CLJS.Ds,function(a){a=$CLJS.O(a);a=$CLJS.J.g(a,$CLJS.nj);return["Not a valid semantic type: ",$CLJS.Oh.l($CLJS.H([a]))].join("")}],null),function(a){return $CLJS.nB(a,$CLJS.fj)}],null));
$CLJS.Y(pD,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Mi,new $CLJS.h(null,2,[$CLJS.ss,"valid relation type",$CLJS.Ds,function(a){a=$CLJS.O(a);a=$CLJS.J.g(a,$CLJS.nj);return["Not a valid relation type: ",$CLJS.Oh.l($CLJS.H([a]))].join("")}],null),function(a){return $CLJS.nB(a,$CLJS.oi)}],null));$CLJS.Y($CLJS.oD,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.fr,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,tD],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,pD],null)],null));
$CLJS.Y($CLJS.CD,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Mi,new $CLJS.h(null,2,[$CLJS.ss,"valid base type",$CLJS.Ds,function(a){a=$CLJS.O(a);a=$CLJS.J.g(a,$CLJS.nj);return["Not a valid base type: ",$CLJS.Oh.l($CLJS.H([a]))].join("")}],null),function(a){return $CLJS.nB(a,$CLJS.lj)}],null));
$CLJS.Y($CLJS.yD,new $CLJS.Q(null,8,5,$CLJS.R,[$CLJS.Gj,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.AD,FD],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.nA,new $CLJS.h(null,1,[$CLJS.Ar,!0],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.er,$CLJS.CD],null)],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Ci,new $CLJS.h(null,1,[$CLJS.Ar,!0],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.er,$CLJS.CD],null)],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.yj,new $CLJS.h(null,1,[$CLJS.Ar,!0],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.er,
$CLJS.oD],null)],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.uD,new $CLJS.h(null,1,[$CLJS.Ar,!0],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.er,$CLJS.sD],null)],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.U,new $CLJS.h(null,1,[$CLJS.Ar,!0],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.er,$CLJS.sD],null)],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.nD,new $CLJS.h(null,1,[$CLJS.Ar,!0],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.er,$CLJS.sD],null)],null)],null));
$CLJS.Y(uga,new $CLJS.Q(null,5,5,$CLJS.R,[$CLJS.Gj,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Us,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Nj,$CLJS.qD],null)],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.vD,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.fr,$CLJS.Bj,$CLJS.Qi],null)],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Kr,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.kj,$CLJS.wr],null)],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Yi,new $CLJS.h(null,1,[$CLJS.Ar,!0],null),$CLJS.yD],null)],null));