var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./clojure.string.js");require("./inflections.core.js");require("./medley.core.js");require("./metabase.lib.card.js");require("./metabase.lib.common.js");require("./metabase.lib.dispatch.js");require("./metabase.lib.equality.js");require("./metabase.lib.filter.js");require("./metabase.lib.filter.operator.js");require("./metabase.lib.hierarchy.js");require("./metabase.lib.join.util.js");require("./metabase.lib.metadata.js");require("./metabase.lib.metadata.calculation.js");require("./metabase.lib.options.js");require("./metabase.lib.query.js");require("./metabase.lib.ref.js");require("./metabase.lib.schema.js");require("./metabase.lib.schema.common.js");require("./metabase.lib.schema.expression.js");require("./metabase.lib.schema.filter.js");require("./metabase.lib.schema.join.js");require("./metabase.lib.schema.metadata.js");require("./metabase.lib.schema.temporal_bucketing.js");require("./metabase.lib.temporal_bucket.js");require("./metabase.lib.types.isa.js");require("./metabase.lib.util.js");require("./metabase.mbql.util.match.js");require("./metabase.shared.util.i18n.js");require("./metabase.util.js");require("./metabase.util.log.js");require("./metabase.util.malli.js");
'use strict';var Bqa,Cqa,Dqa,Eqa,Y2,Z2,$2,a3,Fqa,Gqa,Hqa,Iqa,Jqa,Kqa,Lqa,Mqa,Nqa,k3,l3,Oqa,Pqa,Qqa,j3,i3,Rqa,m3;$CLJS.T2=function(a,b){$CLJS.fb(function(c,d){return a.h?a.h(d):a.call(null,d)},null,b)};
Bqa=function(a){return function(b){var c=$CLJS.bf(!0);return function(){function d(l,m){var t=$CLJS.q(c);if($CLJS.n($CLJS.n(t)?a.h?a.h(m):a.call(null,m):t))return l;$CLJS.il(c,null);return b.g?b.g(l,m):b.call(null,l,m)}function e(l){return b.h?b.h(l):b.call(null,l)}function f(){return b.o?b.o():b.call(null)}var k=null;k=function(l,m){switch(arguments.length){case 0:return f.call(this);case 1:return e.call(this,l);case 2:return d.call(this,l,m)}throw Error("Invalid arity: "+arguments.length);};k.o=
f;k.h=e;k.g=d;return k}()}};Cqa=function(a,b){return function f(d,e){return new $CLJS.pe(null,function(){var k;a:{var l=d;for(k=e;;){var m=l;l=$CLJS.I(m,0,null);if(m=$CLJS.y(m)){var t=a.h?a.h(l):a.call(null,l);if($CLJS.Jd(k,t))l=$CLJS.Mc(m);else{k=$CLJS.ge(l,f($CLJS.Mc(m),$CLJS.de.g(k,t)));break a}}else{k=null;break a}}}return k},null,null)}(b,$CLJS.dh)};
Dqa=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;c=arguments[0];d=arguments[1];var e=arguments[2];b=3<b.length?new $CLJS.w(b.slice(3),0,null):null;return $CLJS.Wa($CLJS.y($CLJS.wz(c,d)))?c:$CLJS.P.M($CLJS.vW,c,d,e,b)};$CLJS.U2=function(a,b){return $CLJS.j0.g(a,b instanceof $CLJS.M?b:$CLJS.Ek.h(b))};
$CLJS.V2=function(a,b,c,d){if($CLJS.y(c)){d=$CLJS.jk.g($CLJS.oV,d);var e=$CLJS.gg.j($CLJS.dh,$CLJS.kf.h(function(f){return $CLJS.x1.v(a,b,f,c)}),d);return $CLJS.jk.g(function(f){return $CLJS.T.j(f,$CLJS.LY,$CLJS.Jd(e,f))},c)}return null};$CLJS.W2=function(a){return $CLJS.E.g($CLJS.SA(a),$CLJS.jK)};Eqa=function(a,b){return $CLJS.n($CLJS.TD.h(a))?$CLJS.kk.j(a,$CLJS.TD,function(c){return $CLJS.xd(c)?$CLJS.jk.g(function(d){return $CLJS.X2.g?$CLJS.X2.g(d,b):$CLJS.X2.call(null,d,b)},c):c}):a};
Y2=function(a){if($CLJS.n(a)){var b=$CLJS.nf;a:try{if($CLJS.Ad(a)&&4===$CLJS.D(a))try{if($CLJS.F(a,0)instanceof $CLJS.M)try{var c=$CLJS.F(a,2);if($CLJS.Ad(c)&&3===$CLJS.D(c))try{var d=$CLJS.F(c,0);if($CLJS.je(d,$CLJS.lF))try{var e=$CLJS.F(a,3);if($CLJS.Ad(e)&&3===$CLJS.D(e))try{var f=$CLJS.F(e,0);if($CLJS.je(f,$CLJS.lF)){$CLJS.F(e,1);$CLJS.F(e,2);$CLJS.F(c,1);$CLJS.F(c,2);$CLJS.F(a,0);$CLJS.F(a,1);var k=new $CLJS.Q(null,1,5,$CLJS.R,[!0],null)}else throw $CLJS.Z;}catch(m){if(m instanceof Error){var l=
m;if(l===$CLJS.Z)throw $CLJS.Z;throw l;}throw m;}else throw $CLJS.Z;}catch(m){if(m instanceof Error){l=m;if(l===$CLJS.Z)throw $CLJS.Z;throw l;}throw m;}else throw $CLJS.Z;}catch(m){if(m instanceof Error){l=m;if(l===$CLJS.Z)throw $CLJS.Z;throw l;}throw m;}else throw $CLJS.Z;}catch(m){if(m instanceof Error){l=m;if(l===$CLJS.Z)throw $CLJS.Z;throw l;}throw m;}else throw $CLJS.Z;}catch(m){if(m instanceof Error){l=m;if(l===$CLJS.Z)throw $CLJS.Z;throw l;}throw m;}else throw $CLJS.Z;}catch(m){if(m instanceof
Error){l=m;if(l===$CLJS.Z){k=new $CLJS.Q(null,1,5,$CLJS.R,[!1],null);break a}throw l;}throw m;}a=$CLJS.z($CLJS.y(b($CLJS.Ya,k)))}else a=null;return a};Z2=function(a){if($CLJS.n(Y2(a))){$CLJS.I(a,0,null);$CLJS.I(a,1,null);var b=$CLJS.I(a,2,null);$CLJS.I(a,3,null);return b}return null};$2=function(a){return $CLJS.n(Y2(a))?($CLJS.I(a,0,null),$CLJS.I(a,1,null),$CLJS.I(a,2,null),$CLJS.I(a,3,null)):null};
a3=function(a,b){var c=$CLJS.X2;if($CLJS.Wa(Y2(a)))return a;var d=$CLJS.I(a,0,null),e=$CLJS.I(a,1,null),f=$CLJS.I(a,2,null);a=$CLJS.I(a,3,null);return new $CLJS.Q(null,4,5,$CLJS.R,[d,e,f,$CLJS.P.j(c,a,b)],null)};
Fqa=function(a,b,c){return $CLJS.ud($CLJS.rK.h(a))?a:$CLJS.n(b)?Dqa(a,new $CLJS.Q(null,1,5,$CLJS.R,[$CLJS.rK],null),function(d){return function l(f,k){try{if($CLJS.Ad(k)&&3===$CLJS.D(k))try{var m=$CLJS.F(k,0);if($CLJS.je(m,$CLJS.lF))try{var t=$CLJS.F(k,1);if(null!=t?t.C&256||$CLJS.Cc===t.lf||(t.C?0:$CLJS.ab($CLJS.xb,t)):$CLJS.ab($CLJS.xb,t))try{var u=$CLJS.J.j(t,$CLJS.rO,$CLJS.BU);if($CLJS.E.g(u,b))return $CLJS.F(k,2),$CLJS.X2.g?$CLJS.X2.g(k,c):$CLJS.X2.call(null,k,c);throw $CLJS.Z;}catch(x){if(x instanceof
Error){var v=x;if(v===$CLJS.Z)throw $CLJS.Z;throw v;}throw x;}else throw $CLJS.Z;}catch(x){if(x instanceof Error){v=x;if(v===$CLJS.Z)throw $CLJS.Z;throw v;}throw x;}else throw $CLJS.Z;}catch(x){if(x instanceof Error){v=x;if(v===$CLJS.Z)throw $CLJS.Z;throw v;}throw x;}else throw $CLJS.Z;}catch(x){if(x instanceof Error){v=x;if(v===$CLJS.Z)return $CLJS.YV(l,f,k);throw v;}throw x;}}($CLJS.Ef,d)}):$CLJS.kk.j(a,$CLJS.rK,function(d){return $CLJS.jk.g(function(e){return a3(e,$CLJS.H([c]))},d)})};
$CLJS.X2=function(a,b){var c=$CLJS.SA(a);switch(c instanceof $CLJS.M?c.S:null){case "field":return $CLJS.ID(a,$CLJS.GD,$CLJS.H([$CLJS.rO,b]));case "metadata/column":return $CLJS.GD(a,$CLJS.$Y,b);case "mbql/join":return c=$CLJS.Z0(a),Fqa(Eqa($CLJS.GD(a,$CLJS.XD,b),b),c,b);default:return b=$CLJS.Gz($CLJS.xx),$CLJS.n($CLJS.Fz("metabase.lib.join",b))&&$CLJS.Ez("metabase.lib.join",b,$CLJS.vv.l($CLJS.H(["with-join-value should not be called with",$CLJS.Oh.l($CLJS.H([a]))])),null),a}};
$CLJS.b3=function(a,b,c){var d=$CLJS.T.l,e=$CLJS.uz($CLJS.vY,$CLJS.U)(c);a=$CLJS.$0($CLJS.XD.h(a),$CLJS.uz($CLJS.vY,$CLJS.U)(c));b=b.h?b.h(a):b.call(null,a);return d.call($CLJS.T,c,$CLJS.vY,e,$CLJS.H([$CLJS.KY,b]))};Gqa=function(a,b){return $CLJS.Wa(b)?a:$CLJS.jk.g(function(c){var d=$2(c);d=$CLJS.n(d)?$CLJS.n($CLJS.Z0(d))?null:a3(c,$CLJS.H([b])):null;return $CLJS.n(d)?d:c},a)};$CLJS.c3=function(a,b){b=Gqa($CLJS.jk.g($CLJS.pV,b),$CLJS.Z0(a));return $CLJS.GD(a,$CLJS.rK,$CLJS.Ie(b))};
$CLJS.d3=function(a,b){b=b instanceof $CLJS.M?b:$CLJS.E.g(b,$CLJS.Ef)?$CLJS.$y:$CLJS.Ie($CLJS.gg.j($CLJS.Ef,$CLJS.hk.g($CLJS.kf.h($CLJS.oV),function(){var c=$CLJS.Z0(a);return $CLJS.n(c)?$CLJS.kf.h(function(d){return $CLJS.X2(d,c)}):$CLJS.Ud}()),b));return $CLJS.GD(a,$CLJS.TD,b)};
Hqa=function(a,b){b=$CLJS.Fl(function(d){return $CLJS.x1.g(d,a)},b);var c=$CLJS.rG($CLJS.uz($CLJS.EZ,$CLJS.FZ),b);if($CLJS.n(c))return c;b=$CLJS.z(b);if($CLJS.n(b))return b;b=$CLJS.rG($CLJS.EZ,a);if($CLJS.n(b))return b;b=$CLJS.rG($CLJS.FZ,a);return $CLJS.n(b)?b:$CLJS.z(a)};Iqa=function(a){return"string"===typeof a?(0,$CLJS.na)($CLJS.Az(a,/ id$/i,"")):null};
Jqa=function(a,b){var c="string"===typeof a;if(c){if(c="string"===typeof b){c=new $CLJS.Lh(function(){return $CLJS.e2(b)});var d=new $CLJS.Lh(function(){return $CLJS.e2(a)});return $CLJS.E.g(a,b)||$CLJS.E.g(a,$CLJS.q(c))||$CLJS.E.g($CLJS.q(d),b)||$CLJS.E.g($CLJS.q(d),$CLJS.q(c))}return c}return c};
Kqa=function(a,b,c){var d=$CLJS.e_.g($CLJS.E.g($CLJS.Us.h(b),$CLJS.fV)?b:a,b),e=$CLJS.n(c)?Iqa($CLJS.e_.g(a,c)):null,f=Jqa(d,e);return function(){var k=function(){if($CLJS.n(d)){if($CLJS.n(e)){var l=$CLJS.Wa($CLJS.ph(/id/i,e));return l?(l=!f)?[$CLJS.p.h(d)," - ",e].join(""):l:l}return e}return d}();return $CLJS.n(k)?k:$CLJS.n(d)?d:$CLJS.n(e)?e:"source"}()};
Lqa=function(a,b,c,d,e){return function m(k,l){try{if($CLJS.GX(l,$CLJS.lF)&&$CLJS.Fd($CLJS.x1.v(a,b,l,e)))return $CLJS.X2(l,d);throw $CLJS.Z;}catch(u){if(u instanceof Error){var t=u;if(t===$CLJS.Z)return $CLJS.YV(m,k,l);throw t;}throw u;}}($CLJS.Ef,c)};
Mqa=function(a,b,c,d,e,f){c=Lqa(a,b,c,d,f);return function t(l,m){try{if($CLJS.Ad(m)&&4===$CLJS.D(m))try{var u=$CLJS.F(m,2);if($CLJS.GX(u,$CLJS.lF))try{var v=$CLJS.F(m,3);if($CLJS.GX(v,$CLJS.lF)){var x=$CLJS.F(m,3),A=$CLJS.F(m,2),C=$CLJS.F(m,0),G=$CLJS.F(m,1),K=$CLJS.Z0(A),S=$CLJS.Z0(x);if($CLJS.Wa($CLJS.n(K)?K:S))return $CLJS.n($CLJS.x1.v(a,b,x,e))?new $CLJS.Q(null,4,5,$CLJS.R,[C,G,$CLJS.X2(A,d),x],null):new $CLJS.Q(null,4,5,$CLJS.R,[C,G,A,$CLJS.X2(x,d)],null);if($CLJS.E.g(K,d)&&$CLJS.E.g(S,d)){var X=
$CLJS.ID(A,$CLJS.ak,$CLJS.H([$CLJS.rO])),ba=$CLJS.ID(x,$CLJS.ak,$CLJS.H([$CLJS.rO])),ha=null==$CLJS.x1.v(a,b,X,e);var ua=ha?$CLJS.x1.v(a,b,ba,e):ha;return $CLJS.n(ua)?new $CLJS.Q(null,4,5,$CLJS.R,[C,G,A,ba],null):new $CLJS.Q(null,4,5,$CLJS.R,[C,G,X,x],null)}return m}throw $CLJS.Z;}catch(Db){if(Db instanceof Error){var Ua=Db;if(Ua===$CLJS.Z)throw $CLJS.Z;throw Ua;}throw Db;}else throw $CLJS.Z;}catch(Db){if(Db instanceof Error){Ua=Db;if(Ua===$CLJS.Z)throw $CLJS.Z;throw Ua;}throw Db;}else throw $CLJS.Z;
}catch(Db){if(Db instanceof Error){Ua=Db;if(Ua===$CLJS.Z)return $CLJS.YV(t,l,m);throw Ua;}throw Db;}}($CLJS.Ef,c)};Nqa=function(a,b){var c=$CLJS.GV();$CLJS.T2(c,b);return c(a)};
$CLJS.e3=function(a,b,c){if($CLJS.Jd(c,$CLJS.XD))return c;var d=$CLJS.DV(a,b),e=$CLJS.P_.j(a,b,d),f=$CLJS.y($CLJS.nf($CLJS.Ya,function v(t,u){try{if($CLJS.Ad(u)&&1<=$CLJS.D(u))try{var x=$CLJS.ok.j(u,0,1);if($CLJS.Ad(x)&&1===$CLJS.D(x))try{var A=$CLJS.F(x,0);if($CLJS.je(A,$CLJS.lF))return new $CLJS.Q(null,1,5,$CLJS.R,[u],null);throw $CLJS.Z;}catch(G){if(G instanceof Error){var C=G;if(C===$CLJS.Z)throw $CLJS.Z;throw C;}throw G;}else throw $CLJS.Z;}catch(G){if(G instanceof Error){C=G;if(C===$CLJS.Z)throw $CLJS.Z;
throw C;}throw G;}else throw $CLJS.Z;}catch(G){if(G instanceof Error){C=G;if(C===$CLJS.Z)return $CLJS.yU(v,t,u);throw C;}throw G;}}($CLJS.Ef,$CLJS.rK.h(c))));f=Hqa(e,f);var k=Nqa(Kqa(a,c,f),$CLJS.Fl($CLJS.XD,$CLJS.BM.h(d))),l=$CLJS.N_.h($CLJS.S0.g(a,$CLJS.oK.h(c)));return $CLJS.X2($CLJS.kk.j(c,$CLJS.rK,function(t){return $CLJS.jk.g(function(u){return Mqa(a,b,u,k,e,l)},t)}),k)};$CLJS.f3=function(a){return $CLJS.rK.h(a)};
$CLJS.g3=function(a){return $CLJS.zk.l($CLJS.H([new $CLJS.h(null,2,[$CLJS.Us,$CLJS.sK,$CLJS.ED,a],null),$CLJS.E.g(a,$CLJS.bE)?new $CLJS.h(null,1,[$CLJS.ei,!0],null):null]))};$CLJS.h3=function(a,b){b=$CLJS.z($CLJS.oK.h(b));return $CLJS.n($CLJS.MU.h(b))?$CLJS.$Z(a,$CLJS.MU.h(b)):$CLJS.n($CLJS.cO.h(b))?$CLJS.YZ(a,$CLJS.cO.h(b)):null};
k3=function(a){a=$CLJS.qG(function(d){return $CLJS.FZ(d)?i3:$CLJS.EZ(d)?j3:$CLJS.Qs},a);var b=$CLJS.O(a);a=$CLJS.J.g(b,i3);var c=$CLJS.J.g(b,j3);b=$CLJS.J.g(b,$CLJS.Qs);return $CLJS.jf.l(a,c,$CLJS.H([b]))};l3=function(a,b,c,d){return $CLJS.Wa(c)?d:$CLJS.jk.g(function(e){return $CLJS.n($CLJS.LY.h(e))?$CLJS.U2(e,$CLJS.c2(c)):e},$CLJS.V2(a,b,d,new $CLJS.Q(null,1,5,$CLJS.R,[c],null)))};
Oqa=function(a,b,c,d){var e=new $CLJS.Lh(function(){return $CLJS.P_.v(a,b,d,new $CLJS.h(null,2,[$CLJS.t_,!1,$CLJS.B_,!1],null))});return $CLJS.Ie($CLJS.gg.j($CLJS.Ef,$CLJS.zl(function(f){var k=$CLJS.O(f),l=$CLJS.J.g(k,$CLJS.UJ);return $CLJS.n(function(){var m=$CLJS.EZ(k);return m?l:m}())?(f=$CLJS.rG(function(m){return $CLJS.E.g(l,$CLJS.Si.h(m))},$CLJS.q(e)),$CLJS.n(f)?$CLJS.T.j(k,m3,f):null):null}),$CLJS.P_.j(a,b,c)))};Pqa={};
Qqa=new $CLJS.M("metabase.lib.join","join-fields","metabase.lib.join/join-fields",-2085751377);j3=new $CLJS.M(null,"fk","fk",398442651);i3=new $CLJS.M(null,"pk","pk",-771936732);Rqa=new $CLJS.r("metabase.lib.stage","ensure-previous-stages-have-metadata","metabase.lib.stage/ensure-previous-stages-have-metadata",2048342183,null);m3=new $CLJS.M("metabase.lib.join","target","metabase.lib.join/target",203858838);$CLJS.E_.m(null,$CLJS.jK,function(a,b,c){b=$CLJS.O(c);b=$CLJS.J.g(b,$CLJS.oK);b=$CLJS.I(b,0,null);b=$CLJS.O(b);c=$CLJS.J.g(b,$CLJS.cO);b=$CLJS.J.g(b,$CLJS.MU);c=$CLJS.n(c)?$CLJS.nD.h($CLJS.YZ(a,c)):null;if($CLJS.n(c))return c;$CLJS.n(b)?(c=$CLJS.$Z(a,b),a=$CLJS.n(c)?$CLJS.e_.j(a,0,c):$CLJS.d1(b)):a=null;return $CLJS.n(a)?a:$CLJS.LD("Native Query")});$CLJS.L_.m(null,$CLJS.jK,function(a,b,c){a=$CLJS.e_.j(a,b,c);c=$CLJS.XD.h(c);return new $CLJS.h(null,2,[$CLJS.U,$CLJS.n(c)?c:a,$CLJS.nD,a],null)});
$CLJS.K_.m(null,$CLJS.jK,function(){throw $CLJS.ji("You can't calculate a metadata map for a join! Use lib.metadata.calculation/returned-columns-method instead.",$CLJS.N);});
$CLJS.E_.m(null,$CLJS.sK,function(a,b,c){a=$CLJS.O(c);a=$CLJS.J.g(a,$CLJS.ED);a=a instanceof $CLJS.M?a.S:null;switch(a){case "left-join":return $CLJS.LD("Left outer join");case "right-join":return $CLJS.LD("Right outer join");case "inner-join":return $CLJS.LD("Inner join");case "full-join":return $CLJS.LD("Full outer join");default:throw Error(["No matching clause: ",$CLJS.p.h(a)].join(""));}});
$CLJS.L_.m(null,$CLJS.sK,function(a,b,c){var d=$CLJS.O(c),e=$CLJS.J.g(d,$CLJS.ED);c=$CLJS.J.g(d,$CLJS.ei);a=new $CLJS.h(null,2,[$CLJS.C_,$CLJS.Uz(e),$CLJS.nD,$CLJS.e_.j(a,b,d)],null);return $CLJS.n(c)?$CLJS.T.j(a,$CLJS.ei,!0):a});
$CLJS.M_.m(null,$CLJS.jK,function(a,b,c,d){var e=$CLJS.O(c),f=$CLJS.J.g(e,$CLJS.XD),k=$CLJS.J.j(e,$CLJS.TD,$CLJS.$y),l=$CLJS.J.g(e,$CLJS.oK);c=$CLJS.O(d);var m=$CLJS.J.g(c,$CLJS.z_);if($CLJS.E.g(k,$CLJS.$y))return null;var t="undefined"!==typeof $CLJS.dL&&"undefined"!==typeof Pqa&&"undefined"!==typeof $CLJS.Sqa&&"undefined"!==typeof $CLJS.n3?new $CLJS.Hc(function(){return $CLJS.n3},$CLJS.pd(Rqa,new $CLJS.h(null,1,[$CLJS.Cj,!0],null)),null):null,u=function(){var v=$CLJS.T.j(a,$CLJS.oK,l);return $CLJS.n(t)?
t.g?t.g(v,-1):t.call(null,v,-1):v}();c=$CLJS.E.g(k,$CLJS.rx)?$CLJS.N_.v(u,-1,$CLJS.rd(l),c):function(){return function A(x){return new $CLJS.pe(null,function(){for(;;){var C=$CLJS.y(x);if(C){if($CLJS.Bd(C)){var G=$CLJS.mc(C),K=$CLJS.D(G),S=$CLJS.se(K);a:for(var X=0;;)if(X<K){var ba=$CLJS.ld(G,X);ba=$CLJS.ID(ba,$CLJS.ak,$CLJS.H([$CLJS.rO]));ba=$CLJS.c_.j(u,-1,ba);S.add(ba);X+=1}else{G=!0;break a}return G?$CLJS.ve($CLJS.xe(S),A($CLJS.nc(C))):$CLJS.ve($CLJS.xe(S),null)}S=$CLJS.z(C);S=$CLJS.ID(S,$CLJS.ak,
$CLJS.H([$CLJS.rO]));return $CLJS.ge($CLJS.c_.j(u,-1,S),A($CLJS.Mc(C)))}return null}},null,null)}(k)}();return $CLJS.jk.g(function(v){v=$CLJS.T.j(v,$CLJS.YY,f);v=$CLJS.X2($CLJS.T.l(v,$CLJS.nD,$CLJS.e_.j(a,b,v),$CLJS.H([$CLJS.IJ,$CLJS.HY])),f);return $CLJS.b3(e,m,v)},c)});$CLJS.O_.m(null,$CLJS.jK,function(a,b,c,d){return $CLJS.N_.v(a,b,$CLJS.T.j(c,$CLJS.TD,$CLJS.rx),d)});
var o3,Tqa=$CLJS.Ze($CLJS.N),Uqa=$CLJS.Ze($CLJS.N),Vqa=$CLJS.Ze($CLJS.N),Wqa=$CLJS.Ze($CLJS.N),Xqa=$CLJS.J.j(new $CLJS.h(null,1,[$CLJS.Jk,$CLJS.bB],null),$CLJS.Jk,$CLJS.Xh.o?$CLJS.Xh.o():$CLJS.Xh.call(null));o3=new $CLJS.fi($CLJS.Hh.g("metabase.lib.join","join-clause-method"),$CLJS.SA,Xqa,Tqa,Uqa,Vqa,Wqa);o3.m(null,$CLJS.jK,function(a){return a});o3.m(null,$CLJS.fV,function(a){return $CLJS.nV(new $CLJS.h(null,2,[$CLJS.Us,$CLJS.jK,$CLJS.oK,$CLJS.oK.h($CLJS.BV(a))],null))});
o3.m(null,$CLJS.TU,function(a){return $CLJS.nV(new $CLJS.h(null,2,[$CLJS.Us,$CLJS.jK,$CLJS.oK,new $CLJS.Q(null,1,5,$CLJS.R,[a],null)],null))});o3.m(null,$CLJS.fK,function(a){return $CLJS.nV(new $CLJS.h(null,2,[$CLJS.Us,$CLJS.jK,$CLJS.oK,new $CLJS.Q(null,1,5,$CLJS.R,[new $CLJS.h(null,2,[$CLJS.MU,$CLJS.Si.h(a),$CLJS.Us,$CLJS.TU],null)],null)],null))});
o3.m(null,$CLJS.OJ,function(a){var b=$CLJS.O(a),c=$CLJS.J.g(b,$CLJS.$Y);a=$CLJS.J.g(b,Qqa);b=o3.h(new $CLJS.h(null,3,[$CLJS.Us,$CLJS.TU,$CLJS.oA,new $CLJS.h(null,1,[$CLJS.AD,$CLJS.p.h($CLJS.KD())],null),$CLJS.cO,$CLJS.Si.h(b)],null));c=$CLJS.n(c)?$CLJS.X2(b,c):b;return $CLJS.n(a)?$CLJS.d3.g?$CLJS.d3.g(c,a):$CLJS.d3.call(null,c,a):c});
$CLJS.p3=function(){function a(d,e){return $CLJS.c3(c.h?c.h(d):c.call(null,d),e)}function b(d){return $CLJS.j1(o3.h(d),$CLJS.TD,$CLJS.rx)}var c=null;c=function(d,e){switch(arguments.length){case 1:return b.call(this,d);case 2:return a.call(this,d,e)}throw Error("Invalid arity: "+arguments.length);};c.h=b;c.g=a;return c}();
$CLJS.Yqa=function(){function a(d,e,f){var k=$CLJS.p3.h(f);f=$CLJS.ud($CLJS.f3.h?$CLJS.f3.h(k):$CLJS.f3.call(null,k))?function(){var m=$CLJS.h3.g?$CLJS.h3.g(d,k):$CLJS.h3.call(null,d,k);return $CLJS.q3.j?$CLJS.q3.j(d,e,m):$CLJS.q3.call(null,d,e,m)}():null;f=$CLJS.y(f)?$CLJS.c3(k,f):k;var l=$CLJS.e3(d,e,f);return $CLJS.PV.l(d,e,$CLJS.kk,$CLJS.H([$CLJS.BM,function(m){return $CLJS.de.g($CLJS.Ff(m),l)}]))}function b(d,e){return c.j?c.j(d,-1,e):c.call(null,d,-1,e)}var c=null;c=function(d,e,f){switch(arguments.length){case 2:return b.call(this,
d,e);case 3:return a.call(this,d,e,f)}throw Error("Invalid arity: "+arguments.length);};c.g=b;c.j=a;return c}();$CLJS.r3=function(){function a(d,e){return $CLJS.Ie($CLJS.J.g($CLJS.DV(d,e),$CLJS.BM))}function b(d){return c.g?c.g(d,-1):c.call(null,d,-1)}var c=null;c=function(d,e){switch(arguments.length){case 1:return b.call(this,d);case 2:return a.call(this,d,e)}throw Error("Invalid arity: "+arguments.length);};c.h=b;c.g=a;return c}();
$CLJS.Zqa=function(){function a(d){d=$CLJS.P0(d);d=$CLJS.az.h(d);return $CLJS.gg.j($CLJS.Ef,$CLJS.hk.g($CLJS.mf($CLJS.Xe($CLJS.Jd,d)),$CLJS.kf.h($CLJS.g3)),new $CLJS.Q(null,4,5,$CLJS.R,[$CLJS.bE,$CLJS.SD,$CLJS.fE,$CLJS.iE],null))}function b(d){return c.g?c.g(d,-1):c.call(null,d,-1)}var c=null;c=function(d,e){switch(arguments.length){case 1:return b.call(this,d);case 2:return a.call(this,d,e)}throw Error("Invalid arity: "+arguments.length);};c.h=b;c.g=a;return c}();
$CLJS.$qa=function(){function a(d,e,f,k){var l=$CLJS.W2(f)?$CLJS.Z0(f):null,m=$CLJS.gg.j($CLJS.dh,$CLJS.hk.g($CLJS.kf.h($CLJS.Z0),Bqa(function(t){return $CLJS.gk.g(t,l)})),$CLJS.r3.g(d,e));f=$CLJS.n(k)?k:$CLJS.W2(f)?Z2($CLJS.z($CLJS.f3(f))):null;return k3(l3(d,e,f,$CLJS.ik.g(function(t){t=$CLJS.Z0(t);return $CLJS.n(t)?$CLJS.Jd(m,t):null},$CLJS.P_.v(d,e,$CLJS.DV(d,e),new $CLJS.h(null,1,[$CLJS.t_,!1],null)))))}function b(d,e,f,k){return c.M?c.M(d,-1,e,f,k):c.call(null,d,-1,e,f,k)}var c=null;c=function(d,
e,f,k,l){switch(arguments.length){case 4:return b.call(this,d,e,f,k);case 5:return a.call(this,d,e,f,k,l)}throw Error("Invalid arity: "+arguments.length);};c.v=b;c.M=a;return c}();
$CLJS.ara=function(){function a(d,e,f,k,l){k=$CLJS.W2(f)?$CLJS.h3(d,f):f;var m=$CLJS.W2(f)?$CLJS.Z0(f):null;f=$CLJS.n(l)?l:$CLJS.W2(f)?$2($CLJS.z($CLJS.f3(f))):null;f=$CLJS.n(f)?$CLJS.Wa(m)?$CLJS.ID(f,$CLJS.ak,$CLJS.H([$CLJS.rO])):f:null;return k3(l3(d,e,f,$CLJS.kf.g(function(t){t=$CLJS.T.j(t,$CLJS.IJ,$CLJS.HY);return $CLJS.n(m)?$CLJS.X2(t,m):t},$CLJS.P_.v(d,e,k,new $CLJS.h(null,1,[$CLJS.t_,!1],null)))))}function b(d,e,f,k){return c.M?c.M(d,-1,e,f,k):c.call(null,d,-1,e,f,k)}var c=null;c=function(d,
e,f,k,l){switch(arguments.length){case 4:return b.call(this,d,e,f,k);case 5:return a.call(this,d,e,f,k,l)}throw Error("Invalid arity: "+arguments.length);};c.v=b;c.M=a;return c}();$CLJS.bra=function(){function a(c,d,e){return b.v?b.v(c,-1,d,e):b.call(null,c,-1,d,e)}var b=null;b=function(c,d,e,f){switch(arguments.length){case 3:return a.call(this,c,d,e);case 4:return $CLJS.N1}throw Error("Invalid arity: "+arguments.length);};b.j=a;b.v=function(){return $CLJS.N1};return b}();
$CLJS.q3=function(){function a(d,e,f){function k(u,v){u=$CLJS.ak.g(u,$CLJS.f1);v=$CLJS.ak.g(v,$CLJS.f1);return $CLJS.S2.l($CLJS.L1.h($CLJS.Nj),u,$CLJS.H([v]))}function l(u,v){return $CLJS.Ie(Cqa(function(x){return $CLJS.Si.h(m3.h(x))},Oqa(d,e,u,v)))}var m=$CLJS.DV(d,e),t=function(){var u=l(m,f);return $CLJS.n(u)?$CLJS.jk.g(function(v){return k(v,m3.h(v))},u):null}();if($CLJS.n(t))return t;t=l(f,m);return $CLJS.n(t)?$CLJS.jk.g(function(u){return k(m3.h(u),u)},t):null}function b(d,e){return c.j?c.j(d,
-1,e):c.call(null,d,-1,e)}var c=null;c=function(d,e,f){switch(arguments.length){case 2:return b.call(this,d,e);case 3:return a.call(this,d,e,f)}throw Error("Invalid arity: "+arguments.length);};c.g=b;c.j=a;return c}();
$CLJS.cra=function(){function a(e,f,k,l){l=$CLJS.n(l)?l:$CLJS.W2(k)?Z2($CLJS.z($CLJS.f3(k))):null;$CLJS.n(l)?(l=$CLJS.h_.j(e,f,l),l=$CLJS.wz(l,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.MV,$CLJS.nD],null))):l=null;if($CLJS.n(l))return l;if(l=0===$CLJS.CV(e,f)){l=$CLJS.r3.g(e,f);var m=$CLJS.ud(l);k=m?m:$CLJS.W2(k)?$CLJS.E.g($CLJS.XD.h(k),$CLJS.XD.h($CLJS.z(l))):null;k=$CLJS.n(k)?$CLJS.SZ(e):k}else k=l;$CLJS.n(k)?(k=$CLJS.SZ(e),k=$CLJS.YZ(e,k),e=$CLJS.e_.j(e,f,k)):e=null;return $CLJS.n(e)?e:$CLJS.LD("Previous results")}
function b(e,f,k){return d.v?d.v(e,-1,f,k):d.call(null,e,-1,f,k)}function c(e,f){return d.j?d.j(e,f,null):d.call(null,e,f,null)}var d=null;d=function(e,f,k,l){switch(arguments.length){case 2:return c.call(this,e,f);case 3:return b.call(this,e,f,k);case 4:return a.call(this,e,f,k,l)}throw Error("Invalid arity: "+arguments.length);};d.g=c;d.j=b;d.v=a;return d}();
$CLJS.dra=function(){function a(d,e,f,k){f=$CLJS.pV.h(f);$CLJS.I(f,0,null);$CLJS.I(f,1,null);var l=$CLJS.I(f,2,null),m=$CLJS.I(f,3,null);k=k instanceof $CLJS.M?k:$CLJS.Ek.h(k);e=$CLJS.CV(d,e);l=$CLJS.n0.j(d,e,l);d=$CLJS.n0.j(d,e,m);m=null==k||$CLJS.Jd($CLJS.hh($CLJS.kf.g($CLJS.Ek,l)),k);d=null==k||$CLJS.Jd($CLJS.hh($CLJS.kf.g($CLJS.Ek,d)),k);f=m?$CLJS.kk.v(f,2,$CLJS.U2,k):f;return d?$CLJS.kk.v(f,3,$CLJS.U2,k):f}function b(d,e,f){return c.v?c.v(d,-1,e,f):c.call(null,d,-1,e,f)}var c=null;c=function(d,
e,f,k){switch(arguments.length){case 3:return b.call(this,d,e,f);case 4:return a.call(this,d,e,f,k)}throw Error("Invalid arity: "+arguments.length);};c.j=b;c.v=a;return c}();$CLJS.H_.m(null,$CLJS.BM,function(a,b){var c=$CLJS.Ie($CLJS.r3.g(a,b));c=null==c?null:$CLJS.kf.g(function(d){return $CLJS.e_.j(a,b,d)},c);return null==c?null:$CLJS.gs(" + ",c)});