var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./metabase.lib.schema.common.js");require("./metabase.lib.schema.expression.js");require("./metabase.shared.util.i18n.js");require("./metabase.util.malli.registry.js");
'use strict';var iK,Uia,lK,nK,Via,pK,qK;iK=new $CLJS.M("metabase.lib.schema.join","join","metabase.lib.schema.join/join",1110197236);$CLJS.jK=new $CLJS.M("mbql","join","mbql/join",-709512370);Uia=new $CLJS.M("gen","fmap","gen/fmap",-1585733563);$CLJS.kK=new $CLJS.M("metabase.lib.schema","stages","metabase.lib.schema/stages",-391672350);lK=new $CLJS.M("metabase.lib.schema.join","conditions","metabase.lib.schema.join/conditions",118173612);
$CLJS.mK=new $CLJS.M("metabase.lib.schema.join","joins","metabase.lib.schema.join/joins",106891649);nK=new $CLJS.M("metabase.lib.schema.join","alias","metabase.lib.schema.join/alias",53862412);$CLJS.oK=new $CLJS.M(null,"stages","stages",-442109532);Via=new $CLJS.M("metabase.lib.schema.join","strategy.option","metabase.lib.schema.join/strategy.option",473280855);pK=new $CLJS.M("metabase.lib.schema.join","fields","metabase.lib.schema.join/fields",391974200);
qK=new $CLJS.M("metabase.lib.schema.join","strategy","metabase.lib.schema.join/strategy",1569892832);$CLJS.rK=new $CLJS.M(null,"conditions","conditions",-1647236270);$CLJS.sK=new $CLJS.M("option","join.strategy","option/join.strategy",1337097154);$CLJS.Y(pK,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.fr,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.cr,$CLJS.rx,$CLJS.$y],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.kj,new $CLJS.h(null,1,[$CLJS.ln,1],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.aE],null)],null)],null));$CLJS.Y(nK,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.fr,new $CLJS.h(null,1,[Uia,function(a){return[$CLJS.p.h(a),"-",$CLJS.p.h($CLJS.KD())].join("")}],null),$CLJS.sD],null));
$CLJS.Y(lK,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.kj,new $CLJS.h(null,1,[$CLJS.ln,1],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.YD],null)],null));$CLJS.Y(qK,new $CLJS.Q(null,5,5,$CLJS.R,[$CLJS.cr,$CLJS.bE,$CLJS.SD,$CLJS.fE,$CLJS.iE],null));
$CLJS.Y(iK,new $CLJS.Q(null,8,5,$CLJS.R,[$CLJS.Gj,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Us,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Nj,$CLJS.jK],null)],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.oA,$CLJS.yD],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.oK,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.kK],null)],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.rK,lK],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.XD,nK],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.TD,new $CLJS.h(null,1,[$CLJS.Ar,!0],null),pK],null),new $CLJS.Q(null,
3,5,$CLJS.R,[$CLJS.ED,new $CLJS.h(null,1,[$CLJS.Ar,!0],null),qK],null)],null));
$CLJS.Y($CLJS.mK,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.mr,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.kj,new $CLJS.h(null,1,[$CLJS.ln,1],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,iK],null)],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Mi,new $CLJS.h(null,1,[$CLJS.Ds,function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.w(e,0,null)}return b.call(this,d)}function b(){return $CLJS.LD("Join aliases must be unique at a given stage of a query")}
a.A=0;a.B=function(c){c=$CLJS.y(c);return b(c)};a.l=b;return a}()],null),function(a){a=$CLJS.Ie($CLJS.nf($CLJS.Ya,$CLJS.kf.g($CLJS.XD,a)));return $CLJS.n(a)?$CLJS.P.g($CLJS.tB,a):!0}],null)],null));
$CLJS.Y(Via,new $CLJS.Q(null,4,5,$CLJS.R,[$CLJS.Gj,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Us,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Nj,$CLJS.sK],null)],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.ED,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,qK],null)],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.ei,new $CLJS.h(null,1,[$CLJS.Ar,!0],null),$CLJS.vr],null)],null));