var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./metabase.shared.formatting.constants.js");require("./metabase.shared.formatting.internal.date_builder.js");require("./metabase.shared.formatting.internal.date_formatters.js");require("./metabase.shared.formatting.internal.date_options.js");require("./metabase.shared.util.time.js");
'use strict';var P$,vya,wya,xya,yya,Q$,zya,Aya,Bya,S$,Cya,Dya;P$=function(a){a=$CLJS.O(a);a=$CLJS.J.g(a,$CLJS.p$);return $CLJS.E.g(a,"compact")};
vya=function(a,b){return $CLJS.n(b)?function e(d){return new $CLJS.pe(null,function(){for(;;){var f=$CLJS.y(d);if(f){if($CLJS.Bd(f)){var k=$CLJS.mc(f),l=$CLJS.D(k),m=$CLJS.se(l);a:for(var t=0;;)if(t<l){var u=$CLJS.ld(k,t);u="string"===typeof u?$CLJS.Az(u,/\//,b):u;m.add(u);t+=1}else{k=!0;break a}return k?$CLJS.ve($CLJS.xe(m),e($CLJS.nc(f))):$CLJS.ve($CLJS.xe(m),null)}m=$CLJS.z(f);return $CLJS.ge("string"===typeof m?$CLJS.Az(m,/\//,b):m,e($CLJS.Mc(f)))}return null}},null,null)}(a):a};
wya=function(a){return function d(c){return new $CLJS.pe(null,function(){for(;;){var e=$CLJS.y(c);if(e){if($CLJS.Bd(e)){var f=$CLJS.mc(e),k=$CLJS.D(f),l=$CLJS.se(k);return function(){for(var t=0;;)if(t<k){var u=$CLJS.ld(f,t),v=l,x=u;u=$CLJS.E.g($CLJS.Y9,x)?$CLJS.$9:$CLJS.E.g(":month-full",x)?$CLJS.$9:$CLJS.E.g($CLJS.l$,x)?$CLJS.h$:$CLJS.E.g(":day-of-week-full",x)?$CLJS.h$:u;v.add(u);t+=1}else return!0}()?$CLJS.ve($CLJS.xe(l),d($CLJS.nc(e))):$CLJS.ve($CLJS.xe(l),null)}var m=$CLJS.z(e);return $CLJS.ge(function(){var t=
m;return $CLJS.E.g($CLJS.Y9,t)?$CLJS.$9:$CLJS.E.g(":month-full",t)?$CLJS.$9:$CLJS.E.g($CLJS.l$,t)?$CLJS.h$:$CLJS.E.g(":day-of-week-full",t)?$CLJS.h$:m}(),d($CLJS.Mc(e)))}return null}},null,null)}(a)};
xya=function(a){var b=$CLJS.O(a),c=$CLJS.J.g(b,$CLJS.n$);a=$CLJS.J.g(b,$CLJS.Ly);b=$CLJS.J.g(b,$CLJS.Ek);if($CLJS.n(c))return c;c=$CLJS.wz($CLJS.A$,new $CLJS.Q(null,2,5,$CLJS.R,[a,b],null));if($CLJS.n(c))return c;c=$CLJS.J.g($CLJS.pya,b);if($CLJS.n(c))return c;c=$CLJS.J.g($CLJS.q$,a);if($CLJS.n(c))return c;c=$CLJS.Gz($CLJS.zx);$CLJS.n($CLJS.Fz("metabase.shared.formatting.internal.date-formatters",c))&&$CLJS.Ez("metabase.shared.formatting.internal.date-formatters",c,$CLJS.vv.l($CLJS.H(["Unrecognized date style",
new $CLJS.h(null,2,[$CLJS.Ly,a,$CLJS.Ek,b],null)])),null);return $CLJS.D$};yya=function(a){a=$CLJS.O(a);var b=$CLJS.J.g(a,$CLJS.oya),c=$CLJS.J.g(a,$CLJS.My);var d=$CLJS.O(a);var e=$CLJS.J.g(d,$CLJS.n$);d=$CLJS.zk.l($CLJS.H([d,$CLJS.J.g($CLJS.s$,e)]));d=xya(d);b=$CLJS.n(b)?vya(d,b):d;c=$CLJS.n(c)?$CLJS.jf.g(new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.h$,", "],null),b):b;return P$(a)?wya(c):c};Q$=function(a){a=$CLJS.O(a);var b=$CLJS.J.g(a,$CLJS.aj);return P$(a)&&$CLJS.gk.g(b,"tooltip")};
zya=function(a){var b=$CLJS.O(a);a=$CLJS.J.g(b,$CLJS.Ny);var c=$CLJS.J.g(b,$CLJS.o$),d=$CLJS.J.g(b,$CLJS.Oy);a:{var e="string"===typeof c;if(e){e=$CLJS.J.g($CLJS.r$,c);if($CLJS.n(e)){b=e;break a}throw $CLJS.ji("Unknown time format",b);}b=e}if($CLJS.n(b))return b;if($CLJS.n(c))return c;c=$CLJS.wz($CLJS.sya,new $CLJS.Q(null,2,5,$CLJS.R,[d,a],null));if($CLJS.n(c))return c;c=$CLJS.J.g($CLJS.r$,d);if($CLJS.n(c))return c;c=$CLJS.Gz($CLJS.zx);$CLJS.n($CLJS.Fz("metabase.shared.formatting.internal.date-formatters",
c))&&$CLJS.Ez("metabase.shared.formatting.internal.date-formatters",c,$CLJS.vv.l($CLJS.H(["Unrecognized time style",new $CLJS.h(null,2,[$CLJS.Oy,d,$CLJS.Ny,a],null)])),null);return $CLJS.tya};
Aya=function(a){var b=$CLJS.O(a);a=$CLJS.J.g(b,$CLJS.Py);var c=$CLJS.J.g(b,$CLJS.Ny),d=$CLJS.n(a)?yya(b):null,e=$CLJS.n(c)?zya(b):null;a=$CLJS.n($CLJS.n(d)?e:d)?$CLJS.jf.l(d,new $CLJS.Q(null,1,5,$CLJS.R,[", "],null),$CLJS.H([e])):function(){if($CLJS.n(d))return d;if($CLJS.n(e))return e;var f=$CLJS.Gz($CLJS.zx);$CLJS.n($CLJS.Fz("metabase.shared.formatting.internal.date-formatters",f))&&$CLJS.Ez("metabase.shared.formatting.internal.date-formatters",f,$CLJS.vv.l($CLJS.H(["Unrecognized date/time format",
b])),null);return $CLJS.D$}();return $CLJS.y$(a)};Bya=function(a){var b=$CLJS.J.g($CLJS.q($CLJS.K$),a);return $CLJS.n(b)?b:$CLJS.J.g($CLJS.Qh.g($CLJS.K$,function(c){return $CLJS.Jd(c,a)?c:$CLJS.T.j(c,a,Aya(a))}),a)};
$CLJS.R$=function(a){a=$CLJS.kk.j($CLJS.$z(a),$CLJS.Ek,$CLJS.Bh);var b=$CLJS.zk.l;var c=$CLJS.Ek.h(a);c=$CLJS.M$.h?$CLJS.M$.h(c):$CLJS.M$.call(null,c);a=b.call($CLJS.zk,$CLJS.H([$CLJS.uya,$CLJS.n(c)?new $CLJS.h(null,1,[$CLJS.Ny,"minutes"],null):null,a]));var d=$CLJS.O(a);b=$CLJS.J.g(d,$CLJS.uA);c=$CLJS.J.g(d,$CLJS.L$);var e=$CLJS.J.g(d,$CLJS.aj);a=$CLJS.J.g(d,$CLJS.Ek);d=$CLJS.ak.l(d,$CLJS.uA,$CLJS.H([$CLJS.L$]));d=$CLJS.n($CLJS.O$.h?$CLJS.O$.h(a):$CLJS.O$.call(null,a))?$CLJS.T.j(d,$CLJS.Py,!1):d;
e=$CLJS.E.g(e,"tooltip")?$CLJS.T.j(d,$CLJS.p$,"condensed"):d;b=$CLJS.n($CLJS.n(b)?b:c)?$CLJS.T.j(e,$CLJS.p$,"compact"):e;return $CLJS.Wa($CLJS.N$.h?$CLJS.N$.h(a):$CLJS.N$.call(null,a))?$CLJS.ak.g(b,$CLJS.My):b};
S$=function(a,b){b=$CLJS.R$(b);var c=$CLJS.h0.g(a,b);if($CLJS.n($CLJS.f0.l($CLJS.H([c])))){c=$CLJS.e0.l($CLJS.H([c,b]));a=$CLJS.I(c,0,null);c=$CLJS.I(c,1,null);var d=$CLJS.O(b);d=$CLJS.J.g(d,$CLJS.p$);var e=new $CLJS.ch(null,new $CLJS.h(null,2,["compact",null,"condensed",null],null),null);d=e.h?e.h(d):e.call(null,d);$CLJS.Wa(d)||$CLJS.Wa($CLJS.Soa.l($CLJS.H([a,c])))?(b=Q$(b)?$CLJS.G$:$CLJS.H$,b=[$CLJS.p.h(b(a))," – ",$CLJS.p.h(b(c))].join("")):b=$CLJS.Wa($CLJS.Roa.l($CLJS.H([a,c])))?[$CLJS.p.h((Q$(b)?
$CLJS.E$:$CLJS.F$)(a))," – ",$CLJS.p.h((Q$(b)?$CLJS.G$:$CLJS.H$)(c))].join(""):[$CLJS.p.h((Q$(b)?$CLJS.E$:$CLJS.F$)(a))," – ",$CLJS.p.h($CLJS.y$(new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Z9,", ",$CLJS.li],null))(c))].join("")}else b=$CLJS.p.h(a);return b};
$CLJS.T$=function(a,b){b=$CLJS.R$(b);var c=$CLJS.O(b),d=$CLJS.J.g(c,Cya),e=$CLJS.J.g(c,Dya),f=$CLJS.J.g(c,$CLJS.aj),k=$CLJS.J.g(c,$CLJS.Ek);b=$CLJS.h0.g(a,c);if($CLJS.n(d))switch(k instanceof $CLJS.M?k.S:null){case "hour-of-day":return(0,$CLJS.qya)(b);case "day-of-week":return(0,$CLJS.rya)(b);default:throw $CLJS.ji("is-exclude option is only compatible with hour-of-day and day-of-week units",new $CLJS.h(null,1,[$CLJS.Yi,c],null));}else{(d=$CLJS.E.g(k,$CLJS.cj))?(d=new $CLJS.ch(null,new $CLJS.h(null,
2,["tooltip",null,"cell",null],null),null),f=d.h?d.h(f):d.call(null,f),e=$CLJS.n(f)?$CLJS.Wa(e):f):e=d;if($CLJS.n(e))return S$(a,c);a=Bya(c);return a.h?a.h(b):a.call(null,b)}};Cya=new $CLJS.M(null,"is-exclude","is-exclude",1738462979);Dya=new $CLJS.M(null,"no-range","no-range",-1511420040);var U$=new $CLJS.h(null,3,[$CLJS.ij,$CLJS.y$(new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.li,"-",$CLJS.d$],null)),$CLJS.qi,$CLJS.y$(new $CLJS.Q(null,4,5,$CLJS.R,["Q",$CLJS.qi,"-",$CLJS.li],null)),$CLJS.Qk,$CLJS.I$],null);
module.exports={format_for_parameter:function(a,b){b=$CLJS.R$(b);var c=$CLJS.h0.g(a,b);if($CLJS.Wa($CLJS.f0.l($CLJS.H([c]))))return $CLJS.p.h(a);a=$CLJS.Ek.h(b);a=U$.h?U$.h(a):U$.call(null,a);if($CLJS.n(a))return a.h?a.h(c):a.call(null,c);c=$CLJS.e0.l($CLJS.H([c,b]));b=$CLJS.I(c,0,null);c=$CLJS.I(c,1,null);return $CLJS.n($CLJS.Qoa.l($CLJS.H([b,c])))?(0,$CLJS.I$)(b):[$CLJS.p.h((0,$CLJS.I$)(b)),"~",$CLJS.p.h((0,$CLJS.I$)(c))].join("")},format_range_with_unit:S$,format_datetime_with_unit:$CLJS.T$};