var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./malli.core.js");require("./medley.core.js");require("./metabase.lib.convert.js");require("./metabase.lib.dispatch.js");require("./metabase.lib.expression.js");require("./metabase.lib.hierarchy.js");require("./metabase.lib.metadata.js");require("./metabase.lib.metadata.calculation.js");require("./metabase.lib.normalize.js");require("./metabase.lib.schema.js");require("./metabase.lib.schema.common.js");require("./metabase.lib.schema.id.js");require("./metabase.lib.util.js");require("./metabase.mbql.util.js");require("./metabase.util.js");require("./metabase.util.malli.js");
'use strict';var N0,O0;$CLJS.K0=function(a,b){return $CLJS.D(a)<=$CLJS.D(b)&&$CLJS.Te(function(c){return $CLJS.Jd(b,c)},a)};$CLJS.L0=function(a,b){return $CLJS.Dz($CLJS.Ve(a),b)};$CLJS.M0=function(a){var b;a:for(b=a;;)if($CLJS.yd(b))b=$CLJS.Si.h(b);else{b=$CLJS.Gd(b)?b:null;break a}if($CLJS.n(b))return b;throw Error($CLJS.iD("Not something with an ID: {0}",$CLJS.H([$CLJS.Oh.l($CLJS.H([a]))])));};
N0=function(a){if(null!=a&&null!=a.rg)a=a.rg(a);else{var b=N0[$CLJS.xa(null==a?null:a)];if(null!=b)a=b.h?b.h(a):b.call(null,a);else if(b=N0._,null!=b)a=b.h?b.h(a):b.call(null,a);else throw $CLJS.cb("MetadataProvider.database",a);}return a};O0=function(a,b){if(null!=a&&null!=a.sg)a=a.sg(a,b);else{var c=O0[$CLJS.xa(null==a?null:a)];if(null!=c)a=c.g?c.g(a,b):c.call(null,a,b);else if(c=O0._,null!=c)a=c.g?c.g(a,b):c.call(null,a,b);else throw $CLJS.cb("MetadataProvider.field",a);}return a};$CLJS.P0=function(a){return N0($CLJS.XZ(a))};
$CLJS.Q0=function(a,b){return O0($CLJS.XZ(a),b)};$CLJS.H0.m(null,$CLJS.fV,function(a){return $CLJS.G0(a,new $CLJS.h(null,2,[$CLJS.aj,$CLJS.Bh,$CLJS.oK,$CLJS.Xe($CLJS.jk,$CLJS.H0)],null))});$CLJS.K_.m(null,$CLJS.fV,function(){throw $CLJS.ji("You can't calculate a metadata map for a query! Use lib.metadata.calculation/returned-columns-method instead.",$CLJS.N);});$CLJS.M_.m(null,$CLJS.fV,function(a,b,c,d){return $CLJS.N_.v(a,b,$CLJS.DV(c,b),d)});$CLJS.E_.m(null,$CLJS.fV,function(a,b,c,d){return $CLJS.e_.v(a,b,$CLJS.DV(c,b),d)});
$CLJS.R0=function(){var a=$CLJS.Ze($CLJS.N),b=$CLJS.Ze($CLJS.N),c=$CLJS.Ze($CLJS.N),d=$CLJS.Ze($CLJS.N),e=$CLJS.J.j($CLJS.N,$CLJS.Jk,$CLJS.Xh.o?$CLJS.Xh.o():$CLJS.Xh.call(null));return new $CLJS.fi($CLJS.Hh.g("metabase.lib.query","can-run-method"),function(f){return $CLJS.Us.h($CLJS.DV(f,0))},e,a,b,c,d)}();$CLJS.R0.m(null,$CLJS.ei,function(){return!0});
$CLJS.S0=function(){function a(d,e,f){return new $CLJS.h(null,4,[$CLJS.Us,$CLJS.fV,$CLJS.jD,$CLJS.XZ(e),$CLJS.SO,d,$CLJS.oK,f],null)}function b(d,e){var f=$CLJS.Si.h($CLJS.P0(d));return c.j?c.j(f,d,e):c.call(null,f,d,e)}var c=null;c=function(d,e,f){switch(arguments.length){case 2:return b.call(this,d,e);case 3:return a.call(this,d,e,f)}throw Error("Invalid arity: "+arguments.length);};c.g=b;c.j=a;return c}();
$CLJS.T0=function(){var a=$CLJS.Ze($CLJS.N),b=$CLJS.Ze($CLJS.N),c=$CLJS.Ze($CLJS.N),d=$CLJS.Ze($CLJS.N),e=$CLJS.J.j(new $CLJS.h(null,1,[$CLJS.Jk,$CLJS.bB],null),$CLJS.Jk,$CLJS.Xh.o?$CLJS.Xh.o():$CLJS.Xh.call(null));return new $CLJS.fi($CLJS.Hh.g("metabase.lib.query","query-method"),function(f,k){return $CLJS.SA(k)},e,a,b,c,d)}();$CLJS.T0.m(null,$CLJS.jA,function(a,b){b=$CLJS.XX.h(b);return $CLJS.S0.g(a,$CLJS.oK.h(b))});
$CLJS.T0.m(null,$CLJS.fV,function(a,b){var c=$CLJS.O(b);b=$CLJS.J.g(c,$CLJS.TX);var d=$CLJS.XZ(a),e=$CLJS.ak.g($CLJS.T.j(c,$CLJS.jD,d),$CLJS.TX);a=$CLJS.oK.h(e);return $CLJS.n(b)?$CLJS.T.j(e,$CLJS.oK,$CLJS.gg.j($CLJS.Ef,$CLJS.kf.h(function(f){var k=$CLJS.I(f,0,null);f=$CLJS.I(f,1,null);return function u(m,t){try{if($CLJS.Ad(t)&&3===$CLJS.D(t))try{var v=$CLJS.F(t,0);if($CLJS.je(v,$CLJS.lF))try{var x=$CLJS.F(t,1);if($CLJS.n($CLJS.Ve($CLJS.uz($CLJS.nA,$CLJS.Ci))(x)))try{var A=$CLJS.F(t,2);if($CLJS.n($CLJS.gD($CLJS.dl,
$CLJS.wl)(A))){var C=$CLJS.F(t,2),G=$CLJS.F(t,1),K=$CLJS.Hl($CLJS.Q0(d,C),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.nA,$CLJS.Ci],null));return new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.lF,$CLJS.zk.l($CLJS.H([K,G])),C],null)}throw $CLJS.Z;}catch(ha){if(ha instanceof Error){var S=ha;if(S===$CLJS.Z)throw $CLJS.Z;throw S;}throw ha;}else throw $CLJS.Z;}catch(ha){if(ha instanceof Error){S=ha;if(S===$CLJS.Z)throw $CLJS.Z;throw S;}throw ha;}else throw $CLJS.Z;}catch(ha){if(ha instanceof Error)if(S=ha,S===$CLJS.Z)try{if(v=
$CLJS.F(t,0),$CLJS.je(v,$CLJS.kA))try{x=$CLJS.F(t,1);if($CLJS.n($CLJS.Ve($CLJS.uz($CLJS.nA,$CLJS.Ci))(x))){G=$CLJS.F(t,1);var X=$CLJS.F(t,2);K=function(){try{return $CLJS.L0(function(ua){return $CLJS.E.g($CLJS.lj,ua)},$CLJS.Hl($CLJS.id($CLJS.opa.j(e,k,X)),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.nA,$CLJS.Ci],null)))}catch(ua){return null}}();return new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.kA,$CLJS.zk.l($CLJS.H([K,G])),X],null)}throw $CLJS.Z;}catch(ua){if(ua instanceof Error){var ba=ua;if(ba===$CLJS.Z)throw $CLJS.Z;
throw ba;}throw ua;}else throw $CLJS.Z;}catch(ua){if(ua instanceof Error){ba=ua;if(ba===$CLJS.Z)throw $CLJS.Z;throw ba;}throw ua;}else throw S;else throw ha;}else throw $CLJS.Z;}catch(ha){if(ha instanceof Error){S=ha;if(S===$CLJS.Z)return $CLJS.YV(u,m,t);throw S;}throw ha;}}($CLJS.Ef,f)}),$CLJS.Gl($CLJS.zr,a))):e});$CLJS.T0.m(null,$CLJS.OJ,function(a,b){return $CLJS.S0.g(a,new $CLJS.Q(null,1,5,$CLJS.R,[new $CLJS.h(null,2,[$CLJS.Us,$CLJS.TU,$CLJS.cO,$CLJS.M0(b)],null)],null))});
$CLJS.T0.m(null,$CLJS.fK,function(a,b){return $CLJS.S0.g(a,new $CLJS.Q(null,1,5,$CLJS.R,[new $CLJS.h(null,2,[$CLJS.Us,$CLJS.TU,$CLJS.MU,$CLJS.M0(b)],null)],null))});