var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./clojure.string.js");require("./clojure.walk.js");require("./medley.core.js");require("./metabase.lib.cache.js");require("./metabase.lib.convert.js");require("./metabase.lib.core.js");require("./metabase.lib.equality.js");require("./metabase.lib.field.js");require("./metabase.lib.join.js");require("./metabase.lib.js.metadata.js");require("./metabase.lib.metadata.js");require("./metabase.lib.metadata.calculation.js");require("./metabase.lib.metadata.protocols.js");require("./metabase.lib.order_by.js");require("./metabase.lib.stage.js");require("./metabase.lib.util.js");require("./metabase.mbql.js.js");require("./metabase.mbql.normalize.js");require("./metabase.shared.util.time.js");require("./metabase.util.js");require("./metabase.util.log.js");require("./metabase.util.memoize.js");
'use strict';var cya=function(a,b){const c={};for(const d in a)b.call(void 0,a[d],d,a)&&(c[d]=a[d]);return c},dya=function(a,b){const c={};for(const d in a)c[d]=b.call(void 0,a[d],d,a);return c},w9=function(a){var b=$CLJS.O(a);a=$CLJS.J.g(b,$CLJS.nA);b=$CLJS.J.g(b,$CLJS.Ci);a=$CLJS.n(b)?b:a;return $CLJS.nB(a,$CLJS.Dj)||$CLJS.nB(a,$CLJS.dj)},eya=function(a,b,c,d){var e=$CLJS.gg.j($CLJS.N,$CLJS.Kl(function(f,k){return new $CLJS.Q(null,2,5,$CLJS.R,[k,f],null)}),d);return function l(k){return new $CLJS.pe(null,
function(){for(;;){var m=$CLJS.y(k);if(m){if($CLJS.Bd(m)){var t=$CLJS.mc(m),u=$CLJS.D(t),v=$CLJS.se(u);a:for(var x=0;;)if(x<u){var A=$CLJS.ld(t,x);A=$CLJS.x1.v(a,b,A,d);A=$CLJS.J.j(e,A,-1);v.add(A);x+=1}else{t=!0;break a}return t?$CLJS.ve($CLJS.xe(v),l($CLJS.nc(m))):$CLJS.ve($CLJS.xe(v),null)}v=$CLJS.z(m);v=$CLJS.x1.v(a,b,v,d);return $CLJS.ge($CLJS.J.j(e,v,-1),l($CLJS.Mc(m)))}return null}},null,null)}(c)},x9=function(a,b){return new $CLJS.Lh(function(){try{return $CLJS.s9.g(a,b)}catch(e){if(e instanceof
Error){var c=e,d=$CLJS.Gz($CLJS.xx);$CLJS.n($CLJS.Fz("metabase.lib.js.metadata",d))&&(c instanceof Error?$CLJS.Ez("metabase.lib.js.metadata",d,$CLJS.sV("Error parsing %s objects: %s",$CLJS.H([a,$CLJS.qU(c)])),c):$CLJS.Ez("metabase.lib.js.metadata",d,$CLJS.sV(c,$CLJS.H(["Error parsing %s objects: %s",a,$CLJS.qU(c)])),null));return null}throw e;}})},fya=function(a,b){return function e(d){return new $CLJS.pe(null,function(){for(var f=d;;)if(f=$CLJS.y(f)){if($CLJS.Bd(f)){var k=$CLJS.mc(f),l=$CLJS.D(k),
m=$CLJS.se(l);return function(){for(var x=0;;)if(x<l){var A=$CLJS.ld(k,x);$CLJS.I(A,0,null);var C=$CLJS.I(A,1,null),G=function(){var K=C;return null==K?null:$CLJS.q(K)}();$CLJS.n(function(){var K=G;return $CLJS.n(K)?$CLJS.E.g($CLJS.XJ.h(G),b):K}())&&m.add(G);x+=1}else return!0}()?$CLJS.ve($CLJS.xe(m),e($CLJS.nc(f))):$CLJS.ve($CLJS.xe(m),null)}var t=$CLJS.z(f);$CLJS.I(t,0,null);var u=$CLJS.I(t,1,null),v=function(){var x=u;return null==x?null:$CLJS.q(x)}();if($CLJS.n(function(){var x=v;return $CLJS.n(x)?
$CLJS.E.g($CLJS.XJ.h(v),b):x}()))return $CLJS.ge(v,e($CLJS.Mc(f)));f=$CLJS.Mc(f)}else return null},null,null)}(function(){var d=null==a?null:$CLJS.TD.h(a);return null==d?null:$CLJS.q(d)}())},gya=function(a,b){return function e(d){return new $CLJS.pe(null,function(){for(var f=d;;)if(f=$CLJS.y(f)){if($CLJS.Bd(f)){var k=$CLJS.mc(f),l=$CLJS.D(k),m=$CLJS.se(l);return function(){for(var x=0;;)if(x<l){var A=$CLJS.ld(k,x);$CLJS.I(A,0,null);var C=$CLJS.I(A,1,null),G=function(){var K=C;return null==K?null:
$CLJS.q(K)}();$CLJS.n(function(){var K=G;return $CLJS.n(K)?$CLJS.E.g($CLJS.XJ.h(G),b):K}())&&m.add(G);x+=1}else return!0}()?$CLJS.ve($CLJS.xe(m),e($CLJS.nc(f))):$CLJS.ve($CLJS.xe(m),null)}var t=$CLJS.z(f);$CLJS.I(t,0,null);var u=$CLJS.I(t,1,null),v=function(){var x=u;return null==x?null:$CLJS.q(x)}();if($CLJS.n(function(){var x=v;return $CLJS.n(x)?$CLJS.E.g($CLJS.XJ.h(v),b):x}()))return $CLJS.ge(v,e($CLJS.Mc(f)));f=$CLJS.Mc(f)}else return null},null,null)}(function(){var d=null==a?null:$CLJS.l9.h(a);
return null==d?null:$CLJS.q(d)}())},hya=function(a,b){return function e(d){return new $CLJS.pe(null,function(){for(var f=d;;)if(f=$CLJS.y(f)){if($CLJS.Bd(f)){var k=$CLJS.mc(f),l=$CLJS.D(k),m=$CLJS.se(l);return function(){for(var x=0;;)if(x<l){var A=$CLJS.ld(k,x);$CLJS.I(A,0,null);var C=$CLJS.I(A,1,null),G=function(){var K=C;return null==K?null:$CLJS.q(K)}();$CLJS.n(function(){var K=G;return $CLJS.n(K)?$CLJS.E.g($CLJS.XJ.h(G),b):K}())&&m.add(G);x+=1}else return!0}()?$CLJS.ve($CLJS.xe(m),e($CLJS.nc(f))):
$CLJS.ve($CLJS.xe(m),null)}var t=$CLJS.z(f);$CLJS.I(t,0,null);var u=$CLJS.I(t,1,null),v=function(){var x=u;return null==x?null:$CLJS.q(x)}();if($CLJS.n(function(){var x=v;return $CLJS.n(x)?$CLJS.E.g($CLJS.XJ.h(v),b):x}()))return $CLJS.ge(v,e($CLJS.Mc(f)));f=$CLJS.Mc(f)}else return null},null,null)}(function(){var d=null==a?null:$CLJS.m9.h(a);return null==d?null:$CLJS.q(d)}())},y9=function(a,b,c,d){this.eg=a;this.Eg=b;this.metadata=c;this.ki=d;this.C=393216;this.I=0},iya=function(a){return $CLJS.Za(a)?
cya(a,function(b){return void 0!==b}):a},z9=function(a){return $CLJS.fs($CLJS.Iy(dya(a,function(b){return iya(b)})),function(b){return $CLJS.kk.j($CLJS.yz(b,$CLJS.Bh),$CLJS.aj,$CLJS.Bh)})},A9=function(a,b){if($CLJS.uY(b))a=b;else{var c=new $CLJS.h(null,6,[$CLJS.q9,x9($CLJS.SO,b),$CLJS.o9,x9($CLJS.MV,b),$CLJS.TD,x9($CLJS.lF,b),$CLJS.j9,x9($CLJS.tM,b),$CLJS.l9,x9($CLJS.gF,b),$CLJS.m9,x9($CLJS.JE,b)],null),d=$CLJS.Gz($CLJS.wx);$CLJS.n($CLJS.Fz("metabase.lib.js.metadata",d))&&$CLJS.Ez("metabase.lib.js.metadata",
d,$CLJS.vv.l($CLJS.H(["Created metadata provider for metadata"])),null);a=new y9(a,b,c,$CLJS.N)}return a},B9=function(a){a=$CLJS.Uz(a);const b=a.length-1;a=0<=b&&a.indexOf("?",b)==b?["is-",$CLJS.Az(a,/\?$/,"")].join(""):a;return $CLJS.BA.h?$CLJS.BA.h(a):$CLJS.BA.call(null,a)},E9=function(a){return $CLJS.yd(a)?C9.h?C9.h(a):C9.call(null,a):$CLJS.xd(a)?D9.h?D9.h(a):D9.call(null,a):a instanceof $CLJS.M?$CLJS.Uz(a):a},F9=function(a,b){return $CLJS.TV($CLJS.TV((0,$CLJS.BX)($CLJS.v9($CLJS.Iy(a))),$CLJS.gP,
function(c){return $CLJS.zk.l($CLJS.H([new $CLJS.h(null,1,[$CLJS.DP,$CLJS.N],null),c]))}),$CLJS.HE,function(c){var d=function(){var e=$CLJS.TD.h(c);return $CLJS.n(e)?e:function l(k){return new $CLJS.pe(null,function(){for(;;){var m=$CLJS.y(k);if(m){if($CLJS.Bd(m)){var t=$CLJS.mc(m),u=$CLJS.D(t),v=$CLJS.se(u);a:for(var x=0;;)if(x<u){var A=$CLJS.ld(t,x);v.add(new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.lF,A,null],null));x+=1}else{t=!0;break a}return t?$CLJS.ve($CLJS.xe(v),l($CLJS.nc(m))):$CLJS.ve($CLJS.xe(v),
null)}v=$CLJS.z(m);return $CLJS.ge(new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.lF,v,null],null),l($CLJS.Mc(m)))}return null}},null,null)}(b)}();return $CLJS.T.j(c,$CLJS.TD,$CLJS.J7(d))})},jya=function(a){return $CLJS.n(function(){var b=$CLJS.z(a),c=new $CLJS.ch(null,new $CLJS.h(null,2,[$CLJS.JE,null,$CLJS.gF,null],null),null);return c.h?c.h(b):c.call(null,b)}())?$CLJS.ok.j(a,0,2):$CLJS.kk.v(a,2,$CLJS.fs,function(b){return $CLJS.oe(b)?$CLJS.Uz(b):b})},H9=function(a){return $CLJS.XX.h($CLJS.kk.j($CLJS.Hy(a,
$CLJS.H([$CLJS.yi,!0])),0,$CLJS.Bh))},kya=function(a){var b=$CLJS.Za(a)?a:null;return $CLJS.n(b)?(a=$CLJS.u9.h?$CLJS.u9.h(b):$CLJS.u9.call(null,b),$CLJS.E.g($CLJS.IJ.h(a),$CLJS.hK)?(b=H9(b.field_ref),$CLJS.T.j(a,$CLJS.t0,$CLJS.jd(b))):a):a},I9=function(a,b){var c=null==a?null:$CLJS.z(a);c=null==c?null:$CLJS.E.g(c,$CLJS.aF);return $CLJS.n(c)?$CLJS.T.j(b,$CLJS.t0,$CLJS.jd(a)):b},J9=function(a){return function(b){var c=function(){var e=a.h?a.h(b):a.call(null,b);return $CLJS.u9.h?$CLJS.u9.h(e):$CLJS.u9.call(null,
e)}(),d=function(){var e=$CLJS.g1.h(c);return $CLJS.n(e)?H9(e):null}();return new $CLJS.h(null,3,[$CLJS.Ni,I9(d,c),$CLJS.C5,d,$CLJS.nj,b.value],null)}};$CLJS.g=y9.prototype;$CLJS.g.P=function(a,b){return new y9(this.eg,this.Eg,this.metadata,b)};$CLJS.g.O=function(){return this.ki};$CLJS.g.li=$CLJS.Cc;$CLJS.g.ug=function(a,b){a=this.metadata;a=null==a?null:$CLJS.l9.h(a);a=null==a?null:$CLJS.q(a);b=null==a?null:$CLJS.J.g(a,b);return null==b?null:$CLJS.q(b)};
$CLJS.g.vg=function(a,b){return gya(this.metadata,b)};$CLJS.g.zg=function(a,b){a=this.metadata;a=null==a?null:$CLJS.o9.h(a);a=null==a?null:$CLJS.q(a);b=null==a?null:$CLJS.J.g(a,b);return null==b?null:$CLJS.q(b)};$CLJS.g.tg=function(a,b){return fya(this.metadata,b)};$CLJS.g.sg=function(a,b){a=this.metadata;a=null==a?null:$CLJS.TD.h(a);a=null==a?null:$CLJS.q(a);b=null==a?null:$CLJS.J.g(a,b);return null==b?null:$CLJS.q(b)};$CLJS.g.xg=function(a,b){return hya(this.metadata,b)};
$CLJS.g.yg=function(a,b){return $CLJS.$8($CLJS.$8(this.Eg,"settings"),$CLJS.ih(b))};$CLJS.g.qg=function(a,b){a=this.metadata;a=null==a?null:$CLJS.j9.h(a);a=null==a?null:$CLJS.q(a);b=null==a?null:$CLJS.J.g(a,b);return null==b?null:$CLJS.q(b)};$CLJS.g.wg=function(a,b){a=this.metadata;a=null==a?null:$CLJS.m9.h(a);a=null==a?null:$CLJS.q(a);b=null==a?null:$CLJS.J.g(a,b);return null==b?null:$CLJS.q(b)};
$CLJS.g.rg=function(){var a=this.metadata,b=this.eg;a=null==a?null:$CLJS.q9.h(a);a=null==a?null:$CLJS.q(a);b=null==a?null:$CLJS.J.g(a,b);return null==b?null:$CLJS.q(b)};var K9=function K9(a){switch(arguments.length){case 1:return K9.h(arguments[0]);case 2:return K9.g(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$CLJS.p.h(arguments.length)].join(""));}};$CLJS.Aa("metabase.lib.js.extract_template_tags",K9);K9.h=function(a){return K9.g(a,$CLJS.N)};K9.g=function(a,b){return $CLJS.Bk($CLJS.Zwa.l($CLJS.H([a,z9(b)])))};K9.A=2;
var L9=function L9(a){switch(arguments.length){case 2:return L9.g(arguments[0],arguments[1]);case 3:return L9.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$CLJS.p.h(arguments.length)].join(""));}};$CLJS.Aa("metabase.lib.js.query",L9);L9.g=function(a,b){return $CLJS.X8.l($CLJS.H([a,b]))};
L9.j=function(a,b,c){c=$CLJS.XX.h((0,$CLJS.BX)($CLJS.j1($CLJS.c7(c),$CLJS.aj,$CLJS.HE)));var d=$CLJS.Gz($CLJS.wx);$CLJS.n($CLJS.Fz("metabase.lib.js",d))&&$CLJS.Ez("metabase.lib.js",d,$CLJS.sV("query map: %s",$CLJS.H([$CLJS.Oh.l($CLJS.H([c]))])),null);return $CLJS.X8.l($CLJS.H([A9(a,b),c]))};L9.A=3;
var M9=function M9(a){return $CLJS.oe(a)?[$CLJS.ke(a),"/",$CLJS.ih(a)].join(""):$CLJS.yd(a)?$CLJS.fs(a,M9):$CLJS.xd(a)?$CLJS.kf.g(M9,a):a},C9=$CLJS.Tz(function(a){return $CLJS.fb(function(b,c){var d=$CLJS.I(c,0,null);c=$CLJS.I(c,1,null);d=B9(d);c=E9.h?E9.h(c):E9.call(null,c);b[d]=c;return b},{},a)}),D9=$CLJS.Tz(function(a){return $CLJS.ye($CLJS.kf.g(E9,a))}),N9=function N9(a){switch(arguments.length){case 1:return N9.h(arguments[0]);case 2:return N9.g(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",
$CLJS.p.h(arguments.length)].join(""));}};$CLJS.Aa("metabase.lib.js.order_by_clause",N9);N9.h=function(a){return N9.g(a,$CLJS.iF)};N9.g=function(a,b){return $CLJS.bxa.l($CLJS.H([$CLJS.W8.l($CLJS.H([$CLJS.Hy(a,$CLJS.H([$CLJS.yi,!0]))])),$CLJS.Bh.h(b)]))};N9.A=2;var O9=function O9(a){switch(arguments.length){case 2:return O9.g(arguments[0],arguments[1]);case 3:return O9.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$CLJS.p.h(arguments.length)].join(""));}};
$CLJS.Aa("metabase.lib.js.available_binning_strategies",O9);O9.g=function(a,b){return $CLJS.ye($CLJS.V8.l($CLJS.H([a,b])))};O9.j=function(a,b,c){return $CLJS.ye($CLJS.V8.l($CLJS.H([a,b,c])))};O9.A=3;var P9=function P9(a){switch(arguments.length){case 2:return P9.g(arguments[0],arguments[1]);case 3:return P9.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$CLJS.p.h(arguments.length)].join(""));}};$CLJS.Aa("metabase.lib.js.available_temporal_buckets",P9);
P9.g=function(a,b){return $CLJS.ye($CLJS.Z8.l($CLJS.H([a,b])))};P9.j=function(a,b,c){return $CLJS.ye($CLJS.Z8.l($CLJS.H([a,b,c])))};P9.A=3;var Q9=function Q9(a){switch(arguments.length){case 2:return Q9.g(arguments[0],arguments[1]);case 3:return Q9.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$CLJS.p.h(arguments.length)].join(""));}};$CLJS.Aa("metabase.lib.js.query_EQ_",Q9);Q9.g=function(a,b){return Q9.j(a,b,null)};
Q9.j=function(a,b,c){a=F9(a,c);b=F9(b,c);return $CLJS.E.g(a,b)};Q9.A=3;var R9=function R9(a){switch(arguments.length){case 1:return R9.h(arguments[0]);case 2:return R9.g(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$CLJS.p.h(arguments.length)].join(""));}};$CLJS.Aa("metabase.lib.js.aggregation_clause",R9);R9.h=function(a){return $CLJS.T8.l($CLJS.H([a]))};R9.g=function(a,b){return $CLJS.T8.l($CLJS.H([a,b]))};R9.A=2;
var S9=function S9(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return S9.l(arguments[0],arguments[1],2<c.length?new $CLJS.w(c.slice(2),0,null):null)};$CLJS.Aa("metabase.lib.js.filter_clause",S9);S9.l=function(a,b,c){return $CLJS.P.v($CLJS.nwa,a,b,c)};S9.A=2;S9.B=function(a){var b=$CLJS.z(a),c=$CLJS.B(a);a=$CLJS.z(c);c=$CLJS.B(c);return this.l(b,a,c)};
var T9=function T9(a){switch(arguments.length){case 2:return T9.g(arguments[0],arguments[1]);case 3:return T9.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$CLJS.p.h(arguments.length)].join(""));}};$CLJS.Aa("metabase.lib.js.expressionable_columns",T9);T9.g=function(a,b){return T9.g(a,b)};T9.j=function(a,b,c){return $CLJS.ye($CLJS.$va.l($CLJS.H([a,b,c])))};T9.A=3;
var U9=function U9(a){switch(arguments.length){case 3:return U9.j(arguments[0],arguments[1],arguments[2]);case 4:return U9.v(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error(["Invalid arity: ",$CLJS.p.h(arguments.length)].join(""));}};$CLJS.Aa("metabase.lib.js.with_different_database",U9);U9.j=function(a,b,c){return U9.v(a,b,c,null)};U9.v=function(a,b,c,d){return $CLJS.Xwa.l($CLJS.H([a,A9(b,c),$CLJS.Hy(d,$CLJS.H([$CLJS.yi,!0]))]))};U9.A=4;
var lya=J9(function(a){return a.col}),mya=J9(function(a){return a.column}),V9=function V9(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return V9.l(arguments[0],arguments[1],arguments[2],3<c.length?new $CLJS.w(c.slice(3),0,null):null)};$CLJS.Aa("metabase.lib.js.drill_thru",V9);V9.l=function(a,b,c,d){return $CLJS.P.M($CLJS.Tva,a,b,c,d)};V9.A=3;
V9.B=function(a){var b=$CLJS.z(a),c=$CLJS.B(a);a=$CLJS.z(c);var d=$CLJS.B(c);c=$CLJS.z(d);d=$CLJS.B(d);return this.l(b,a,c,d)};
module.exports={returned_columns:function(a,b){var c=$CLJS.DV(a,b);return $CLJS.ye($CLJS.kf.g(function(d){return $CLJS.T.j(d,$CLJS.LY,!0)},$CLJS.N_.j(a,b,c)))},legacy_expression_for_expression_clause:function(a,b,c){b=$CLJS.U8.l($CLJS.H([a,b]));a=$CLJS.gg.j($CLJS.N,$CLJS.Kl(function(k,l){$CLJS.I(l,0,null);l=$CLJS.I(l,1,null);l=$CLJS.O(l);l=$CLJS.J.g(l,$CLJS.AD);return new $CLJS.Q(null,2,5,$CLJS.R,[k,l],null)}),b);b=$CLJS.gg.j($CLJS.N,$CLJS.Kl(function(k,l){$CLJS.I(l,0,null);l=$CLJS.I(l,1,null);l=
$CLJS.O(l);l=$CLJS.J.g(l,$CLJS.AD);return new $CLJS.Q(null,2,5,$CLJS.R,[l,k],null)}),b);var d=$CLJS.WX,e=$CLJS.VX;$CLJS.WX=a;$CLJS.VX=b;try{var f=$CLJS.MX.h(c);return $CLJS.Bk($CLJS.Ad(f)&&$CLJS.E.g($CLJS.z(f),$CLJS.sL)?$CLJS.J.g(f,1):f)}finally{$CLJS.VX=e,$CLJS.WX=d}},drop_stage_if_empty:function(a){return $CLJS.mxa.l($CLJS.H([a]))},extract_template_tags:K9,engine:function(a){return $CLJS.ih($CLJS.Swa.l($CLJS.H([a])))},filter_operator:function(a,b,c){return $CLJS.owa.l($CLJS.H([a,b,c]))},binning:function(a){return $CLJS.Jva.l($CLJS.H([a]))},
query:L9,columns_group_columns:function(a){return $CLJS.ye($CLJS.Ova.l($CLJS.H([a])))},join_fields:function(a){a=$CLJS.Cwa.l($CLJS.H([a]));return a instanceof $CLJS.M?$CLJS.Uz(a):$CLJS.ye(a)},aggregate:function(a,b,c){return $CLJS.Fva.l($CLJS.H([a,b,$CLJS.Hy(c,$CLJS.H([$CLJS.yi,!0]))]))},join_conditions:function(a){return $CLJS.ye($CLJS.Bwa.l($CLJS.H([a])))},query_EQ_:Q9,temporal_bucket:function(a){return $CLJS.qxa.l($CLJS.H([a]))},available_drill_thrus:function(a,b,c,d,e,f){var k=$CLJS.U8.l($CLJS.H([a,
b])),l=$CLJS.gg.j($CLJS.N,$CLJS.Kl(function(v,x){$CLJS.I(x,0,null);x=$CLJS.I(x,1,null);x=$CLJS.O(x);x=$CLJS.J.g(x,$CLJS.AD);return new $CLJS.Q(null,2,5,$CLJS.R,[v,x],null)}),k);k=$CLJS.gg.j($CLJS.N,$CLJS.Kl(function(v,x){$CLJS.I(x,0,null);x=$CLJS.I(x,1,null);x=$CLJS.O(x);x=$CLJS.J.g(x,$CLJS.AD);return new $CLJS.Q(null,2,5,$CLJS.R,[x,v],null)}),k);var m=$CLJS.WX,t=$CLJS.VX;$CLJS.WX=l;$CLJS.VX=k;try{var u=function(){var v=$CLJS.n(c)?c.field_ref:c;return $CLJS.n(v)?H9(v):null}();return $CLJS.ye($CLJS.Sva.l($CLJS.H([a,
b,$CLJS.zk.l($CLJS.H([new $CLJS.h(null,3,[$CLJS.Ni,$CLJS.n(c)?I9(u,$CLJS.u9.h?$CLJS.u9.h(c):$CLJS.u9.call(null,c)):null,$CLJS.C5,u,$CLJS.nj,void 0===d?null:null==d?$CLJS.KK:d],null),$CLJS.n(e)?new $CLJS.h(null,1,[$CLJS.B5,$CLJS.jk.g(lya,e)],null):null,$CLJS.n($CLJS.Ie(f))?new $CLJS.h(null,1,[$CLJS.FK,$CLJS.jk.g(mya,f)],null):null]))])))}finally{$CLJS.VX=t,$CLJS.WX=m}},remove_clause:function(a,b,c){return $CLJS.fxa.l($CLJS.H([a,b,$CLJS.W8.l($CLJS.H([$CLJS.Hy(c,$CLJS.H([$CLJS.yi,!0]))]))]))},source_table_or_card_id:function(a){var b=
$CLJS.SZ(a);if($CLJS.n(b))return b;a=$CLJS.n1(a);return null==a?null:["card__",$CLJS.p.h(a)].join("")},legacy_ref:function(a){return $CLJS.Bk(jya($CLJS.MX.h($CLJS.Y8.l($CLJS.H([a])))))},replace_clause:function(a,b,c,d){return $CLJS.ixa.l($CLJS.H([a,b,$CLJS.W8.l($CLJS.H([$CLJS.Hy(c,$CLJS.H([$CLJS.yi,!0]))])),$CLJS.W8.l($CLJS.H([$CLJS.Hy(d,$CLJS.H([$CLJS.yi,!0]))]))]))},drop_stage:function(a){return $CLJS.lxa.l($CLJS.H([a]))},join_lhs_display_name:function(a,b,c,d){return $CLJS.Dwa.l($CLJS.H([a,b,c,
d]))},add_field:function(a,b,c){return $CLJS.ewa.l($CLJS.H([a,b,c]))},pivot_types:function(a){return $CLJS.ye($CLJS.kf.g($CLJS.ih,$CLJS.Vva.l($CLJS.H([a]))))},native_extras:function(a){return $CLJS.Bk($CLJS.Vwa.l($CLJS.H([a])))},available_temporal_buckets:P9,with_binning:function(a,b){return $CLJS.Kva.l($CLJS.H([a,b]))},append_stage:function(a){return $CLJS.kxa.l($CLJS.H([a]))},join:function(a,b,c){return $CLJS.vwa.l($CLJS.H([a,b,c]))},aggregations:function(a,b){return $CLJS.ye($CLJS.U8.l($CLJS.H([a,
b])))},drill_thru:V9,raw_native_query:function(a){return $CLJS.Pwa.l($CLJS.H([a]))},filterable_column_operators:function(a){return $CLJS.ye($CLJS.mwa.l($CLJS.H([a])))},with_temporal_bucket:function(a,b){return $CLJS.rxa.l($CLJS.H([a,b]))},with_join_conditions:function(a,b){return $CLJS.Kwa.l($CLJS.H([a,$CLJS.Hy(b,$CLJS.H([$CLJS.yi,!0]))]))},update_lat_lon_filter:function(a,b,c,d,e){e=$CLJS.Hy(e,$CLJS.H([$CLJS.yi,!0]));return $CLJS.rwa.l($CLJS.H([a,b,c,d,e]))},available_metrics:function(a){return $CLJS.ye($CLJS.Nwa.l($CLJS.H([a])))},
with_different_database:U9,with_fields:function(a,b,c){return $CLJS.iwa.l($CLJS.H([a,b,c]))},is_column_metadata:function(a){return $CLJS.yd(a)&&$CLJS.E.g($CLJS.GJ,$CLJS.Us.h(a))},filter_args_display_name:function(a,b,c){return $CLJS.dwa.l($CLJS.H([a,b,c]))},join_clause:function(a,b){return $CLJS.wwa.l($CLJS.H([a,b]))},aggregation_clause:R9,external_op:function(a){a=$CLJS.Qva.l($CLJS.H([a]));var b=$CLJS.O(a);a=$CLJS.J.g(b,$CLJS.vD);var c=$CLJS.J.g(b,$CLJS.Yi);b=$CLJS.J.g(b,$CLJS.Kr);return{operator:a,
options:$CLJS.Bk(c),args:$CLJS.ye(b)}},with_join_fields:function(a,b){return $CLJS.Iwa.l($CLJS.H([a,"string"===typeof b?$CLJS.Bh.h(b):b]))},visible_columns:function(a,b){var c=$CLJS.DV(a,b),d=$CLJS.P_.j(a,b,c);c=$CLJS.N_.j(a,b,c);return $CLJS.ye($CLJS.V2(a,b,d,c))},update_numeric_filter:function(a,b,c,d,e){return $CLJS.swa.l($CLJS.H([a,b,c,d,e]))},available_binning_strategies:O9,update_temporal_filter:function(a,b,c,d,e){return $CLJS.twa.l($CLJS.H([a,b,c,d,e]))},find_column_indexes_from_legacy_refs:function(a,
b,c,d){var e=$CLJS.aF.h($CLJS.DV(a,b)),f=$CLJS.gg.j($CLJS.N,$CLJS.Kl(function(u,v){$CLJS.I(v,0,null);v=$CLJS.I(v,1,null);v=$CLJS.O(v);v=$CLJS.J.g(v,$CLJS.AD);return new $CLJS.Q(null,2,5,$CLJS.R,[u,v],null)}),e);e=$CLJS.gg.j($CLJS.N,$CLJS.Kl(function(u,v){$CLJS.I(v,0,null);v=$CLJS.I(v,1,null);v=$CLJS.O(v);v=$CLJS.J.g(v,$CLJS.AD);return new $CLJS.Q(null,2,5,$CLJS.R,[v,u],null)}),e);var k=$CLJS.WX,l=$CLJS.VX;$CLJS.WX=f;$CLJS.VX=e;try{var m=$CLJS.jk.g(kya,c),t=$CLJS.kf.g(H9,d);return $CLJS.ye(eya(a,b,
t,m))}finally{$CLJS.VX=l,$CLJS.WX=k}},expression:function(a,b,c,d){return $CLJS.Yva.l($CLJS.H([a,b,c,d]))},describe_relative_datetime:function(a,b){a="string"===typeof a?$CLJS.Bh.h(a):a;b="string"===typeof b?$CLJS.Bh.h(b):b;return $CLJS.pxa.l($CLJS.H([a,b]))},order_bys:function(a,b){return $CLJS.ye($CLJS.cxa.l($CLJS.H([a,b])))},display_info:function(a,b,c){return $CLJS.b_($CLJS.Bh.g("display-info-outer",["stage-",$CLJS.p.h(b)].join("")),c,function(d){return E9($CLJS.Lwa.l($CLJS.H([$CLJS.n3(a,b),b,
d])))})},fieldable_columns:function(a,b){return $CLJS.ye($CLJS.fwa.l($CLJS.H([a,b])))},template_tags:function(a){return $CLJS.Bk($CLJS.Rwa.l($CLJS.H([a])))},selected_aggregation_operators:function(a,b){return $CLJS.ye($CLJS.Iva.l($CLJS.H([$CLJS.y(a),b])))},order_by_clause:N9,filterable_columns:function(a,b){return $CLJS.ye($CLJS.lwa.l($CLJS.H([a,b])))},join_condition_rhs_columns:function(a,b,c,d,e){return $CLJS.ye($CLJS.zwa.l($CLJS.H([a,b,c,d,e])))},join_condition_update_temporal_bucketing:function(a,
b,c,d){return $CLJS.Awa.l($CLJS.H([a,b,c,d]))},filters:function(a,b){return $CLJS.ye($CLJS.kwa.l($CLJS.H([a,b])))},join_condition_lhs_columns:function(a,b,c,d,e){return $CLJS.ye($CLJS.xwa.l($CLJS.H([a,b,c,d,e])))},table_or_card_metadata:function(a,b){return $CLJS.Y0(a,b)},with_expression_name:function(a,b){return $CLJS.awa.l($CLJS.H([a,b]))},orderable_columns:function(a,b){return $CLJS.ye($CLJS.y7.g(a,b))},find_filter_for_legacy_filter:function(a,b,c){return $CLJS.pwa.l($CLJS.H([a,b,$CLJS.Hy(c,$CLJS.H([$CLJS.yi,
!0]))]))},suggestedName:function(a){return $CLJS.Mwa.l($CLJS.H([a]))},find_column_for_legacy_ref:function(a,b,c,d){return $CLJS.Wva.l($CLJS.H([a,b,c,d]))},has_write_permission:function(a){return $CLJS.Ywa.l($CLJS.H([a]))},metadataProvider:A9,filter_clause:S9,fields:function(a,b){return $CLJS.ye($CLJS.gwa.l($CLJS.H([a,b])))},available_aggregation_operators:function(a,b){return $CLJS.ye($CLJS.Hva.l($CLJS.H([a,b])))},breakouts:function(a,b){return $CLJS.ye($CLJS.Nva.l($CLJS.H([a,b])))},joinable_columns:function(a,
b,c){return $CLJS.ye($CLJS.Fwa.l($CLJS.H([a,b,c])))},group_columns:function(a){return $CLJS.ye($CLJS.Pva.l($CLJS.H([a])))},describe_temporal_unit:function(a,b){b="string"===typeof b?$CLJS.Bh.h(b):b;return $CLJS.nxa.l($CLJS.H([a,b]))},joins:function(a,b){return $CLJS.ye($CLJS.Gwa.l($CLJS.H([a,b])))},native_query:function(a,b,c){return $CLJS.Owa.l($CLJS.H([A9(a,b),c]))},available_join_strategies:function(a,b){return $CLJS.ye($CLJS.uwa.l($CLJS.H([a,b])))},legacy_query:function(a){return $CLJS.Bk.l(M9($CLJS.MX.h(a)),
$CLJS.H([$CLJS.Oj,$CLJS.Uz]))},stage_count:function(a){return $CLJS.dxa.l($CLJS.H([a]))},expression_clause:function(a,b,c){return $CLJS.W8.l($CLJS.H([$CLJS.bwa.l($CLJS.H([$CLJS.Bh.h(a),b,$CLJS.Hy(c,$CLJS.H([$CLJS.yi,!0]))]))]))},find_matching_column:function(a,b,c,d){return $CLJS.Xva.l($CLJS.H([a,b,c,d]))},with_native_extras:function(a,b){return $CLJS.Wwa.l($CLJS.H([a,$CLJS.Hy(b,$CLJS.H([$CLJS.yi,!0]))]))},join_strategy:function(a){return $CLJS.Ewa.l($CLJS.H([a]))},picker_info:function(a,b){var c=
$CLJS.Us.h(b);switch(c instanceof $CLJS.M?c.S:null){case "metadata/table":return{databaseId:$CLJS.SO.h(a),tableId:$CLJS.Si.h(b)};case "metadata/card":return{databaseId:$CLJS.SO.h(a),tableId:["card__",$CLJS.p.h($CLJS.Si.h(b))].join(""),cardId:$CLJS.Si.h(b),isModel:$CLJS.CY.h(b)};default:return a=$CLJS.Gz($CLJS.zx),$CLJS.n($CLJS.Fz("metabase.lib.js",a))&&$CLJS.Ez("metabase.lib.js",a,$CLJS.vv.l($CLJS.H(["Cannot provide picker-info for",$CLJS.Us.h(b)])),null),null}},expression_parts:function(a,b,c){a=
$CLJS.cwa.l($CLJS.H([a,b,c]));return $CLJS.sU(function(d){if($CLJS.yd(d)&&$CLJS.E.g($CLJS.k8,$CLJS.Us.h(d))){var e=$CLJS.O(d);d=$CLJS.J.g(e,$CLJS.vD);var f=$CLJS.J.g(e,$CLJS.Yi);e=$CLJS.J.g(e,$CLJS.Kr);return{operator:$CLJS.ih(d),options:$CLJS.Bk($CLJS.Hl(f,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.tF,$CLJS.Nk],null))),args:$CLJS.ye($CLJS.kf.g(function(k){return k instanceof $CLJS.M?$CLJS.Uz(k):k},e))}}return d},a)},expression_clause_for_legacy_expression:function(a,b,c){b=$CLJS.U8.l($CLJS.H([a,b]));a=
$CLJS.gg.j($CLJS.N,$CLJS.Kl(function(l,m){$CLJS.I(m,0,null);m=$CLJS.I(m,1,null);m=$CLJS.O(m);m=$CLJS.J.g(m,$CLJS.AD);return new $CLJS.Q(null,2,5,$CLJS.R,[l,m],null)}),b);b=$CLJS.gg.j($CLJS.N,$CLJS.Kl(function(l,m){$CLJS.I(m,0,null);m=$CLJS.I(m,1,null);m=$CLJS.O(m);m=$CLJS.J.g(m,$CLJS.AD);return new $CLJS.Q(null,2,5,$CLJS.R,[m,l],null)}),b);var d=$CLJS.WX,e=$CLJS.VX;$CLJS.WX=a;$CLJS.VX=b;try{var f=$CLJS.Hy(c,$CLJS.H([$CLJS.yi,!0])),k=$CLJS.z($CLJS.CX(new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.HE,$CLJS.aF],
null),new $CLJS.Q(null,1,5,$CLJS.R,[f],null)));return $CLJS.XX.h(k)}finally{$CLJS.VX=e,$CLJS.WX=d}},format_relative_date_range:function(a,b,c,d,e){b=$CLJS.Bh.h(b);d=null==d?null:$CLJS.Bh.h(d);e=$CLJS.Hy(e,$CLJS.H([$CLJS.yi,!0]));return $CLJS.Z1((0,$CLJS.MH)(),a,b,c,d,e)},aggregation_operator_columns:function(a){return $CLJS.ye($CLJS.Gva.l($CLJS.H([a])))},find_filterable_column_for_legacy_ref:function(a,b,c){return $CLJS.qwa.l($CLJS.H([a,b,c]))},available_segments:function(a,b){return $CLJS.ye($CLJS.jxa.l($CLJS.H([a,
b])))},join_condition_operators:function(a,b,c,d){return $CLJS.ye($CLJS.ywa.l($CLJS.H([a,b,c,d])))},expressionable_columns:T9,filter:function(a,b,c){return $CLJS.jwa.l($CLJS.H([a,b,$CLJS.Hy(c,$CLJS.H([$CLJS.yi,!0]))]))},change_direction:function(a,b){return $CLJS.$wa.l($CLJS.H([a,b]))},pivot_columns_for_type:function(a,b){return $CLJS.ye($CLJS.Uva.l($CLJS.H([a,$CLJS.Bh.h(b)])))},filter_drill_details:function(a){var b=$CLJS.O(a);a=$CLJS.J.g(b,$CLJS.HE);var c=$CLJS.J.g(b,$CLJS.Ni),d=$CLJS.J.g(b,$CLJS.CK);
b=$CLJS.J.g(b,$CLJS.nj);return{column:c,query:a,stageIndex:d,value:$CLJS.E.g(b,$CLJS.KK)?null:b}},remove_field:function(a,b,c){return $CLJS.hwa.l($CLJS.H([a,b,c]))},with_template_tags:function(a,b){return $CLJS.Twa.l($CLJS.H([a,z9(b)]))},expressions:function(a,b){return $CLJS.ye($CLJS.Zva.l($CLJS.H([a,b])))},suggested_join_conditions:function(a,b,c){return $CLJS.ye($CLJS.Hwa.l($CLJS.H([a,b,c])))},with_join_strategy:function(a,b){return $CLJS.Jwa.l($CLJS.H([a,b]))},order_by:function(a,b,c,d){return $CLJS.axa.l($CLJS.H([a,
b,c,$CLJS.Bh.h(d)]))},field_values_search_info:function(a,b){var c=$CLJS.kk.j;if($CLJS.n(b)){var d=$CLJS.Si.h(b),e=$CLJS.Si.h;var f=$CLJS.FZ(b)?b:null;$CLJS.n(f)?a=f:(f=$CLJS.wz(b,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.VJ,$CLJS.RJ],null)),a=$CLJS.n(f)?$CLJS.Q0(a,f):null,a=$CLJS.n(a)?a:b);a=w9(a)?a:null;e=e.call($CLJS.Si,a);d=$CLJS.ql(d)?d:null;e=$CLJS.ql(e)?e:null;$CLJS.n(b)?(b=$CLJS.O(b),a=$CLJS.J.g(b,$CLJS.TY),b=$CLJS.E.g(a,$CLJS.VY)?$CLJS.mj:$CLJS.n(a)?a:w9(b)?$CLJS.zY:$CLJS.$y):b=$CLJS.$y;b=new $CLJS.h(null,
3,[$CLJS.RJ,d,$CLJS.V6,e,$CLJS.TY,b],null)}else b=null;return $CLJS.Bk($CLJS.yz(c.call($CLJS.kk,b,$CLJS.TY,$CLJS.ih),B9))},describe_temporal_interval:function(a,b){a="string"===typeof a?$CLJS.Bh.h(a):a;b="string"===typeof b?$CLJS.Bh.h(b):b;return $CLJS.oxa.l($CLJS.H([a,b]))},breakout:function(a,b,c){return $CLJS.Lva.l($CLJS.H([a,b,$CLJS.Y8.l($CLJS.H([c]))]))},database_id:function(a){return $CLJS.Rva.l($CLJS.H([a]))},required_native_extras:function(a,b){return $CLJS.ye($CLJS.kf.g($CLJS.Uz,$CLJS.Uwa.l($CLJS.H([A9(a,
b)]))))},remove_join:function(a,b,c){return $CLJS.gxa.l($CLJS.H([a,b,c]))},joined_thing:function(a,b){return $CLJS.h3(a,b)},with_native_query:function(a,b){return $CLJS.Qwa.l($CLJS.H([a,b]))},breakoutable_columns:function(a,b){return $CLJS.ye($CLJS.Mva.l($CLJS.H([a,b])))},rename_join:function(a,b,c,d){return $CLJS.hxa.l($CLJS.H([a,b,c,d]))},with_different_table:function(a,b){return $CLJS.exa.l($CLJS.H([a,b]))}};