var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./metabase.lib.schema.common.js");require("./metabase.lib.schema.expression.js");require("./metabase.lib.schema.mbql_clause.js");require("./metabase.lib.schema.temporal_bucketing.js");require("./metabase.util.malli.registry.js");
'use strict';$CLJS.KI=new $CLJS.M("metabase.lib.schema.filter","operator","metabase.lib.schema.filter/operator",-805746630);$CLJS.LI=new $CLJS.M("operator","filter","operator/filter",-1518842858);$CLJS.MI=new $CLJS.M(null,"display-name-variant","display-name-variant",-1831788853);for(var NI=$CLJS.y(new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.mr,$CLJS.fr],null)),OI=null,PI=0,QI=0;;)if(QI<PI){var sia=OI.X(null,QI);$CLJS.AE(sia,$CLJS.H([$CLJS.Yr,$CLJS.sj,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Kr,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Sq,new $CLJS.h(null,1,[$CLJS.ln,2],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Uk,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.YD],null)],null)],null)],null)]));QI+=1}else{var RI=$CLJS.y(NI);if(RI){var SI=RI;if($CLJS.Bd(SI)){var TI=$CLJS.mc(SI),tia=$CLJS.nc(SI),
uia=TI,via=$CLJS.D(TI);NI=tia;OI=uia;PI=via}else{var wia=$CLJS.z(SI);$CLJS.AE(wia,$CLJS.H([$CLJS.Yr,$CLJS.sj,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Kr,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Sq,new $CLJS.h(null,1,[$CLJS.ln,2],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Uk,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.YD],null)],null)],null)],null)]));NI=$CLJS.B(SI);OI=null;PI=0}QI=0}else break}$CLJS.yE($CLJS.hr,$CLJS.H([$CLJS.Yr,$CLJS.sj,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.YD],null)]));
for(var UI=$CLJS.y(new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Nj,$CLJS.BF],null)),VI=null,WI=0,XI=0;;)if(XI<WI){var xia=VI.X(null,XI);$CLJS.AE(xia,$CLJS.H([$CLJS.Yr,$CLJS.sj,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Kr,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Sq,new $CLJS.h(null,1,[$CLJS.ln,2],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Uk,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.cE],null)],null)],null)],null)]));XI+=1}else{var YI=$CLJS.y(UI);if(YI){var ZI=YI;if($CLJS.Bd(ZI)){var $I=$CLJS.mc(ZI),yia=$CLJS.nc(ZI),
zia=$I,Aia=$CLJS.D($I);UI=yia;VI=zia;WI=Aia}else{var Bia=$CLJS.z(ZI);$CLJS.AE(Bia,$CLJS.H([$CLJS.Yr,$CLJS.sj,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Kr,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Sq,new $CLJS.h(null,1,[$CLJS.ln,2],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Uk,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.cE],null)],null)],null)],null)]));UI=$CLJS.B(ZI);VI=null;WI=0}XI=0}else break}
for(var aJ=$CLJS.y(new $CLJS.Q(null,4,5,$CLJS.R,[$CLJS.Gq,$CLJS.Iq,$CLJS.Cq,$CLJS.Eq],null)),bJ=null,cJ=0,dJ=0;;)if(dJ<cJ){var Cia=bJ.X(null,dJ);$CLJS.yE(Cia,$CLJS.H([$CLJS.Yr,$CLJS.sj,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.eE],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.eE],null)]));dJ+=1}else{var eJ=$CLJS.y(aJ);if(eJ){var fJ=eJ;if($CLJS.Bd(fJ)){var gJ=$CLJS.mc(fJ),Dia=$CLJS.nc(fJ),Eia=gJ,Fia=$CLJS.D(gJ);aJ=Dia;bJ=Eia;cJ=Fia}else{var Gia=$CLJS.z(fJ);$CLJS.yE(Gia,$CLJS.H([$CLJS.Yr,$CLJS.sj,
new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.eE],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.eE],null)]));aJ=$CLJS.B(fJ);bJ=null;cJ=0}dJ=0}else break}$CLJS.yE($CLJS.NE,$CLJS.H([$CLJS.Yr,$CLJS.sj,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.eE],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.eE],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.eE],null)]));
$CLJS.yE($CLJS.TE,$CLJS.H([$CLJS.Yr,$CLJS.sj,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.eE],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.eE],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.eE],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.eE],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.eE],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.eE],null)]));
for(var hJ=$CLJS.y(new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.ME,$CLJS.YE],null)),iJ=null,jJ=0,kJ=0;;)if(kJ<jJ){var Hia=iJ.X(null,kJ);$CLJS.yE(Hia,$CLJS.H([$CLJS.Yr,$CLJS.sj,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.ZD],null)]));kJ+=1}else{var lJ=$CLJS.y(hJ);if(lJ){var mJ=lJ;if($CLJS.Bd(mJ)){var nJ=$CLJS.mc(mJ),Iia=$CLJS.nc(mJ),Jia=nJ,Kia=$CLJS.D(nJ);hJ=Iia;iJ=Jia;jJ=Kia}else{var Lia=$CLJS.z(mJ);$CLJS.yE(Lia,$CLJS.H([$CLJS.Yr,$CLJS.sj,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.ZD],null)]));hJ=$CLJS.B(mJ);
iJ=null;jJ=0}kJ=0}else break}
for(var oJ=$CLJS.y(new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.OE,$CLJS.VE],null)),pJ=null,qJ=0,rJ=0;;)if(rJ<qJ){var Mia=pJ.X(null,rJ);$CLJS.yE(Mia,$CLJS.H([$CLJS.Yr,$CLJS.sj,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.gE],null)]));rJ+=1}else{var sJ=$CLJS.y(oJ);if(sJ){var tJ=sJ;if($CLJS.Bd(tJ)){var uJ=$CLJS.mc(tJ),Nia=$CLJS.nc(tJ),Oia=uJ,Pia=$CLJS.D(uJ);oJ=Nia;pJ=Oia;qJ=Pia}else{var Qia=$CLJS.z(tJ);$CLJS.yE(Qia,$CLJS.H([$CLJS.Yr,$CLJS.sj,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.gE],null)]));oJ=$CLJS.B(tJ);
pJ=null;qJ=0}rJ=0}else break}
for(var vJ=new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Gj,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.tF,new $CLJS.h(null,1,[$CLJS.Ar,!0],null),$CLJS.vr],null)],null),wJ=$CLJS.y(new $CLJS.Q(null,4,5,$CLJS.R,[$CLJS.cF,$CLJS.wF,$CLJS.kF,$CLJS.dF],null)),xJ=null,yJ=0,zJ=0;;)if(zJ<yJ){var AJ=xJ.X(null,zJ);$CLJS.KF.v(AJ,$CLJS.Yr,$CLJS.sj,new $CLJS.Q(null,5,5,$CLJS.R,[$CLJS.ir,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Nj,AJ],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.rs,$CLJS.yD,vJ],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,
$CLJS.hE],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.hE],null)],null));zJ+=1}else{var BJ=$CLJS.y(wJ);if(BJ){var CJ=BJ;if($CLJS.Bd(CJ)){var DJ=$CLJS.mc(CJ),Ria=$CLJS.nc(CJ),Sia=DJ,Tia=$CLJS.D(DJ);wJ=Ria;xJ=Sia;yJ=Tia}else{var EJ=$CLJS.z(CJ);$CLJS.KF.v(EJ,$CLJS.Yr,$CLJS.sj,new $CLJS.Q(null,5,5,$CLJS.R,[$CLJS.ir,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Nj,EJ],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.rs,$CLJS.yD,vJ],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.hE],null),new $CLJS.Q(null,2,5,$CLJS.R,
[$CLJS.W,$CLJS.hE],null)],null));wJ=$CLJS.B(CJ);xJ=null;yJ=0}zJ=0}else break}
$CLJS.KF.v($CLJS.ZA,$CLJS.Yr,$CLJS.sj,new $CLJS.Q(null,6,5,$CLJS.R,[$CLJS.ir,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Nj,$CLJS.ZA],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.rs,$CLJS.yD,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Gj,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Nk,new $CLJS.h(null,1,[$CLJS.Ar,!0],null),$CLJS.vr],null)],null)],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.WD],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.fr,new $CLJS.Q(null,4,5,$CLJS.R,[$CLJS.cr,$CLJS.Ou,$CLJS.Qw,$CLJS.SE],null),new $CLJS.Q(null,
2,5,$CLJS.R,[$CLJS.W,$CLJS.kE],null)],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.eD],null)],null));$CLJS.KF.v($CLJS.JE,$CLJS.Yr,$CLJS.sj,new $CLJS.Q(null,4,5,$CLJS.R,[$CLJS.ir,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Nj,$CLJS.JE],null),$CLJS.yD,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.fr,$CLJS.kD,$CLJS.sD],null)],null));
$CLJS.Y($CLJS.KI,new $CLJS.Q(null,4,5,$CLJS.R,[$CLJS.Gj,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Us,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Nj,$CLJS.LI],null)],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.eF,new $CLJS.Q(null,17,5,$CLJS.R,[$CLJS.cr,$CLJS.Nj,$CLJS.BF,$CLJS.TE,$CLJS.NE,$CLJS.Gq,$CLJS.Cq,$CLJS.Iq,$CLJS.Eq,$CLJS.ME,$CLJS.YE,$CLJS.OE,$CLJS.VE,$CLJS.kF,$CLJS.dF,$CLJS.cF,$CLJS.wF],null)],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.MI,$CLJS.Qi],null)],null));