var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./metabase.shared.formatting.internal.numbers.js");require("./metabase.shared.formatting.internal.numbers_core.js");require("./metabase.util.js");
'use strict';var Sra=function(a,b){return new $CLJS.pe(null,function(){a:for(var c=a,d=b;;){d=$CLJS.y(d);var e;if(e=d)e=$CLJS.z(d),e=c.h?c.h(e):c.call(null,e);if($CLJS.n(e))d=$CLJS.Mc(d);else break a}return d},null,null)},Tra=function(a,b){return new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.pt(a,b),Sra(a,b)],null)},v4=function(a){var b=$CLJS.zk.l;var c=$CLJS.O(a);var d=$CLJS.J.g(c,$CLJS.o4);c=$CLJS.J.g(c,$CLJS.p4);if($CLJS.n($CLJS.n(d)?$CLJS.E.g(c,"currency"):d)){c=$CLJS.j4.h;d=$CLJS.Bh.h(d);var e=$CLJS.q($CLJS.g4);
d=e.h?e.h(d):e.call(null,d);c=c.call($CLJS.j4,d);c=new $CLJS.h(null,2,[$CLJS.n4,c,$CLJS.q4,c],null)}else c=new $CLJS.h(null,1,[$CLJS.q4,2],null);b=b.call($CLJS.zk,$CLJS.H([c,a]));return $CLJS.n($CLJS.r4.h(a))?$CLJS.T.l($CLJS.ak.g(b,$CLJS.r4),$CLJS.q4,$CLJS.r4.h(a),$CLJS.H([$CLJS.n4,$CLJS.r4.h(a)])):b},w4=function(a,b){if(null!=a&&null!=a.Ne)a=a.Ne(a,b);else{var c=w4[$CLJS.xa(null==a?null:a)];if(null!=c)a=c.g?c.g(a,b):c.call(null,a,b);else if(c=w4._,null!=c)a=c.g?c.g(a,b):c.call(null,a,b);else throw $CLJS.cb("NumberFormatter.format-number-basic",
a);}return a},Ura=function(a,b){var c=$CLJS.Hy(a.formatToParts(b),$CLJS.H([new $CLJS.h(null,1,[$CLJS.yi,!0],null)]));a=$CLJS.n($CLJS.Ue(function(d){return $CLJS.E.g($CLJS.aj.h(d),"exponentMinusSign")},c))?c:function(){var d=Tra(function(f){return $CLJS.gk.g($CLJS.aj.h(f),"exponentInteger")},c),e=$CLJS.I(d,0,null);d=$CLJS.I(d,1,null);return $CLJS.jf.l(e,new $CLJS.Q(null,1,5,$CLJS.R,[new $CLJS.h(null,2,[$CLJS.aj,"exponentPlusSign",$CLJS.nj,"+"],null)],null),$CLJS.H([d]))}();return $CLJS.P.g($CLJS.p,
$CLJS.kf.g(function(d){var e=$CLJS.O(d);d=$CLJS.J.g(e,$CLJS.aj);e=$CLJS.J.g(e,$CLJS.nj);switch(d){case "exponentSeparator":return"e";default:return e}},a))},Vra=function(a,b){switch($CLJS.p4.h(b)){case "scientific":return function(c){return Ura(a,c)};default:return function(c){return a.format(c)}}},x4=function(a,b,c,d,e){this.options=a;this.Ag=b;this.Dg=c;this.de=d;this.ji=e;this.C=393216;this.I=0},Wra=function(a,b){return $CLJS.P.g($CLJS.p,function(){return function e(d){return new $CLJS.pe(null,
function(){for(var f=d;;)if(f=$CLJS.y(f)){if($CLJS.Bd(f)){var k=$CLJS.mc(f),l=$CLJS.D(k),m=$CLJS.se(l);return function(){for(var v=0;;)if(v<l){var x=$CLJS.ld(k,v),A=$CLJS.O(x);x=$CLJS.J.g(A,$CLJS.aj);A=$CLJS.J.g(A,$CLJS.nj);var C=new $CLJS.ch(null,new $CLJS.h(null,2,["currency",null,"integer",null],null),null);C=C.h?C.h(x):C.call(null,x);$CLJS.n(C)&&(x=$CLJS.E.g(x,"integer")?b:A,m.add(x));v+=1}else return!0}()?$CLJS.ve($CLJS.xe(m),e($CLJS.nc(f))):$CLJS.ve($CLJS.xe(m),null)}var t=$CLJS.z(f);t=$CLJS.O(t);
var u=$CLJS.J.g(t,$CLJS.aj);t=$CLJS.J.g(t,$CLJS.nj);if($CLJS.n(function(){var v=new $CLJS.ch(null,new $CLJS.h(null,2,["currency",null,"integer",null],null),null);return v.h?v.h(u):v.call(null,u)}()))return $CLJS.ge($CLJS.E.g(u,"integer")?b:t,e($CLJS.Mc(f)));f=$CLJS.Mc(f)}else return null},null,null)}($CLJS.Hy(a.Ag.formatToParts(1),$CLJS.H([$CLJS.yi,!0])))}())},y4=function(a){var b=$CLJS.E.g($CLJS.p4.h(a),"currency")?2:null;b=new Intl.NumberFormat("en",$CLJS.Bk($CLJS.Dz($CLJS.Ya,$CLJS.Kg([$CLJS.Pra,
$CLJS.Hra,$CLJS.Kra,$CLJS.Mra,$CLJS.Rra,$CLJS.o4,$CLJS.Lra,$CLJS.Nra,$CLJS.Ira,$CLJS.Jra],[$CLJS.q4.g(a,b),$CLJS.t4.h(a),$CLJS.s4.h(a),$CLJS.Ora.h(a),$CLJS.E.g($CLJS.p4.h(a),"scientific")?null:$CLJS.p4.g(a,"decimal"),$CLJS.o4.h(a),!0,$CLJS.n4.g(a,b),$CLJS.E.g($CLJS.p4.h(a),"scientific")?"scientific":null,$CLJS.u4.h(a)]))));var c=$CLJS.t4.h(a);var d=$CLJS.o4.h(a);c=$CLJS.n(d)?null==c||$CLJS.E.g(c,"symbol"):d;d=Vra(b,a);return new x4(a,b,c,d,$CLJS.N)},z4=function(a,b){return y4(v4(b)).Ne(null,a)},B4=
function(a,b){var c=$CLJS.ak.l(b,$CLJS.uA,$CLJS.H([$CLJS.p4])),d=$CLJS.tz(a);if(0===a)return"0";if(1E3>d)return $CLJS.A4.g?$CLJS.A4.g(a,c):$CLJS.A4.call(null,a,c);b=$CLJS.z($CLJS.nf(function(f){return d>=$CLJS.z(f)},Xra));var e=$CLJS.I(b,0,null);b=$CLJS.I(b,1,null);return[$CLJS.p.h(function(){var f=a/e,k=$CLJS.zk.l($CLJS.H([c,new $CLJS.h(null,2,[$CLJS.n4,1,$CLJS.q4,1],null)]));return $CLJS.A4.g?$CLJS.A4.g(f,k):$CLJS.A4.call(null,f,k)}()),$CLJS.p.h(b)].join("")},Yra=function(a,b){var c=v4(b);if($CLJS.n(C4.h(c)))b=
C4.h(c);else if($CLJS.Wa($CLJS.r4.h(c))&&$CLJS.Wa($CLJS.n4.h(c))&&$CLJS.gk.g($CLJS.p4.h(c),"currency")&&$CLJS.tz(a)<($CLJS.E.g($CLJS.p4.h(c),"percent")?.01:1)){b=$CLJS.T.j;var d=$CLJS.ak.g(c,$CLJS.q4);c=$CLJS.u4.g(c,0);b=y4(b.call($CLJS.T,d,$CLJS.s4,2>c?2:c))}else b=y4(c);return w4(b,a)};x4.prototype.P=function(a,b){return new x4(this.options,this.Ag,this.Dg,this.de,b)};x4.prototype.O=function(){return this.ji};
x4.prototype.Ne=function(a,b){a=this.de.h?this.de.h(b):this.de.call(null,b);var c=$CLJS.Qra.h(this.options);$CLJS.n($CLJS.n(c)?$CLJS.gk.g(c,".,"):c)&&(b=$CLJS.z(c),c=$CLJS.id(c),a=$CLJS.Az(a,/[\.,]/,new $CLJS.h(null,2,[",",$CLJS.n(c)?c:"",".",b],null)));$CLJS.n(this.Dg)&&(b=$CLJS.o4.h(this.options),c=$CLJS.h4(b),a=$CLJS.Az($CLJS.Az(a,[$CLJS.ih(b)," "].join(""),c),$CLJS.ih(b),c));return a};
var C4=new $CLJS.M(null,"number-formatter","number-formatter",929788393),D4=new $CLJS.M(null,"scale","scale",-230427353),E4=new $CLJS.M(null,"negative-in-parentheses","negative-in-parentheses",-1676084141),Zra=new $CLJS.M(null,"scientific","scientific",316285837);var F4=new $CLJS.h(null,1,[$CLJS.t4,"symbol"],null),$ra=$CLJS.Bk(F4),Xra=new $CLJS.Q(null,4,5,$CLJS.R,[new $CLJS.Q(null,2,5,$CLJS.R,[1E12,"T"],null),new $CLJS.Q(null,2,5,$CLJS.R,[1E9,"B"],null),new $CLJS.Q(null,2,5,$CLJS.R,[1E6,"M"],null),new $CLJS.Q(null,2,5,$CLJS.R,[1E3,"k"],null)],null),G4=function(){var a=$CLJS.Ze($CLJS.N),b=$CLJS.Ze($CLJS.N),c=$CLJS.Ze($CLJS.N),d=$CLJS.Ze($CLJS.N),e=$CLJS.J.j($CLJS.N,$CLJS.Jk,$CLJS.Xh.o?$CLJS.Xh.o():$CLJS.Xh.call(null));return new $CLJS.fi($CLJS.Hh.g("metabase.shared.formatting.numbers",
"format-number-compact*"),function(f,k){f=$CLJS.O(k);return $CLJS.J.g(f,$CLJS.p4)},e,a,b,c,d)}();G4.m(null,$CLJS.ei,function(a,b){return B4(a,b)});G4.m(null,"percent",function(a,b){return[$CLJS.p.h(B4(100*a,b)),"%"].join("")});G4.m(null,"currency",function(a,b){b=$CLJS.zk.l($CLJS.H([b,F4]));var c=y4(b);return 1E3>$CLJS.tz(a)?c.Ne(null,a):Wra(c,B4(a,b))});G4.m(null,"scientific",function(a,b){return z4(a,$CLJS.zk.l($CLJS.H([b,new $CLJS.h(null,2,[$CLJS.q4,1,$CLJS.n4,1],null)])))});
$CLJS.A4=function A4(a,b){b=$CLJS.$z(b);var d=$CLJS.O(b);b=$CLJS.J.g(d,$CLJS.uA);var e=$CLJS.J.g(d,E4),f=$CLJS.J.g(d,$CLJS.p4),k=$CLJS.J.g(d,D4);return $CLJS.n($CLJS.n(k)?!isNaN(k):k)?(b=k*a,f=$CLJS.ak.g(d,D4),A4.g?A4.g(b,f):A4.call(null,b,f)):$CLJS.n(function(){var l=0>a;return l?e:l}())?["(",$CLJS.p.h(function(){var l=-a,m=$CLJS.T.j(d,E4,!1);return A4.g?A4.g(l,m):A4.call(null,l,m)}()),")"].join(""):$CLJS.n(b)?G4.g(a,v4($CLJS.ak.g(d,$CLJS.uA))):$CLJS.E.g($CLJS.Bh.h(f),Zra)?z4(a,d):Yra(a,d)};
module.exports={compact_currency_options_js:$ra,format_number:$CLJS.A4};