var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./clojure.string.js");require("./metabase.lib.schema.common.js");require("./metabase.mbql.predicates.js");require("./metabase.mbql.schema.js");require("./metabase.mbql.schema.helpers.js");require("./metabase.mbql.util.match.js");require("./metabase.shared.util.i18n.js");require("./metabase.util.log.js");require("./metabase.util.malli.js");
'use strict';var vU;$CLJS.qU=function(a){return a instanceof Error?a.message:null};
$CLJS.rU=function(a,b,c){if($CLJS.be(c)){var d=$CLJS.P.g($CLJS.V,$CLJS.kf.g(a,c));return b.h?b.h(d):b.call(null,d)}return $CLJS.Bf(c)?(d=new $CLJS.$f(function(){var e=$CLJS.Fb(c);return a.h?a.h(e):a.call(null,e)}(),function(){var e=$CLJS.Gb(c);return a.h?a.h(e):a.call(null,e)}()),b.h?b.h(d):b.call(null,d)):$CLJS.Ed(c)?(d=$CLJS.oh($CLJS.kf.g(a,c)),b.h?b.h(d):b.call(null,d)):$CLJS.zd(c)?(d=$CLJS.fb(function(e,f){return $CLJS.de.g(e,a.h?a.h(f):a.call(null,f))},c,c),b.h?b.h(d):b.call(null,d)):$CLJS.vd(c)?
(d=$CLJS.gg.g($CLJS.kd(c),$CLJS.kf.g(a,c)),b.h?b.h(d):b.call(null,d)):b.h?b.h(c):b.call(null,c)};$CLJS.tU=function(a){function b(c){var d=$CLJS.I(c,0,null);c=$CLJS.I(c,1,null);return"string"===typeof d?new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Bh.h(d),c],null):new $CLJS.Q(null,2,5,$CLJS.R,[d,c],null)}return $CLJS.sU(function(c){return $CLJS.yd(c)?$CLJS.gg.g($CLJS.N,$CLJS.kf.g(b,c)):c},a)};
$CLJS.uU=function(a){var b=new $CLJS.Fa;for(a=$CLJS.y(a);;)if(null!=a)b=b.append($CLJS.p.h($CLJS.z(a))),a=$CLJS.B(a);else return b.toString()};$CLJS.wU=function(a,b,c){a=$CLJS.Az(a,/''/,"'");var d=$CLJS.Ms(a,vU);d=$CLJS.E.g($CLJS.D(d),1)?new $CLJS.Q(null,2,5,$CLJS.R,[a,""],null):d;a=$CLJS.qh(/.*\{0\}.*/,a);return $CLJS.Fs.ngettext($CLJS.Fs.msgid($CLJS.Bk(d),$CLJS.n(a)?c:""),$CLJS.Az($CLJS.Az(b,/''/,"'"),vU,$CLJS.p.h(c)),c)};
$CLJS.xU=function(a,b){return $CLJS.fb(function(c,d){var e=$CLJS.I(d,0,null);d=$CLJS.I(d,1,null);return $CLJS.Jd(a,e)?$CLJS.T.j(c,d,$CLJS.J.g(a,e)):c},$CLJS.P.j($CLJS.ak,a,$CLJS.Zg(b)),b)};$CLJS.yU=function(a,b,c){return $CLJS.yd(c)?$CLJS.lf(function(d){var e=$CLJS.I(d,0,null);d=$CLJS.I(d,1,null);e=$CLJS.de.g(b,e);return a.g?a.g(e,d):a.call(null,e,d)},$CLJS.H([c])):$CLJS.xd(c)?$CLJS.lf($CLJS.Xe(a,$CLJS.z(c)instanceof $CLJS.M?$CLJS.de.g(b,$CLJS.z(c)):b),$CLJS.H([c])):null};
$CLJS.sU=function sU(a,b){return $CLJS.rU($CLJS.Xe(sU,a),a,b)};vU=/\{0\}/;$CLJS.zU=new $CLJS.M(null,"unique-alias-fn","unique-alias-fn",32555420);$CLJS.AU=new $CLJS.M(null,"binning-strategy","binning-strategy",2063329158);$CLJS.BU=new $CLJS.M("clojure.core.match","not-found","clojure.core.match/not-found",1553053780);$CLJS.CU=new $CLJS.M(null,"name-key-fn","name-key-fn",-1634839199);var $la=$CLJS.Kg([new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.jI,null],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.UH,null],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.WA,$CLJS.YH],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.WA,null],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.hI,null],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.cI,null],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.eI,null],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.NH,null],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.fI,null],null),new $CLJS.Q(null,2,5,
$CLJS.R,[$CLJS.WA,$CLJS.RH],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.WA,$CLJS.bI],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.TH,null],null)],[$CLJS.Gk,$CLJS.YF,$CLJS.kI,$CLJS.XH,$CLJS.Fk,$CLJS.Lk,$CLJS.Kk,$CLJS.Ok,$CLJS.Hk,$CLJS.XH,$CLJS.lI,$CLJS.VF]),EU;$CLJS.hh($CLJS.kf.g($CLJS.z,$CLJS.Zg($la)));var DU,ama=$CLJS.Ze($CLJS.N),bma=$CLJS.Ze($CLJS.N),cma=$CLJS.Ze($CLJS.N),dma=$CLJS.Ze($CLJS.N),ema=$CLJS.J.j($CLJS.N,$CLJS.Jk,$CLJS.Xh.o?$CLJS.Xh.o():$CLJS.Xh.call(null));
DU=new $CLJS.fi($CLJS.Hh.g("metabase.mbql.util","negate*"),$CLJS.z,ema,ama,bma,cma,dma);DU.m(null,$CLJS.hr,function(a){$CLJS.I(a,0,null);return $CLJS.I(a,1,null)});DU.m(null,$CLJS.mr,function(a){a=$CLJS.y(a);$CLJS.z(a);a=$CLJS.B(a);return $CLJS.gg.g(new $CLJS.Q(null,1,5,$CLJS.R,[$CLJS.fr],null),$CLJS.kf.g(DU,a))});DU.m(null,$CLJS.fr,function(a){a=$CLJS.y(a);$CLJS.z(a);a=$CLJS.B(a);return $CLJS.gg.g(new $CLJS.Q(null,1,5,$CLJS.R,[$CLJS.mr],null),$CLJS.kf.g(DU,a))});
DU.m(null,$CLJS.Nj,function(a){$CLJS.I(a,0,null);var b=$CLJS.I(a,1,null);a=$CLJS.I(a,2,null);return new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.BF,b,a],null)});DU.m(null,$CLJS.BF,function(a){$CLJS.I(a,0,null);var b=$CLJS.I(a,1,null);a=$CLJS.I(a,2,null);return new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Nj,b,a],null)});DU.m(null,$CLJS.Cq,function(a){$CLJS.I(a,0,null);var b=$CLJS.I(a,1,null);a=$CLJS.I(a,2,null);return new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Iq,b,a],null)});
DU.m(null,$CLJS.Gq,function(a){$CLJS.I(a,0,null);var b=$CLJS.I(a,1,null);a=$CLJS.I(a,2,null);return new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Eq,b,a],null)});DU.m(null,$CLJS.Eq,function(a){$CLJS.I(a,0,null);var b=$CLJS.I(a,1,null);a=$CLJS.I(a,2,null);return new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Gq,b,a],null)});DU.m(null,$CLJS.Iq,function(a){$CLJS.I(a,0,null);var b=$CLJS.I(a,1,null);a=$CLJS.I(a,2,null);return new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Cq,b,a],null)});
DU.m(null,$CLJS.NE,function(a){$CLJS.I(a,0,null);var b=$CLJS.I(a,1,null),c=$CLJS.I(a,2,null);a=$CLJS.I(a,3,null);return new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.fr,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Gq,b,c],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Cq,b,a],null)],null)});DU.m(null,$CLJS.kF,function(a){return new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.hr,a],null)});DU.m(null,$CLJS.cF,function(a){return new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.hr,a],null)});
DU.m(null,$CLJS.wF,function(a){return new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.hr,a],null)});
EU=function EU(a){return $CLJS.yd(a)?$CLJS.Ie($CLJS.gg.g($CLJS.N,function(){return function e(d){return new $CLJS.pe(null,function(){for(var f=d;;)if(f=$CLJS.y(f)){if($CLJS.Bd(f)){var k=$CLJS.mc(f),l=$CLJS.D(k),m=$CLJS.se(l);a:for(var t=0;;)if(t<l){var u=$CLJS.ld(k,t),v=$CLJS.I(u,0,null);u=$CLJS.I(u,1,null);u=EU.h?EU.h(u):EU.call(null,u);null!=u&&m.add(new $CLJS.Q(null,2,5,$CLJS.R,[v,u],null));t+=1}else{k=!0;break a}return k?$CLJS.ve($CLJS.xe(m),e($CLJS.nc(f))):$CLJS.ve($CLJS.xe(m),null)}k=$CLJS.z(f);
m=$CLJS.I(k,0,null);k=$CLJS.I(k,1,null);k=EU.h?EU.h(k):EU.call(null,k);if(null!=k)return $CLJS.ge(new $CLJS.Q(null,2,5,$CLJS.R,[m,k],null),e($CLJS.Mc(f)));f=$CLJS.Mc(f)}else return null},null,null)}(a)}())):$CLJS.xd(a)?$CLJS.Ie($CLJS.gg.g($CLJS.kd(a),$CLJS.nf($CLJS.Ya,$CLJS.kf.g(EU,a)))):a};
$CLJS.FU=function(){function a(c,d,e){var f=null;if(2<arguments.length){f=0;for(var k=Array(arguments.length-2);f<k.length;)k[f]=arguments[f+2],++f;f=new $CLJS.w(k,0,null)}return b.call(this,c,d,f)}function b(c,d,e){var f=$CLJS.I(c,0,null),k=$CLJS.I(c,1,null);c=$CLJS.I(c,2,null);d=$CLJS.Ie(EU($CLJS.P.j(d,c,e)));return $CLJS.n(d)?new $CLJS.Q(null,3,5,$CLJS.R,[f,k,d],null):$CLJS.E.g(f,$CLJS.lF)?new $CLJS.Q(null,3,5,$CLJS.R,[f,k,null],null):new $CLJS.Q(null,2,5,$CLJS.R,[f,k],null)}a.A=2;a.B=function(c){var d=
$CLJS.z(c);c=$CLJS.B(c);var e=$CLJS.z(c);c=$CLJS.Mc(c);return b(d,e,c)};a.l=b;return a}();