var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./metabase.lib.convert.js");require("./metabase.lib.metadata.js");require("./metabase.lib.metadata.calculation.js");require("./metabase.lib.query.js");require("./metabase.lib.schema.common.js");require("./metabase.lib.schema.id.js");require("./metabase.lib.schema.metadata.js");require("./metabase.lib.util.js");require("./metabase.shared.util.i18n.js");require("./metabase.util.js");require("./metabase.util.humanization.js");require("./metabase.util.malli.js");
'use strict';$CLJS.Y0=function(a,b){var c=$CLJS.EV(b);return $CLJS.n(c)?$CLJS.$Z(a,c):$CLJS.YZ(a,b)};$CLJS.Z0=function(a){var b=$CLJS.SA(a);b=b instanceof $CLJS.M?b.S:null;switch(b){case "dispatch-type/nil":return null;case "field":return $CLJS.rO.h($CLJS.HD(a));case "metadata/column":return $CLJS.$Y.h(a);case "mbql/join":return $CLJS.XD.h(a);default:throw Error(["No matching clause: ",$CLJS.p.h(b)].join(""));}};
$CLJS.$0=function(a,b){return $CLJS.ia.j?$CLJS.ia.j("%s__%s",a,b):$CLJS.ia.call(null,"%s__%s",a,b)};$CLJS.a1=function(a,b){var c=$CLJS.Z0(b);if($CLJS.n(c))a=c;else a:{var d=$CLJS.O(b);c=$CLJS.J.g(d,$CLJS.WJ);d=$CLJS.J.g(d,$CLJS.XJ);if($CLJS.n($CLJS.n(c)?d:c)&&(d=$CLJS.Y0(a,d),$CLJS.n(d))){d=$CLJS.U.h(d);a=$CLJS.U.h($CLJS.Q0(a,c));a=$CLJS.ia.j?$CLJS.ia.j("%s__via__%s",d,a):$CLJS.ia.call(null,"%s__via__%s",d,a);break a}a=null}return $CLJS.n(a)?$CLJS.$0(a,$CLJS.U.h(b)):$CLJS.U.h(b)};
$CLJS.b1=function(a,b,c,d){var e=$CLJS.gg.j($CLJS.dh,$CLJS.kf.h($CLJS.XJ),c);return $CLJS.gg.j($CLJS.Ef,$CLJS.hk.l($CLJS.mf($CLJS.UJ),$CLJS.kf.h(function(f){f=$CLJS.O(f);var k=$CLJS.J.g(f,$CLJS.Si),l=$CLJS.J.g(f,$CLJS.UJ);return $CLJS.T.l($CLJS.Q0(a,l),$CLJS.u_,k,$CLJS.H([$CLJS.v_,$CLJS.$Y.h(f)]))}),$CLJS.ik.h(function(f){return $CLJS.Jd(e,$CLJS.XJ.h(f))}),$CLJS.H([$CLJS.hD(function(f){f=$CLJS.O(f);var k=$CLJS.J.g(f,$CLJS.XJ),l=$CLJS.J.g(f,$CLJS.u_),m=$CLJS.J.g(f,$CLJS.v_);f=$CLJS.YZ(a,k);return function v(u){return new $CLJS.pe(null,
function(){for(;;){var x=$CLJS.y(u);if(x){if($CLJS.Bd(x)){var A=$CLJS.mc(x),C=$CLJS.D(A),G=$CLJS.se(C);return function(){for(var X=0;;)if(X<C){var ba=$CLJS.ld(A,X),ha=$CLJS.T.l(ba,$CLJS.WJ,l,$CLJS.H([$CLJS.r_,m,$CLJS.IJ,$CLJS.GY,$CLJS.vY,$CLJS.U.h(ba)]));ba=G;var ua=$CLJS.T,Ua=ua.j,Db=ha;ha=$CLJS.a1(a,ha);ha=d.h?d.h(ha):d.call(null,ha);ua=Ua.call(ua,Db,$CLJS.KY,ha);ba.add(ua);X+=1}else return!0}()?$CLJS.ve($CLJS.xe(G),v($CLJS.nc(x))):$CLJS.ve($CLJS.xe(G),null)}var K=$CLJS.z(x),S=$CLJS.T.l(K,$CLJS.WJ,
l,$CLJS.H([$CLJS.r_,m,$CLJS.IJ,$CLJS.GY,$CLJS.vY,$CLJS.U.h(K)]));return $CLJS.ge($CLJS.T.j(S,$CLJS.KY,function(){var X=$CLJS.a1(a,S);return d.h?d.h(X):d.call(null,X)}()),v($CLJS.Mc(x)))}return null}},null,null)}($CLJS.O_.v(a,b,f,new $CLJS.h(null,2,[$CLJS.z_,d,$CLJS.t_,!1],null)))})])),c)};$CLJS.c1=function(a,b){return $CLJS.T0.g(a,b)};$CLJS.d1=function(a){return $CLJS.iD("Question {0}",$CLJS.H([$CLJS.Oh.l($CLJS.H([a]))]))};
$CLJS.e1=function(a,b){var c=$CLJS.TD.h(b);$CLJS.n(c)||(c=$CLJS.QY.h(b),$CLJS.n(c)||(c=$CLJS.PY.h(b),c=null!=c?$CLJS.N_.h($CLJS.c1(a,$CLJS.XX.h(c))):null));return $CLJS.n(c)?(c=$CLJS.Ie($CLJS.yd(c)?$CLJS.AV.h(c):$CLJS.xd(c)?c:null),$CLJS.n(c)?$CLJS.jk.g($CLJS.Ws(xpa,a,b),c):null):null};$CLJS.f1=new $CLJS.M("metabase.lib.card","force-broken-id-refs","metabase.lib.card/force-broken-id-refs",-868945458);$CLJS.g1=new $CLJS.M(null,"field-ref","field-ref",-1699303428);$CLJS.E_.m(null,$CLJS.fK,function(a,b,c){return $CLJS.uz($CLJS.nD,$CLJS.U)(c)});$CLJS.K_.m(null,$CLJS.fK,function(a,b,c){a=$CLJS.O(c);b=$CLJS.J.g(a,$CLJS.U);c=$CLJS.J.g(a,$CLJS.nD);return $CLJS.Wa(c)?$CLJS.T.j(a,$CLJS.nD,$CLJS.X0.g($CLJS.W0,b)):a});
$CLJS.O_.m(null,$CLJS.fK,function(a,b,c,d){c=$CLJS.O(c);var e=$CLJS.J.g(c,$CLJS.TD),f=$CLJS.J.g(c,$CLJS.QY);d=$CLJS.O(d);var k=$CLJS.J.g(d,$CLJS.t_),l=$CLJS.J.g(d,$CLJS.z_);return $CLJS.jf.g($CLJS.N_.v(a,b,c,d),$CLJS.n(k)?$CLJS.b1(a,b,$CLJS.jf.g(e,f),l):null)});$CLJS.H_.m(null,$CLJS.MU,function(a,b){var c=$CLJS.DV(a,b);c=$CLJS.O(c);c=$CLJS.J.g(c,$CLJS.MU);if($CLJS.n(c)){var d=$CLJS.$Z(a,c);a=$CLJS.n(d)?$CLJS.e_.v(a,b,d,$CLJS.f_):null;return $CLJS.n(a)?a:$CLJS.d1(c)}return null});
var xpa=function(){function a(d,e,f){var k=$CLJS.ak.g($CLJS.yz(f,$CLJS.Zz),$CLJS.g1);return $CLJS.zk.l($CLJS.H([new $CLJS.h(null,2,[$CLJS.nA,$CLJS.lj,$CLJS.Us,$CLJS.GJ],null),function(){var l=$CLJS.Si.h(k);if($CLJS.n(l))try{return $CLJS.Q0(d,l)}catch(m){return null}else return null}(),k,new $CLJS.h(null,3,[$CLJS.Us,$CLJS.GJ,$CLJS.IJ,$CLJS.NY,$CLJS.vY,$CLJS.uz($CLJS.vY,$CLJS.U)(k)],null),$CLJS.n(e)?new $CLJS.h(null,1,[$CLJS.XY,$CLJS.M0(e)],null):null,$CLJS.n($CLJS.n(!0)?$CLJS.Wa(e)||$CLJS.Wa($CLJS.CY.h($CLJS.$Z(d,
$CLJS.M0(e)))):!0)?new $CLJS.h(null,1,[$CLJS.f1,!0],null):null]))}function b(d,e){return c.j?c.j(d,null,e):c.call(null,d,null,e)}var c=null;c=function(d,e,f){switch(arguments.length){case 2:return b.call(this,d,e);case 3:return a.call(this,d,e,f)}throw Error("Invalid arity: "+arguments.length);};c.g=b;c.j=a;return c}();
$CLJS.M_.m(null,$CLJS.fK,function(a,b,c,d){b=$CLJS.O(d);var e=$CLJS.J.g(b,$CLJS.z_);return $CLJS.jk.g(function(f){var k=$CLJS.lB($CLJS.KY,$CLJS.vY,$CLJS.U)(f);return $CLJS.T.j(f,$CLJS.KY,e.h?e.h(k):e.call(null,k))},$CLJS.e1(a,c))});