var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./metabase.lib.schema.aggregation.js");require("./metabase.lib.schema.common.js");require("./metabase.lib.schema.expression.js");require("./metabase.lib.schema.expression.arithmetic.js");require("./metabase.lib.schema.expression.conditional.js");require("./metabase.lib.schema.expression.string.js");require("./metabase.lib.schema.expression.temporal.js");require("./metabase.lib.schema.filter.js");require("./metabase.lib.schema.id.js");require("./metabase.lib.schema.join.js");require("./metabase.lib.schema.literal.js");require("./metabase.lib.schema.order_by.js");require("./metabase.lib.schema.ref.js");require("./metabase.lib.schema.template_tag.js");require("./metabase.lib.schema.util.js");require("./metabase.mbql.util.js");require("./metabase.mbql.util.match.js");require("./metabase.util.malli.registry.js");
'use strict';var GU,IU,JU,fma,NU,OU,PU,hma,QU,RU,SU,UU,VU,WU,XU,YU,ZU,aV,bV,cV,dV,eV,hV,iV,gma;GU=function(a){return $CLJS.gg.j($CLJS.N,$CLJS.ik.h(function(b){var c=$CLJS.I(b,0,null);$CLJS.I(b,1,null);return $CLJS.oe(c)}),a)};
$CLJS.HU=function(a){var b=2>$CLJS.D(a);return b?b:$CLJS.P.g($CLJS.tB,function(){return function e(d){return new $CLJS.pe(null,function(){for(;;){var f=$CLJS.y(d);if(f){var k=f;if($CLJS.Bd(k)){var l=$CLJS.mc(k),m=$CLJS.D(l),t=$CLJS.se(m);return function(){for(var v=0;;)if(v<m){var x=$CLJS.ld(l,v);$CLJS.we(t,$CLJS.JD(x,function(){return function(A){return $CLJS.ak.l(GU(A),$CLJS.nA,$CLJS.H([$CLJS.Ci]))}}(v,x,l,m,t,k,f,b)));v+=1}else return!0}()?$CLJS.ve($CLJS.xe(t),e($CLJS.nc(k))):$CLJS.ve($CLJS.xe(t),
null)}var u=$CLJS.z(k);return $CLJS.ge($CLJS.JD(u,function(){return function(v){return $CLJS.ak.l(GU(v),$CLJS.nA,$CLJS.H([$CLJS.Ci]))}}(u,k,f,b)),e($CLJS.Mc(k)))}return null}},null,null)}(a)}())};
IU=function(a,b){a=new $CLJS.Q(null,1,5,$CLJS.R,[new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Ef,a],null)],null);for(var c=$CLJS.Ef;;){var d=$CLJS.rd(a);if($CLJS.n(d)){var e=d,f=$CLJS.I(e,0,null),k=$CLJS.I(e,1,null),l=e,m=$CLJS.td(a);a=function(t,u,v,x,A,C,G,K){return function(S){return $CLJS.gg.j(v,$CLJS.kf.h(function(X,ba,ha,ua,Ua){return function(Db){var Qa=$CLJS.I(Db,0,null);Db=$CLJS.I(Db,1,null);return new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.de.g(Ua,Qa),Db],null)}}(t,u,v,x,A,C,G,K)),S)}}(a,c,m,e,f,k,l,d);
$CLJS.n(b.h?b.h(k):b.call(null,k))?(a=m,c=$CLJS.de.g(c,l)):a=$CLJS.yd(k)?a(k):$CLJS.xd(k)?a($CLJS.Gl($CLJS.zr,k)):m}else return c}};JU=function(a,b,c){return $CLJS.Ad(c)&&$CLJS.E.g(a,$CLJS.z(c))&&!$CLJS.Jd(b,$CLJS.J.g(c,2))};$CLJS.KU=function(a){var b=$CLJS.gg.j($CLJS.dh,$CLJS.kf.h($CLJS.hk.g($CLJS.rD,$CLJS.id)),$CLJS.XO.h(a));return IU($CLJS.ak.l(a,$CLJS.BM,$CLJS.H([$CLJS.lU])),function(c){return JU($CLJS.kA,b,c)})};
$CLJS.LU=function(a){var b=$CLJS.gg.j($CLJS.dh,$CLJS.kf.h($CLJS.hk.g($CLJS.AD,$CLJS.id)),$CLJS.aF.h(a));return IU($CLJS.ak.l(a,$CLJS.BM,$CLJS.H([$CLJS.lU])),function(c){return JU($CLJS.aF,b,c)})};fma=function(a){function b(d){return $CLJS.lf(c,$CLJS.H([$CLJS.BM.h(d)]))}function c(d){return $CLJS.ge($CLJS.XD.h(d),$CLJS.lf(b,$CLJS.H([$CLJS.oK.h(d)])))}return $CLJS.n($CLJS.MU.h(a))?$CLJS.We(!0):$CLJS.hh(b(a))};
NU=function(a){if($CLJS.xd(a))for(var b=$CLJS.We(!1),c=$CLJS.y(a),d=$CLJS.z(c),e=$CLJS.B(c),f=b,k=0,l=a;;){var m=f,t=k,u=l,v=$CLJS.y(u),x=$CLJS.z(v),A=$CLJS.B(v),C=x,G=A,K=$CLJS.uz(m,fma(C));f=$CLJS.z($CLJS.y($CLJS.nf($CLJS.Ya,function(S,X,ba,ha,ua,Ua){return function hb(Qa,Xa){try{if($CLJS.Ad(Xa)&&3===$CLJS.D(Xa))try{var Ma=$CLJS.F(Xa,0);if($CLJS.je(Ma,$CLJS.lF))try{var ob=$CLJS.F(Xa,1);if($CLJS.n($CLJS.rO.h(ob)))try{var Ja=$CLJS.F(Xa,1);if(null!=Ja?Ja.C&256||$CLJS.Cc===Ja.lf||(Ja.C?0:$CLJS.ab($CLJS.xb,
Ja)):$CLJS.ab($CLJS.xb,Ja))try{var fc=$CLJS.J.j(Ja,$CLJS.rO,$CLJS.BU);if($CLJS.n($CLJS.Ve(ha)(fc))){var $d=$CLJS.J.g(Ja,$CLJS.rO);$CLJS.F(Xa,2);return new $CLJS.Q(null,1,5,$CLJS.R,[["Invalid :field reference in stage ",$CLJS.p.h(Ua),": no join named ",$CLJS.Oh.l($CLJS.H([$d]))].join("")],null)}throw $CLJS.Z;}catch(sd){if(sd instanceof Error){var Id=sd;if(Id===$CLJS.Z)throw $CLJS.Z;throw Id;}throw sd;}else throw $CLJS.Z;}catch(sd){if(sd instanceof Error){Id=sd;if(Id===$CLJS.Z)throw $CLJS.Z;throw Id;
}throw sd;}else throw $CLJS.Z;}catch(sd){if(sd instanceof Error){Id=sd;if(Id===$CLJS.Z)throw $CLJS.Z;throw Id;}throw sd;}else throw $CLJS.Z;}catch(sd){if(sd instanceof Error){Id=sd;if(Id===$CLJS.Z)throw $CLJS.Z;throw Id;}throw sd;}else throw $CLJS.Z;}catch(sd){if(sd instanceof Error){Id=sd;if(Id===$CLJS.Z)return $CLJS.yU(hb,Qa,Xa);throw Id;}throw sd;}}}(f,k,l,K,m,t,u,v,x,A,C,G,b,0,a,a,c,d,e,d,e)($CLJS.Ef,$CLJS.ak.l(C,$CLJS.BM,$CLJS.H([gma]))))));if($CLJS.n(f))return f;if($CLJS.y(G))k=t+1,f=K,l=G;
else return null}else return null};OU=new $CLJS.M("metabase.lib.schema","breakouts","metabase.lib.schema/breakouts",1354104361);PU=new $CLJS.r("metabase.lib.schema.util","distinct-refs?","metabase.lib.schema.util/distinct-refs?",-262561159,null);hma=new $CLJS.M("metabase.lib.schema","stage","metabase.lib.schema/stage",1626908550);QU=new $CLJS.r(null,"distinct-refs?","distinct-refs?",-2065255505,null);
RU=new $CLJS.M("metabase.lib.schema","stage.mbql.with-source-table","metabase.lib.schema/stage.mbql.with-source-table",-2119049176);SU=new $CLJS.M("metabase.lib.schema","stage.mbql.with-source-card","metabase.lib.schema/stage.mbql.with-source-card",-1292215799);$CLJS.TU=new $CLJS.M("mbql.stage","mbql","mbql.stage/mbql",1578747798);UU=new $CLJS.M("metabase.lib.schema","stage.additional","metabase.lib.schema/stage.additional",1347605157);
VU=new $CLJS.M("metabase.lib.schema","stage.mbql.with-source","metabase.lib.schema/stage.mbql.with-source",1947556064);WU=new $CLJS.r(null,"refs","refs",80480079,null);XU=new $CLJS.M("metabase.lib.schema","stage.native","metabase.lib.schema/stage.native",-1206212320);YU=new $CLJS.M("metabase.lib.schema","stage.mbql.without-source","metabase.lib.schema/stage.mbql.without-source",1507072886);ZU=new $CLJS.M("metabase.lib.schema","stage.type","metabase.lib.schema/stage.type",1362996639);
$CLJS.$U=new $CLJS.M("mbql.stage","native","mbql.stage/native",359422194);aV=new $CLJS.M("metabase.lib.schema","filters","metabase.lib.schema/filters",889389881);bV=new $CLJS.M("metabase.lib.schema","breakout","metabase.lib.schema/breakout",-921298600);cV=new $CLJS.M("metabase.lib.schema","fields","metabase.lib.schema/fields",-2010307316);dV=new $CLJS.M("metabase.lib.schema","filterable","metabase.lib.schema/filterable",-1640076631);
eV=new $CLJS.M("metabase.lib.schema","stage.valid-refs","metabase.lib.schema/stage.valid-refs",-383625241);$CLJS.fV=new $CLJS.M("mbql","query","mbql/query",-1285688662);$CLJS.MU=new $CLJS.M(null,"source-card","source-card",-1580820390);$CLJS.gV=new $CLJS.M(null,"filters","filters",974726919);hV=new $CLJS.M("metabase.lib.schema","stages.valid-refs","metabase.lib.schema/stages.valid-refs",-193458245);iV=new $CLJS.M("metabase.lib.schema","stage.initial","metabase.lib.schema/stage.initial",-1483255395);
$CLJS.jV=new $CLJS.M("metabase.lib.schema","stage.mbql","metabase.lib.schema/stage.mbql",1051351388);gma=new $CLJS.M("stage","metadata","stage/metadata",1707239131);$CLJS.Y(XU,new $CLJS.Q(null,6,5,$CLJS.R,[$CLJS.Gj,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Us,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Nj,$CLJS.$U],null)],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.gP,$CLJS.Ya],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Kr,new $CLJS.h(null,1,[$CLJS.Ar,!0],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.kj,$CLJS.fl],null)],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.jN,new $CLJS.h(null,1,[$CLJS.Ar,!0],null),$CLJS.sD],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.DP,new $CLJS.h(null,1,[$CLJS.Ar,
!0],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.dU],null)],null)],null));$CLJS.Y(bV,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.pF],null));
$CLJS.Y(OU,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.mr,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.kj,new $CLJS.h(null,1,[$CLJS.ln,1],null),bV],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Mi,new $CLJS.h(null,1,[$CLJS.ss,"Breakouts must be distinct"],null),new $CLJS.Hc(function(){return $CLJS.HU},PU,$CLJS.Kg([$CLJS.Pi,$CLJS.U,$CLJS.Lj,$CLJS.vi,$CLJS.Ni,$CLJS.bj,$CLJS.Rj,$CLJS.ui,$CLJS.Ij,$CLJS.Kj],[$CLJS.pU,QU,"metabase/lib/schema/util.cljc",21,1,64,64,$CLJS.V(new $CLJS.Q(null,1,5,$CLJS.R,[WU],null)),"Is a sequence of `refs` distinct for the purposes of appearing in `:fields` or `:breakouts` (ignoring keys that\n  aren't important such as namespaced keys and type info)?",
$CLJS.n($CLJS.HU)?$CLJS.HU.H:null]))],null)],null));
$CLJS.Y(cV,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.mr,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.kj,new $CLJS.h(null,1,[$CLJS.ln,1],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.pF],null)],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Mi,new $CLJS.h(null,1,[$CLJS.ss,":fields must be distinct"],null),new $CLJS.Hc(function(){return $CLJS.HU},PU,$CLJS.Kg([$CLJS.Pi,$CLJS.U,$CLJS.Lj,$CLJS.vi,$CLJS.Ni,$CLJS.bj,$CLJS.Rj,$CLJS.ui,$CLJS.Ij,$CLJS.Kj],[$CLJS.pU,QU,"metabase/lib/schema/util.cljc",21,1,64,64,$CLJS.V(new $CLJS.Q(null,
1,5,$CLJS.R,[WU],null)),"Is a sequence of `refs` distinct for the purposes of appearing in `:fields` or `:breakouts` (ignoring keys that\n  aren't important such as namespaced keys and type info)?",$CLJS.n($CLJS.HU)?$CLJS.HU.H:null]))],null)],null));$CLJS.Y(dV,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.fr,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.YD],null),new $CLJS.Q(null,4,5,$CLJS.R,[$CLJS.ir,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Nj,$CLJS.JE],null),$CLJS.Gj,$CLJS.Bj],null)],null));
$CLJS.Y(aV,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.kj,new $CLJS.h(null,1,[$CLJS.ln,1],null),dV],null));
var kV=$CLJS.uz(function(a){a=$CLJS.z($CLJS.KU(a));if($CLJS.n(a)){var b=$CLJS.wz(a,new $CLJS.Q(null,2,5,$CLJS.R,[1,2],null));return $CLJS.n(b)?["Invalid :expression reference: no expression named ",$CLJS.Oh.l($CLJS.H([b]))].join(""):["Invalid :expression reference: ",$CLJS.p.h($CLJS.J.g(a,1))].join("")}return null},function(a){a=$CLJS.z($CLJS.LU(a));if($CLJS.n(a)){var b=$CLJS.wz(a,new $CLJS.Q(null,2,5,$CLJS.R,[1,2],null));return $CLJS.n(b)?["Invalid :aggregation reference: no aggregation with uuid ",
$CLJS.p.h(b)].join(""):["Invalid :aggregation reference: ",$CLJS.p.h($CLJS.J.g(a,1))].join("")}return null});$CLJS.Y(eV,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Mi,new $CLJS.h(null,2,[$CLJS.ss,"Valid references for a single query stage",$CLJS.Ds,function(a){a=$CLJS.O(a);a=$CLJS.J.g(a,$CLJS.nj);return kV(a)}],null),$CLJS.Ve(kV)],null));
$CLJS.Y($CLJS.jV,new $CLJS.Q(null,5,5,$CLJS.R,[$CLJS.mr,new $CLJS.Q(null,11,5,$CLJS.R,[$CLJS.Gj,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Us,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Nj,$CLJS.TU],null)],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.BM,new $CLJS.h(null,1,[$CLJS.Ar,!0],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.mK],null)],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.XO,new $CLJS.h(null,1,[$CLJS.Ar,!0],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.VD],null)],null),new $CLJS.Q(null,3,5,$CLJS.R,
[$CLJS.$E,new $CLJS.h(null,1,[$CLJS.Ar,!0],null),OU],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.aF,new $CLJS.h(null,1,[$CLJS.Ar,!0],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.MF],null)],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.TD,new $CLJS.h(null,1,[$CLJS.Ar,!0],null),cV],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.gV,new $CLJS.h(null,1,[$CLJS.Ar,!0],null),aV],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.LQ,new $CLJS.h(null,1,[$CLJS.Ar,!0],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.uK],null)],
null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.cO,new $CLJS.h(null,1,[$CLJS.Ar,!0],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.LJ],null)],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.MU,new $CLJS.h(null,1,[$CLJS.Ar,!0],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.SJ],null)],null)],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Mi,new $CLJS.h(null,1,[$CLJS.ss,":source-query is not allowed in pMBQL queries."],null),function(a){return!$CLJS.Jd(a,$CLJS.FP)}],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Mi,
new $CLJS.h(null,1,[$CLJS.ss,"A query cannot have both a :source-table and a :source-card."],null),$CLJS.Ve($CLJS.gD($CLJS.cO,$CLJS.MU))],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,eV],null)],null));$CLJS.Y(RU,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.rs,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.jV],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Gj,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.cO,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.LJ],null)],null)],null)],null));
$CLJS.Y(SU,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.rs,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.jV],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Gj,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.MU,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.SJ],null)],null)],null)],null));$CLJS.Y(VU,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.fr,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,RU],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,SU],null)],null));
$CLJS.Y(YU,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.mr,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.jV],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Mi,new $CLJS.h(null,1,[$CLJS.ss,"Only the initial stage of a query can have a :source-table or :source-card."],null),$CLJS.Ve($CLJS.uz($CLJS.cO,$CLJS.MU))],null)],null));$CLJS.Y(ZU,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.cr,$CLJS.$U,$CLJS.TU],null));
$CLJS.Y(hma,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.mr,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Gj,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Us,ZU],null)],null),new $CLJS.Q(null,4,5,$CLJS.R,[$CLJS.lr,new $CLJS.h(null,1,[$CLJS.Ji,$CLJS.Us],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.$U,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,XU],null)],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.TU,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.jV],null)],null)],null)],null));
$CLJS.Y(iV,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.mr,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Gj,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Us,ZU],null)],null),new $CLJS.Q(null,4,5,$CLJS.R,[$CLJS.lr,new $CLJS.h(null,1,[$CLJS.Ji,$CLJS.Us],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.$U,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,XU],null)],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.TU,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,VU],null)],null)],null)],null));$CLJS.Y(UU,YU);
$CLJS.Y(hV,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Mi,new $CLJS.h(null,2,[$CLJS.ss,"Valid references for all query stages",$CLJS.Ds,function(a){a=$CLJS.O(a);a=$CLJS.J.g(a,$CLJS.nj);return NU.h?NU.h(a):NU.call(null,a)}],null),$CLJS.Ve(NU)],null));
$CLJS.Y($CLJS.kK,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.mr,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Uq,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Uk,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,iV],null)],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Lq,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Uk,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,UU],null)],null)],null)],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,hV],null)],null));
$CLJS.Y($CLJS.IK,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.mr,new $CLJS.Q(null,4,5,$CLJS.R,[$CLJS.Gj,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Us,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Nj,$CLJS.fV],null)],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.SO,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.fr,$CLJS.TJ,$CLJS.$J],null)],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.oK,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.kK],null)],null)],null),$CLJS.Zla],null));