var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./shadow.js.shim.module$moment.js");require("./metabase.shared.util.internal.time_common.js");
'use strict';var S_,T_,U_,V_,X_;$CLJS.Q_=function(a){return $CLJS.n(a)?$CLJS.MH.isMoment(a):a};$CLJS.R_=function(a){var b=$CLJS.Q_(a);return $CLJS.n(b)?a.isValid():b};$CLJS.Hoa=new $CLJS.M(null,"offset-n","offset-n",555087298);S_=new $CLJS.M(null,"local-time","local-time",-1873195290);T_=new $CLJS.M(null,"offset-time","offset-time",1629332358);U_=new $CLJS.M(null,"local-date-time","local-date-time",-1710577246);V_=new $CLJS.M(null,"local-date","local-date",1829761428);
$CLJS.W_=new $CLJS.M(null,"formats","formats",-1397890976);$CLJS.Ioa=new $CLJS.M(null,"offset-unit","offset-unit",-352817795);X_=new $CLJS.M(null,"offset-date-time","offset-date-time",1403996582);$CLJS.nH.m(null,$CLJS.ei,function(a,b){var c=$CLJS.O(b);b=$CLJS.J.g(c,$CLJS.Mj);c=$CLJS.J.g(c,$CLJS.Ek);var d=a.clone();a=a.clone();a=1<b?a.add(b-1,$CLJS.ih(c)):a;return new $CLJS.Q(null,2,5,$CLJS.R,[d.startOf($CLJS.ih(c)),a.endOf($CLJS.ih(c))],null)});$CLJS.oH.m(null,$CLJS.ei,function(a){return $CLJS.MH.utc(a,$CLJS.MH.ISO_8601)});
$CLJS.oH.m(null,$CLJS.Hk,function(a,b){try{var c=$CLJS.kH($CLJS.oH,$CLJS.ei);var d=c.g?c.g(a,b):c.call(null,a,b)}catch(e){if(e instanceof Error)d=null;else throw e;}return $CLJS.n($CLJS.R_(d))?d:(0,$CLJS.MH)().isoWeekday(a).startOf("day")});$CLJS.pH.m(null,$CLJS.ei,function(a){return $CLJS.MH.utc(a,$CLJS.MH.ISO_8601)});$CLJS.pH.m(null,$CLJS.Kk,function(a){return(0,$CLJS.MH)().minute(a).startOf("minute")});$CLJS.pH.m(null,$CLJS.Fk,function(a){return(0,$CLJS.MH)().hour(a).startOf("hour")});
$CLJS.pH.m(null,$CLJS.Hk,function(a){return(0,$CLJS.MH)().weekday(a-1).startOf("day")});$CLJS.pH.m(null,$CLJS.Lk,function(a){return(0,$CLJS.MH)("2016-01-01").date(a).startOf("day")});$CLJS.pH.m(null,$CLJS.oj,function(a){return(0,$CLJS.MH)("2016-01-01").dayOfYear(a).startOf("day")});$CLJS.pH.m(null,$CLJS.ri,function(a){return(0,$CLJS.MH)().week(a).startOf("week")});$CLJS.pH.m(null,$CLJS.Ok,function(a){return(0,$CLJS.MH)().month(a-1).startOf("month")});$CLJS.pH.m(null,$CLJS.Gk,function(a){return(0,$CLJS.MH)().quarter(a).startOf("quarter")});
$CLJS.pH.m(null,$CLJS.li,function(a){return(0,$CLJS.MH)().year(a).startOf("year")});
$CLJS.Joa=new $CLJS.h(null,5,[X_,new $CLJS.h(null,2,[$CLJS.Mk,$CLJS.xH,$CLJS.W_,["yyyy-MM-DDTHH:mm:ss.SSS[Z]","yyyy-MM-DDTHH:mm:ss[Z]","yyyy-MM-DDTHH:mm[Z]","yyyy-MM-DDTHH[Z]"]],null),U_,new $CLJS.h(null,2,[$CLJS.Mk,$CLJS.wH,$CLJS.W_,["yyyy-MM-DDTHH:mm:ss.SSS","yyyy-MM-DDTHH:mm:ss","yyyy-MM-DDTHH:mm","yyyy-MM-DDTHH"]],null),V_,new $CLJS.h(null,2,[$CLJS.Mk,$CLJS.tH,$CLJS.W_,["yyyy-MM-DD","yyyy-MM","yyyy"]],null),T_,new $CLJS.h(null,2,[$CLJS.Mk,$CLJS.vH,$CLJS.W_,["HH:mm:ss.SSS[Z]","HH:mm:ss[Z]","HH:mm[Z]",
"HH[Z]"]],null),S_,new $CLJS.h(null,2,[$CLJS.Mk,$CLJS.uH,$CLJS.W_,["HH:mm:ss.SSS","HH:mm:ss","HH:mm","HH"]],null)],null);$CLJS.Y_=function(){var a=$CLJS.Ze($CLJS.N),b=$CLJS.Ze($CLJS.N),c=$CLJS.Ze($CLJS.N),d=$CLJS.Ze($CLJS.N),e=$CLJS.J.j($CLJS.N,$CLJS.Jk,$CLJS.Xh.o?$CLJS.Xh.o():$CLJS.Xh.call(null));return new $CLJS.fi($CLJS.Hh.g("metabase.shared.util.internal.time","moment+type-\x3eiso-8601"),function(f){$CLJS.I(f,0,null);return $CLJS.I(f,1,null)},e,a,b,c,d)}();
$CLJS.Y_.m(null,X_,function(a){var b=$CLJS.I(a,0,null);$CLJS.I(a,1,null);a=0<b.milliseconds()?"yyyy-MM-DDTHH:mm:ss.SSS[Z]":0<b.seconds()?"yyyy-MM-DDTHH:mm:ss[Z]":"yyyy-MM-DDTHH:mm[Z]";return b.format(a)});$CLJS.Y_.m(null,U_,function(a){var b=$CLJS.I(a,0,null);$CLJS.I(a,1,null);a=0<b.milliseconds()?"yyyy-MM-DDTHH:mm:ss.SSS":0<b.seconds()?"yyyy-MM-DDTHH:mm:ss":"yyyy-MM-DDTHH:mm";return b.format(a)});$CLJS.Y_.m(null,V_,function(a){var b=$CLJS.I(a,0,null);$CLJS.I(a,1,null);return b.format("yyyy-MM-DD")});
$CLJS.Y_.m(null,T_,function(a){var b=$CLJS.I(a,0,null);$CLJS.I(a,1,null);a=0<b.milliseconds()?"HH:mm:ss.SSS[Z]":0<b.seconds()?"HH:mm:ss[Z]":"HH:mm[Z]";return b.format(a)});$CLJS.Y_.m(null,S_,function(a){var b=$CLJS.I(a,0,null);$CLJS.I(a,1,null);a=0<b.milliseconds()?"HH:mm:ss.SSS":0<b.seconds()?"HH:mm:ss":"HH:mm";return b.format(a)});