var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./clojure.data.js");require("./clojure.set.js");require("./clojure.string.js");require("./malli.core.js");require("./malli.error.js");require("./medley.core.js");require("./metabase.lib.dispatch.js");require("./metabase.lib.hierarchy.js");require("./metabase.lib.options.js");require("./metabase.lib.schema.js");require("./metabase.lib.schema.expression.js");require("./metabase.lib.schema.ref.js");require("./metabase.lib.util.js");require("./metabase.mbql.normalize.js");require("./metabase.util.js");require("./metabase.util.log.js");require("./metabase.util.malli.js");
'use strict';var DX,wna,FX,xna,yna,zna,HX,Bna,Cna,Dna,Ena,JX,KX,LX,NX,Fna,OX,PX,Gna,Hna,Ina,QX,Ana,RX,SX,Jna,UX;DX=function(a,b){var c=$CLJS.y(b);for(a=$CLJS.y($CLJS.df(a,b));;)if(a)c=$CLJS.B(c),a=$CLJS.B(a);else return c};
wna=function(){return function(){function a(k,l,m){return new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.aj.j?$CLJS.aj.j(k,l,m):$CLJS.aj.call(null,k,l,m),$CLJS.Rk.j?$CLJS.Rk.j(k,l,m):$CLJS.Rk.call(null,k,l,m)],null)}function b(k,l){return new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.aj.g?$CLJS.aj.g(k,l):$CLJS.aj.call(null,k,l),$CLJS.Rk.g?$CLJS.Rk.g(k,l):$CLJS.Rk.call(null,k,l)],null)}function c(k){return new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.aj.h?$CLJS.aj.h(k):$CLJS.aj.call(null,k),$CLJS.Rk.h?$CLJS.Rk.h(k):$CLJS.Rk.call(null,
k)],null)}function d(){return new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.aj.o?$CLJS.aj.o():$CLJS.aj.call(null),$CLJS.Rk.o?$CLJS.Rk.o():$CLJS.Rk.call(null)],null)}var e=null,f=function(){function k(m,t,u,v){var x=null;if(3<arguments.length){x=0;for(var A=Array(arguments.length-3);x<A.length;)A[x]=arguments[x+3],++x;x=new $CLJS.w(A,0,null)}return l.call(this,m,t,u,x)}function l(m,t,u,v){return new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.P.M($CLJS.aj,m,t,u,v),$CLJS.P.M($CLJS.Rk,m,t,u,v)],null)}k.A=3;k.B=function(m){var t=
$CLJS.z(m);m=$CLJS.B(m);var u=$CLJS.z(m);m=$CLJS.B(m);var v=$CLJS.z(m);m=$CLJS.Mc(m);return l(t,u,v,m)};k.l=l;return k}();e=function(k,l,m,t){switch(arguments.length){case 0:return d.call(this);case 1:return c.call(this,k);case 2:return b.call(this,k,l);case 3:return a.call(this,k,l,m);default:var u=null;if(3<arguments.length){u=0;for(var v=Array(arguments.length-3);u<v.length;)v[u]=arguments[u+3],++u;u=new $CLJS.w(v,0,null)}return f.l(k,l,m,u)}throw Error("Invalid arity: "+arguments.length);};e.A=
3;e.B=f.B;e.o=d;e.h=c;e.g=b;e.j=a;e.l=f.l;return e}()};
$CLJS.EX=function(a){return function(b){var c=$CLJS.bf(-1);return function(){function d(l,m){var t=c.md(null,c.Lb(null)+1);m=a.g?a.g(t,m):a.call(null,t,m);return null==m?l:b.g?b.g(l,m):b.call(null,l,m)}function e(l){return b.h?b.h(l):b.call(null,l)}function f(){return b.o?b.o():b.call(null)}var k=null;k=function(l,m){switch(arguments.length){case 0:return f.call(this);case 1:return e.call(this,l);case 2:return d.call(this,l,m)}throw Error("Invalid arity: "+arguments.length);};k.o=f;k.h=e;k.g=d;return k}()}};
FX=function(a){return $CLJS.OK($CLJS.jV)(a,$CLJS.Ef,$CLJS.Ef)};xna=function(a,b,c){return $CLJS.fb(function(d,e){var f=$CLJS.I(e,0,null);e=$CLJS.I(e,1,null);return null==e?d:$CLJS.T.j(d,f,e)},null==b?a:$CLJS.T.j(a,$CLJS.aF,b),$CLJS.Vr(2,2,c))};yna=function(a,b){var c=$CLJS.Jl(a,$CLJS.DP);if($CLJS.n(c)){var d=$CLJS.T.j;c=$CLJS.Gb(c);b=$CLJS.fs.g?$CLJS.fs.g(c,b):$CLJS.fs.call(null,c,b);a=d.call($CLJS.T,a,$CLJS.DP,b)}return a};zna=function(a){return $CLJS.jf.g($CLJS.KU(a),$CLJS.LU(a))};
$CLJS.GX=function(a,b){return $CLJS.vV(a)&&$CLJS.E.g($CLJS.z(a),b)};HX=function(a,b,c){var d=new $CLJS.ch(null,new $CLJS.h(null,2,[$CLJS.Dr,null,$CLJS.Wk,null],null),null),e=$CLJS.n(d.h?d.h(b):d.call(null,b))?$CLJS.qt(2,c):$CLJS.qt(1,c);b=$CLJS.n(d.h?d.h(b):d.call(null,b))?DX(2,c):DX(1,c);var f=$CLJS.I(b,0,null);return $CLJS.y(e)?$CLJS.vW.j(a,e,function(k){var l=$CLJS.T.j(k,f,null);return $CLJS.Ad(k)?$CLJS.gg.j($CLJS.Ef,$CLJS.ik.h($CLJS.cl),l):$CLJS.yd(k)?$CLJS.Dz($CLJS.Ya,l):l}):$CLJS.ak.g(a,f)};
Bna=function(a){return $CLJS.fb(function(b,c){var d=$CLJS.I(c,0,null);$CLJS.I(c,1,null);return HX(b,Ana,d)},a,zna(a))};
Cna=function(a){for(var b=0;;){var c=$CLJS.F($CLJS.oK.h(a),b);a:{var d=c;for(var e=$CLJS.Ef;;){var f=$CLJS.z($CLJS.kf.g(wna(),$CLJS.nf($CLJS.hk.j(IX,$CLJS.z,$CLJS.Rk),$CLJS.Hr.h(FX(d)))));if($CLJS.n(f)){var k=f;f=$CLJS.I(k,0,null);k=$CLJS.I(k,1,null);var l=HX(d,f,k),m=$CLJS.Gz($CLJS.zx);if($CLJS.n($CLJS.Fz("metabase.lib.convert",m))){var t=$CLJS.vA.l($CLJS.H([$CLJS.uy,$CLJS.Oh.l($CLJS.H([k]))])),u=$CLJS.vA,v=u.l,x=$CLJS.Oh,A=x.l;var C=f;C=$CLJS.n(C)?C:$CLJS.TK(FX(d));$CLJS.Ez("metabase.lib.convert",
m,$CLJS.sV("Clean: Removing bad clause in %s due to error %s:\n%s",$CLJS.H([t,v.call(u,$CLJS.H([$CLJS.uy,A.call(x,$CLJS.H([C]))])),$CLJS.vA.l($CLJS.H([$CLJS.jy,$CLJS.tV($CLJS.z($CLJS.Ys(d,l)))]))])),null)}if($CLJS.E.g(l,d))break a;d=l;e=$CLJS.de.g(e,new $CLJS.Q(null,2,5,$CLJS.R,[f,k],null))}else break a}}d=Bna(d);if($CLJS.E.g(c,d)){if($CLJS.E.g(b,$CLJS.D($CLJS.oK.h(a))-1))return a;b+=1}else a=$CLJS.kk.M(a,$CLJS.oK,$CLJS.T,b,d)}};
Dna=function(a){var b=$CLJS.GV();return $CLJS.jk.g(function(c){return $CLJS.E.g($CLJS.XD.h(c),"__join")?$CLJS.kk.j(c,$CLJS.XD,b):c},a)};Ena=function(a){return"string"===typeof $CLJS.cO.h(a)?$CLJS.ak.g($CLJS.T.j(a,$CLJS.MU,$CLJS.EV($CLJS.cO.h(a))),$CLJS.cO):a};JX=function(){return $CLJS.ik.h(function(a){var b=$CLJS.I(a,0,null);$CLJS.I(a,1,null);(a=$CLJS.oe(b))?(b=$CLJS.ke(b),b=$CLJS.n(b)?$CLJS.E.g(b,"lib")||0==b.lastIndexOf("metabase.lib.",0):null):b=a;return b})};
KX=function(a){return $CLJS.gg.j($CLJS.N,JX(),a)};LX=function(a){return $CLJS.Ie($CLJS.gg.j($CLJS.N,$CLJS.hk.g(JX(),$CLJS.ik.h(function(b){var c=$CLJS.I(b,0,null);$CLJS.I(b,1,null);return $CLJS.E.g(c,$CLJS.Ci)})),a))};
NX=function(a){var b=$CLJS.y(a);a=$CLJS.z(b);var c=$CLJS.B(b);b=$CLJS.z(c);c=$CLJS.B(c);var d=$CLJS.gg.j(new $CLJS.Q(null,1,5,$CLJS.R,[a],null),$CLJS.kf.h($CLJS.MX),c);a=$CLJS.E.g(a,$CLJS.UE)&&$CLJS.B(c)?$CLJS.de.g($CLJS.td(d),new $CLJS.h(null,1,[$CLJS.ei,$CLJS.rd(d)],null)):d;b=$CLJS.Ie(LX(b));return $CLJS.n(b)?new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.sL,a,b],null):a};Fna=function(a){return $CLJS.gg.j($CLJS.Ef,$CLJS.hk.g($CLJS.kf.h(function(b){return $CLJS.yz(b,$CLJS.AA)}),$CLJS.kf.h($CLJS.MX)),$CLJS.AV.h(a))};
OX=function(a){a=$CLJS.O(a);a=$CLJS.J.g(a,$CLJS.oK);a=$CLJS.z($CLJS.fb(function(b,c){var d=$CLJS.I(b,0,null),e=$CLJS.I(b,1,null);b=$CLJS.R;var f=$CLJS.MX.h(c);d=$CLJS.n(d)?$CLJS.T.j(f,$CLJS.FP,d):f;d=$CLJS.n(e)?$CLJS.T.j(d,$CLJS.PN,Fna(e)):d;return new $CLJS.Q(null,2,5,b,[d,$CLJS.lU.h(c)],null)},null,a));return $CLJS.n($CLJS.gP.h(a))?$CLJS.xU(a,new $CLJS.h(null,1,[$CLJS.gP,$CLJS.HE],null)):a};
PX=function(a,b,c){var d=$CLJS.E.g($CLJS.D($CLJS.J.g(a,b)),1)?$CLJS.TV(a,b,$CLJS.hk.g($CLJS.MX,$CLJS.z)):a;a=1<$CLJS.D($CLJS.J.g(a,b))?$CLJS.TV(d,b,function(e){return $CLJS.gg.j(new $CLJS.Q(null,1,5,$CLJS.R,[$CLJS.mr],null),$CLJS.kf.h($CLJS.MX),e)}):d;return $CLJS.xU(a,$CLJS.He([b,c]))};Gna=function(a){var b=$CLJS.MU.h(a);return $CLJS.n(b)?$CLJS.T.j($CLJS.ak.g(a,$CLJS.MU),$CLJS.cO,["card__",$CLJS.p.h(b)].join("")):a};
Hna=new $CLJS.M(null,"legacy-index-\x3epMBQL-uuid","legacy-index-\x3epMBQL-uuid",-192973336);Ina=new $CLJS.M(null,"legacy-ref","legacy-ref",1686404700);QX=new $CLJS.M("metabase.lib.convert","not-found","metabase.lib.convert/not-found",967996550);Ana=new $CLJS.M("metabase.lib.schema","invalid-ref","metabase.lib.schema/invalid-ref",-2010445475);RX=new $CLJS.M("metabase.lib.convert","aggregation-or-expression","metabase.lib.convert/aggregation-or-expression",1924029672);
SX=new $CLJS.M("metabase.lib.convert","expression","metabase.lib.convert/expression",1648102782);$CLJS.TX=new $CLJS.M("lib.convert","converted?","lib.convert/converted?",1937433683);Jna=new $CLJS.M(null,"m","m",1632677161);UX=new $CLJS.M("metabase.lib.convert","aggregation","metabase.lib.convert/aggregation",108290790);var IX,Kna,Lna,Mna,Nna,Ona,Pna,Qna,Rna,Sna,Tna;$CLJS.VX=$CLJS.N;$CLJS.WX=$CLJS.N;IX=new $CLJS.ch(null,new $CLJS.h(null,7,[$CLJS.gV,null,$CLJS.TD,null,$CLJS.BM,null,$CLJS.XO,null,$CLJS.$E,null,$CLJS.LQ,null,$CLJS.aF,null],null),null);Kna=$CLJS.Ze($CLJS.N);Lna=$CLJS.Ze($CLJS.N);Mna=$CLJS.Ze($CLJS.N);Nna=$CLJS.Ze($CLJS.N);Ona=$CLJS.J.j(new $CLJS.h(null,1,[$CLJS.Jk,$CLJS.bB],null),$CLJS.Jk,$CLJS.Xh.o?$CLJS.Xh.o():$CLJS.Xh.call(null));
$CLJS.XX=new $CLJS.fi($CLJS.Hh.g("metabase.lib.convert","-\x3epMBQL"),$CLJS.SA,Ona,Kna,Lna,Mna,Nna);$CLJS.XX.m(null,$CLJS.ei,function(a){if($CLJS.Ad(a)&&$CLJS.z(a)instanceof $CLJS.M){var b=$CLJS.rd(a);var c=$CLJS.yd(b);a=c?$CLJS.td(a):a;var d=$CLJS.y(a);a=$CLJS.z(d);d=$CLJS.B(d);b=$CLJS.nV($CLJS.gg.j(new $CLJS.Q(null,2,5,$CLJS.R,[a,c?b:$CLJS.N],null),$CLJS.kf.h($CLJS.XX),d))}else b=a;return b});$CLJS.XX.m(null,$CLJS.fV,function(a){return a});
$CLJS.XX.m(null,$CLJS.TU,function(a){var b=$CLJS.XX.h($CLJS.aF.h(a)),c=$CLJS.Ie($CLJS.jk.g(function(t){var u=$CLJS.I(t,0,null);t=$CLJS.I(t,1,null);return $CLJS.xV($CLJS.XX.h(t),u)},$CLJS.XO.h(a))),d=$CLJS.gg.j($CLJS.N,$CLJS.Kl(function(t,u){$CLJS.I(u,0,null);u=$CLJS.I(u,1,null);u=$CLJS.O(u);u=$CLJS.J.g(u,$CLJS.AD);return new $CLJS.Q(null,2,5,$CLJS.R,[t,u],null)}),b),e=$CLJS.gg.j($CLJS.N,$CLJS.Kl(function(t,u){$CLJS.I(u,0,null);u=$CLJS.I(u,1,null);u=$CLJS.O(u);u=$CLJS.J.g(u,$CLJS.AD);return new $CLJS.Q(null,
2,5,$CLJS.R,[u,t],null)}),b),f=$CLJS.WX,k=$CLJS.VX;$CLJS.WX=d;$CLJS.VX=e;try{var l=xna(Ena(a),b,$CLJS.H([$CLJS.XO,c])),m=$CLJS.fb(function(t,u){return $CLJS.Wa($CLJS.J.g(t,u))?t:$CLJS.kk.j(t,u,$CLJS.XX)},l,$CLJS.bk.l(IX,$CLJS.aF,$CLJS.H([$CLJS.XO])));return $CLJS.n($CLJS.BM.h(m))?$CLJS.kk.j(m,$CLJS.BM,Dna):m}finally{$CLJS.VX=k,$CLJS.WX=f}});$CLJS.XX.m(null,$CLJS.$U,function(a){return yna(a,function(b){return $CLJS.TV(b,$CLJS.EE,$CLJS.XX)})});
$CLJS.XX.m(null,$CLJS.jK,function(a){a=$CLJS.kk.j($CLJS.kk.j(a,$CLJS.rK,$CLJS.XX),$CLJS.oK,$CLJS.XX);var b=$CLJS.n($CLJS.TD.h(a))?$CLJS.kk.j(a,$CLJS.TD,function(c){return $CLJS.ol(c)?$CLJS.jk.g($CLJS.XX,c):$CLJS.Bh.h(c)}):a;return $CLJS.Wa($CLJS.XD.h(a))?$CLJS.T.j(b,$CLJS.XD,"__join"):b});$CLJS.XX.m(null,$CLJS.hA,function(a){return $CLJS.jk.g($CLJS.XX,a)});
$CLJS.XX.m(null,$CLJS.jA,function(a){return $CLJS.n($CLJS.aj.h(a))?Cna($CLJS.T.j($CLJS.kk.j($CLJS.BV(a),$CLJS.oK,function(b){return $CLJS.jk.g($CLJS.XX,b)}),$CLJS.TX,!0)):$CLJS.fs(a,$CLJS.XX)});$CLJS.XX.m(null,$CLJS.lF,function(a){$CLJS.I(a,0,null);var b=$CLJS.I(a,1,null);a=$CLJS.I(a,2,null);a=$CLJS.yd(b)?new $CLJS.Q(null,2,5,$CLJS.R,[a,b],null):new $CLJS.Q(null,2,5,$CLJS.R,[b,a],null);b=$CLJS.I(a,0,null);a=$CLJS.I(a,1,null);return $CLJS.nV(new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.lF,a,b],null))});
$CLJS.XX.m(null,$CLJS.nj,function(a){$CLJS.I(a,0,null);var b=$CLJS.I(a,1,null);a=$CLJS.I(a,2,null);a=$CLJS.xU(a,new $CLJS.h(null,3,[$CLJS.bC,$CLJS.nA,$CLJS.BN,$CLJS.yj,$CLJS.TQ,$CLJS.uD],null));var c=$CLJS.T.j;var d=$CLJS.Ci.h(a);$CLJS.n(d)||(d=$CLJS.nA.h(a),d=$CLJS.n(d)?d:$CLJS.OD(b));a=c.call($CLJS.T,a,$CLJS.Ci,d);return $CLJS.nV(new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.nj,a,b],null))});
$CLJS.XX.m(null,$CLJS.UE,function(a){$CLJS.I(a,0,null);var b=$CLJS.I(a,1,null),c=$CLJS.I(a,2,null);a=$CLJS.ei.h(c);b=new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.UE,$CLJS.ak.g(c,$CLJS.ei),$CLJS.jk.g($CLJS.XX,b)],null);b=$CLJS.nV(b);return null!=a?$CLJS.de.g(b,$CLJS.XX.h(a)):b});$CLJS.XX.m(null,$CLJS.kA,function(a){var b=$CLJS.I(a,0,null),c=$CLJS.I(a,1,null);a=$CLJS.I(a,2,null);return $CLJS.nV(new $CLJS.Q(null,3,5,$CLJS.R,[b,a,c],null))});
$CLJS.XX.m(null,$CLJS.aF,function(a){var b=$CLJS.I(a,0,null),c=$CLJS.I(a,1,null),d=$CLJS.I(a,2,null),e=$CLJS.R;var f=$CLJS.J.g($CLJS.WX,c);if(!$CLJS.n(f))throw $CLJS.ji(["Error converting :aggregation reference: no aggregation at index ",$CLJS.p.h(c)].join(""),new $CLJS.h(null,1,[$CLJS.WQ,a],null));return $CLJS.nV(new $CLJS.Q(null,3,5,e,[b,d,f],null))});
$CLJS.XX.m(null,$CLJS.sL,function(a){$CLJS.I(a,0,null);var b=$CLJS.I(a,1,null);a=$CLJS.I(a,2,null);b=$CLJS.XX.h(b);var c=$CLJS.y(b);b=$CLJS.z(c);var d=$CLJS.B(c);c=$CLJS.z(d);d=$CLJS.B(d);return $CLJS.gg.g(new $CLJS.Q(null,2,5,$CLJS.R,[b,$CLJS.zk.l($CLJS.H([c,a]))],null),d)});Pna=$CLJS.Ze($CLJS.N);Qna=$CLJS.Ze($CLJS.N);Rna=$CLJS.Ze($CLJS.N);Sna=$CLJS.Ze($CLJS.N);Tna=$CLJS.J.j(new $CLJS.h(null,1,[$CLJS.Jk,$CLJS.bB],null),$CLJS.Jk,$CLJS.Xh.o?$CLJS.Xh.o():$CLJS.Xh.call(null));
$CLJS.MX=new $CLJS.fi($CLJS.Hh.g("metabase.lib.convert","-\x3elegacy-MBQL"),$CLJS.SA,Tna,Pna,Qna,Rna,Sna);
$CLJS.MX.m(null,$CLJS.ei,function(a){if($CLJS.Ad(a)&&$CLJS.z(a)instanceof $CLJS.M){a=$CLJS.y(a);var b=$CLJS.z(a),c=$CLJS.B(a);a=$CLJS.z(c);var d=$CLJS.B(c);if($CLJS.yd(a)){c=$CLJS.gg.g;b=new $CLJS.Q(null,1,5,$CLJS.R,[b],null);var e=$CLJS.jf.g;d=$CLJS.kf.g($CLJS.MX,d);a=LX(a);a=c.call($CLJS.gg,b,e.call($CLJS.jf,d,$CLJS.n(a)?new $CLJS.Q(null,1,5,$CLJS.R,[a],null):null))}else a=$CLJS.gg.g(new $CLJS.Q(null,1,5,$CLJS.R,[b],null),$CLJS.kf.g($CLJS.MX,$CLJS.ge(a,d)))}else a=$CLJS.yd(a)?$CLJS.fs(KX(a),$CLJS.MX):
a;return a});for(var YX=$CLJS.y(new $CLJS.Q(null,2,5,$CLJS.R,[UX,SX],null)),ZX=null,$X=0,aY=0;;)if(aY<$X){var Una=ZX.X(null,aY);$CLJS.rE(Una,RX);aY+=1}else{var bY=$CLJS.y(YX);if(bY){var cY=bY;if($CLJS.Bd(cY)){var dY=$CLJS.mc(cY),Vna=$CLJS.nc(cY),Wna=dY,Xna=$CLJS.D(dY);YX=Vna;ZX=Wna;$X=Xna}else{var Yna=$CLJS.z(cY);$CLJS.rE(Yna,RX);YX=$CLJS.B(cY);ZX=null;$X=0}aY=0}else break}
for(var eY=$CLJS.y(new $CLJS.Q(null,12,5,$CLJS.R,[$CLJS.Mw,$CLJS.fF,$CLJS.uF,$CLJS.QE,$CLJS.Hj,$CLJS.yF,$CLJS.ln,$CLJS.XE,$CLJS.sF,$CLJS.zF,$CLJS.xF,$CLJS.EF],null)),fY=null,gY=0,hY=0;;)if(hY<gY){var Zna=fY.X(null,hY);$CLJS.rE(Zna,UX);hY+=1}else{var iY=$CLJS.y(eY);if(iY){var jY=iY;if($CLJS.Bd(jY)){var kY=$CLJS.mc(jY),$na=$CLJS.nc(jY),aoa=kY,boa=$CLJS.D(kY);eY=$na;fY=aoa;gY=boa}else{var coa=$CLJS.z(jY);$CLJS.rE(coa,UX);eY=$CLJS.B(jY);fY=null;gY=0}hY=0}else break}
for(var lY=$CLJS.y($CLJS.Af([$CLJS.Kq,$CLJS.Yr,$CLJS.Lq,$CLJS.FF,$CLJS.UE,$CLJS.oF,$CLJS.LE,$CLJS.HF,$CLJS.CE,$CLJS.ZE,$CLJS.GE,$CLJS.jF,$CLJS.qF,$CLJS.IE,$CLJS.UA,$CLJS.VA,$CLJS.Ax,$CLJS.VH,$CLJS.$H,$CLJS.PH,$CLJS.WA,$CLJS.UH,$CLJS.NH,$CLJS.cI,$CLJS.hI,$CLJS.eI,$CLJS.TH,$CLJS.jI,$CLJS.XA,$CLJS.$A,$CLJS.KE,$CLJS.DE,$CLJS.IF,$CLJS.WG,$CLJS.nF,$CLJS.Kw,$CLJS.AF,$CLJS.CF,$CLJS.JF,$CLJS.is,$CLJS.os],!0)),mY=null,nY=0,oY=0;;)if(oY<nY){var doa=mY.X(null,oY);$CLJS.rE(doa,SX);oY+=1}else{var pY=$CLJS.y(lY);
if(pY){var qY=pY;if($CLJS.Bd(qY)){var rY=$CLJS.mc(qY),eoa=$CLJS.nc(qY),foa=rY,goa=$CLJS.D(rY);lY=eoa;mY=foa;nY=goa}else{var hoa=$CLJS.z(qY);$CLJS.rE(hoa,SX);lY=$CLJS.B(qY);mY=null;nY=0}oY=0}else break}$CLJS.MX.m(null,RX,function(a){return NX(a)});$CLJS.MX.m(null,$CLJS.jA,function(a){return $CLJS.gg.j($CLJS.N,$CLJS.hk.g(JX(),$CLJS.kf.h(function(b){var c=$CLJS.I(b,0,null);b=$CLJS.I(b,1,null);return new $CLJS.Q(null,2,5,$CLJS.R,[c,$CLJS.MX.h(b)],null)})),a)});
$CLJS.MX.m(null,$CLJS.aF,function(a){$CLJS.I(a,0,null);var b=$CLJS.I(a,1,null),c=$CLJS.I(a,2,null);if($CLJS.yd(b))try{var d=LX(b);b=$CLJS.R;var e=$CLJS.VX,f=$CLJS.J.j(e,c,QX);if($CLJS.E.g(f,QX))throw $CLJS.ji(["Unable to find key ",$CLJS.Oh.l($CLJS.H([c]))," in map."].join(""),new $CLJS.h(null,2,[Jna,e,$CLJS.Qv,c],null));var k=new $CLJS.Q(null,2,5,b,[$CLJS.aF,f],null);return $CLJS.n(d)?$CLJS.de.g(k,d):k}catch(l){throw c=l,d=$CLJS.qU(c),d=$CLJS.ia.g?$CLJS.ia.g("Error converting aggregation reference to pMBQL: %s",
d):$CLJS.ia.call(null,"Error converting aggregation reference to pMBQL: %s",d),$CLJS.ii(d,new $CLJS.h(null,1,[$CLJS.W,a],null),c);}else return a});$CLJS.MX.m(null,$CLJS.hA,function(a){return $CLJS.jk.g($CLJS.MX,a)});
$CLJS.MX.m(null,$CLJS.lF,function(a){$CLJS.I(a,0,null);var b=$CLJS.I(a,1,null);a=$CLJS.I(a,2,null);a=null==b||$CLJS.yd(b)?new $CLJS.Q(null,2,5,$CLJS.R,[b,a],null):new $CLJS.Q(null,2,5,$CLJS.R,[a,b],null);b=$CLJS.I(a,0,null);a=$CLJS.I(a,1,null);return new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.lF,$CLJS.MX.h(a),LX(b)],null)});
$CLJS.MX.m(null,$CLJS.nj,function(a){$CLJS.I(a,0,null);var b=$CLJS.I(a,1,null);a=$CLJS.I(a,2,null);b=LX($CLJS.xU(b,new $CLJS.h(null,3,[$CLJS.nA,$CLJS.bC,$CLJS.yj,$CLJS.BN,$CLJS.uD,$CLJS.TQ],null)));return new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.nj,a,b],null)});
$CLJS.MX.m(null,$CLJS.jK,function(a){var b=KX(a);a=0==$CLJS.XD.h(a).lastIndexOf("__join",0)?$CLJS.ak.g(b,$CLJS.XD):b;return $CLJS.zk.l($CLJS.H([$CLJS.fs($CLJS.ak.l(a,$CLJS.oK,$CLJS.H([$CLJS.rK])),$CLJS.MX),PX($CLJS.Hl(a,new $CLJS.Q(null,1,5,$CLJS.R,[$CLJS.rK],null)),$CLJS.rK,$CLJS.NQ),OX(a)]))});
$CLJS.MX.m(null,$CLJS.TU,function(a){var b=$CLJS.aF.h(a),c=$CLJS.gg.j($CLJS.N,$CLJS.Kl(function(f,k){$CLJS.I(k,0,null);k=$CLJS.I(k,1,null);k=$CLJS.O(k);k=$CLJS.J.g(k,$CLJS.AD);return new $CLJS.Q(null,2,5,$CLJS.R,[f,k],null)}),b);b=$CLJS.gg.j($CLJS.N,$CLJS.Kl(function(f,k){$CLJS.I(k,0,null);k=$CLJS.I(k,1,null);k=$CLJS.O(k);k=$CLJS.J.g(k,$CLJS.AD);return new $CLJS.Q(null,2,5,$CLJS.R,[k,f],null)}),b);var d=$CLJS.WX,e=$CLJS.VX;$CLJS.WX=c;$CLJS.VX=b;try{return $CLJS.fb(function(f,k){return $CLJS.TV(f,
k,$CLJS.MX)},PX($CLJS.TV($CLJS.TV(Gna(KX(a)),$CLJS.aF,function(f){return $CLJS.jk.g(NX,f)}),$CLJS.XO,function(f){return $CLJS.gg.g($CLJS.N,function(){return function m(l){return new $CLJS.pe(null,function(){for(;;){var t=$CLJS.y(l);if(t){if($CLJS.Bd(t)){var u=$CLJS.mc(t),v=$CLJS.D(u),x=$CLJS.se(v);a:for(var A=0;;)if(A<v){var C=$CLJS.ld(u,A),G=$CLJS.MX.h(C);C=new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.wV(C),$CLJS.E.g($CLJS.nj,$CLJS.z(G))?$CLJS.id(G):G],null);x.add(C);A+=1}else{u=!0;break a}return u?$CLJS.ve($CLJS.xe(x),
m($CLJS.nc(t))):$CLJS.ve($CLJS.xe(x),null)}x=$CLJS.z(t);u=$CLJS.MX.h(x);return $CLJS.ge(new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.wV(x),$CLJS.E.g($CLJS.nj,$CLJS.z(u))?$CLJS.id(u):u],null),m($CLJS.Mc(t)))}return null}},null,null)}(f)}())}),$CLJS.gV,$CLJS.PE),$CLJS.bk.l(IX,$CLJS.aF,$CLJS.H([$CLJS.gV,$CLJS.XO])))}finally{$CLJS.VX=e,$CLJS.WX=d}});$CLJS.MX.m(null,$CLJS.$U,function(a){return $CLJS.fs(KX(a),$CLJS.MX)});
$CLJS.MX.m(null,$CLJS.fV,function(a){try{var b=KX(a),c=$CLJS.sM.h(b),d=OX(b),e=$CLJS.E.g($CLJS.Us.h($CLJS.jd($CLJS.oK.h(a))),$CLJS.$U)?$CLJS.gP:$CLJS.HE;return $CLJS.zk.l($CLJS.H([$CLJS.fs($CLJS.ak.l(b,$CLJS.oK,$CLJS.H([$CLJS.sM,$CLJS.TX])),$CLJS.MX),function(){var k=$CLJS.He([$CLJS.aj,e,e,d]);return $CLJS.y(c)?$CLJS.T.j(k,$CLJS.sM,c):k}()]))}catch(k){var f=k;throw $CLJS.ii(function(){var l=$CLJS.qU(f);return $CLJS.ia.g?$CLJS.ia.g("Error converting MLv2 query to legacy query: %s",l):$CLJS.ia.call(null,
"Error converting MLv2 query to legacy query: %s",l)}(),new $CLJS.h(null,1,[$CLJS.HE,a],null),f);}});
$CLJS.sY=function(){function a(d,e,f){f=$CLJS.CX(null,$CLJS.Hy(f,$CLJS.H([$CLJS.yi,!0])));var k=$CLJS.DV(d,e);k=$CLJS.O(k);var l=$CLJS.J.g(k,$CLJS.aF);k=$CLJS.gg.j($CLJS.N,$CLJS.Kl(function(v,x){$CLJS.I(x,0,null);x=$CLJS.I(x,1,null);x=$CLJS.O(x);x=$CLJS.J.g(x,$CLJS.AD);return new $CLJS.Q(null,2,5,$CLJS.R,[v,x],null)}),l);l=$CLJS.gg.j($CLJS.N,$CLJS.Kl(function(v,x){$CLJS.I(x,0,null);x=$CLJS.I(x,1,null);x=$CLJS.O(x);x=$CLJS.J.g(x,$CLJS.AD);return new $CLJS.Q(null,2,5,$CLJS.R,[x,v],null)}),l);var m=
$CLJS.WX,t=$CLJS.VX;$CLJS.WX=k;$CLJS.VX=l;try{try{return $CLJS.XX.h(f)}catch(v){var u=v;throw $CLJS.ii(function(){var x=$CLJS.qU(u);return $CLJS.ia.g?$CLJS.ia.g("Error converting legacy ref to pMBQL: %s",x):$CLJS.ia.call(null,"Error converting legacy ref to pMBQL: %s",x)}(),new $CLJS.h(null,4,[$CLJS.HE,d,$CLJS.CK,e,Ina,f,Hna,$CLJS.WX],null),u);}}finally{$CLJS.VX=t,$CLJS.WX=m}}function b(d,e){return c.j?c.j(d,-1,e):c.call(null,d,-1,e)}var c=null;c=function(d,e,f){switch(arguments.length){case 2:return b.call(this,
d,e);case 3:return a.call(this,d,e,f)}throw Error("Invalid arity: "+arguments.length);};c.g=b;c.j=a;return c}();