var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./clojure.string.js");require("./metabase.lib.dispatch.js");require("./metabase.lib.hierarchy.js");require("./metabase.lib.schema.common.js");require("./metabase.lib.schema.expression.js");require("./metabase.lib.schema.id.js");require("./metabase.lib.schema.mbql_clause.js");require("./metabase.lib.schema.temporal_bucketing.js");require("./metabase.types.js");require("./metabase.util.malli.registry.js");
'use strict';var zK,BK,DK,GK,JK;$CLJS.wK=function(a){return $CLJS.Yh($CLJS.q($CLJS.bB),a,$CLJS.pF)};$CLJS.xK=new $CLJS.M(null,"many-pks?","many-pks?",-459675021);$CLJS.yK=new $CLJS.M(null,"object-id","object-id",-754527291);zK=new $CLJS.M("metabase.lib.schema.ref","aggregation-options","metabase.lib.schema.ref/aggregation-options",-15566487);$CLJS.AK=new $CLJS.M(null,"operators","operators",-2064102509);
BK=new $CLJS.M("metabase.lib.schema.ref","field.options","metabase.lib.schema.ref/field.options",408316031);$CLJS.CK=new $CLJS.M(null,"stage-number","stage-number",-1752729638);DK=new $CLJS.M("metabase.lib.schema.ref","field.literal","metabase.lib.schema.ref/field.literal",-1228060748);$CLJS.EK=new $CLJS.M(null,"min-value","min-value",-1119123315);$CLJS.FK=new $CLJS.M(null,"dimensions","dimensions",-254818097);
GK=new $CLJS.M("metabase.lib.schema.ref","field.id","metabase.lib.schema.ref/field.id",-956546909);$CLJS.HK=new $CLJS.M(null,"max-value","max-value",687805168);$CLJS.IK=new $CLJS.M("metabase.lib.schema","query","metabase.lib.schema/query",-1207387140);JK=new $CLJS.M("metabase.lib.schema.ref","field.literal.options","metabase.lib.schema.ref/field.literal.options",-860446668);$CLJS.KK=new $CLJS.M(null,"null","null",-180137709);
$CLJS.LK=new $CLJS.M("metabase.lib.drill-thru","drill-thru","metabase.lib.drill-thru/drill-thru",-67424984);$CLJS.Y(BK,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.rs,$CLJS.yD,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Gj,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.rF,new $CLJS.h(null,1,[$CLJS.Ar,!0],null),$CLJS.fD],null)],null)],null));$CLJS.Y(JK,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.rs,BK,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Gj,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.nA,$CLJS.CD],null)],null)],null));$CLJS.Y(DK,new $CLJS.Q(null,4,5,$CLJS.R,[$CLJS.ir,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Nj,$CLJS.lF],null),JK,$CLJS.sD],null));
$CLJS.Y(GK,new $CLJS.Q(null,4,5,$CLJS.R,[$CLJS.ir,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Nj,$CLJS.lF],null),BK,$CLJS.eK],null));
$CLJS.KF.g($CLJS.lF,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.mr,new $CLJS.Q(null,4,5,$CLJS.R,[$CLJS.ir,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Nj,$CLJS.lF],null),BK,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.fr,$CLJS.eK,$CLJS.sD],null)],null),new $CLJS.Q(null,4,5,$CLJS.R,[$CLJS.lr,new $CLJS.h(null,2,[$CLJS.Ji,function(a){return $CLJS.xd(a)?($CLJS.I(a,0,null),$CLJS.I(a,1,null),a=$CLJS.I(a,2,null),$CLJS.SA(a)):null},$CLJS.ss,"Invalid :field clause ID or name: must be a string or integer"],null),new $CLJS.Q(null,2,
5,$CLJS.R,[$CLJS.fA,GK],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.eA,DK],null)],null)],null));$CLJS.rE($CLJS.lF,$CLJS.pF);$CLJS.ND.m(null,$CLJS.lF,function(a){$CLJS.I(a,0,null);var b=$CLJS.I(a,1,null);$CLJS.I(a,2,null);a=$CLJS.uz($CLJS.Ci,$CLJS.nA)(b);return $CLJS.n(a)?a:$CLJS.$D});$CLJS.yE($CLJS.kA,$CLJS.H([$CLJS.sD]));$CLJS.ND.m(null,$CLJS.kA,function(a){$CLJS.I(a,0,null);var b=$CLJS.I(a,1,null);$CLJS.I(a,2,null);a=$CLJS.uz($CLJS.Ci,$CLJS.nA)(b);return $CLJS.n(a)?a:$CLJS.$D});
$CLJS.rE($CLJS.kA,$CLJS.pF);$CLJS.Y(zK,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.rs,$CLJS.yD,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Gj,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.U,new $CLJS.h(null,1,[$CLJS.Ar,!0],null),$CLJS.sD],null),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.nD,new $CLJS.h(null,1,[$CLJS.Ar,!0],null),$CLJS.sD],null)],null)],null));$CLJS.KF.g($CLJS.aF,new $CLJS.Q(null,4,5,$CLJS.R,[$CLJS.ir,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Nj,$CLJS.aF],null),zK,$CLJS.Bj],null));
$CLJS.ND.m(null,$CLJS.aF,function(a){$CLJS.I(a,0,null);var b=$CLJS.I(a,1,null);$CLJS.I(a,2,null);a=$CLJS.uz($CLJS.Ci,$CLJS.nA)(b);return $CLJS.n(a)?a:$CLJS.$D});$CLJS.rE($CLJS.aF,$CLJS.pF);$CLJS.yE($CLJS.JE,$CLJS.H([$CLJS.Yr,$CLJS.sj,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Uk,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.JJ],null)],null)]));$CLJS.rE($CLJS.JE,$CLJS.pF);
$CLJS.yE($CLJS.gF,$CLJS.H([$CLJS.Yr,$CLJS.$D,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.Uk,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.HJ],null)],null)]));$CLJS.rE($CLJS.gF,$CLJS.pF);
$CLJS.Y($CLJS.pF,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.mr,$CLJS.PD,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Mi,new $CLJS.h(null,1,[$CLJS.Ds,function(){return["Valid reference, must be one of these clauses: ",$CLJS.gs(", ",$CLJS.xz($CLJS.Kd,$CLJS.Ck.g($CLJS.q($CLJS.bB),$CLJS.pF)))].join("")}],null),function(a){a=$CLJS.I(a,0,null);return $CLJS.wK(a)}],null)],null));