var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./clojure.string.js");require("./medley.core.js");require("./metabase.lib.aggregation.js");require("./metabase.lib.binning.js");require("./metabase.lib.card.js");require("./metabase.lib.dispatch.js");require("./metabase.lib.equality.js");require("./metabase.lib.expression.js");require("./metabase.lib.join.js");require("./metabase.lib.join.util.js");require("./metabase.lib.metadata.js");require("./metabase.lib.metadata.calculation.js");require("./metabase.lib.normalize.js");require("./metabase.lib.options.js");require("./metabase.lib.ref.js");require("./metabase.lib.remove_replace.js");require("./metabase.lib.schema.js");require("./metabase.lib.schema.common.js");require("./metabase.lib.schema.id.js");require("./metabase.lib.schema.metadata.js");require("./metabase.lib.schema.temporal_bucketing.js");require("./metabase.lib.temporal_bucket.js");require("./metabase.lib.types.isa.js");require("./metabase.lib.util.js");require("./metabase.shared.util.i18n.js");require("./metabase.shared.util.time.js");require("./metabase.util.js");require("./metabase.util.humanization.js");require("./metabase.util.log.js");require("./metabase.util.malli.js");require("./metabase.util.malli.registry.js");
'use strict';var K6,M6,N6,Msa,Nsa,Osa,Q6,R6,T6,U6,Psa,Qsa,W6,X6,Rsa,Ssa;K6=function(a){var b=new $CLJS.h(null,3,[$CLJS.AD,$CLJS.p.h($CLJS.KD()),$CLJS.nA,$CLJS.nA.h(a),$CLJS.Ci,$CLJS.uz($CLJS.Ci,$CLJS.nA)(a)],null);return new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.kA,b,$CLJS.uz($CLJS.rD,$CLJS.U)(a)],null)};$CLJS.L6=function(a){return $CLJS.N4.h(a)};M6=function(a){return $CLJS.T.j(a,$CLJS.Us,$CLJS.e4)};
N6=function(a,b){return $CLJS.E.g($CLJS.mD.h(a),$CLJS.Hl(b,new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.ED,$CLJS.lD,$CLJS.DD],null)))};Msa=function(a){return $CLJS.G0(a,new $CLJS.h(null,1,[$CLJS.ED,$CLJS.Bh],null))};
Nsa=function(a,b){var c=$CLJS.Ue(function(e){return $CLJS.rG(function(f){return $CLJS.E.g($CLJS.J.g(f,e),a)},b)},new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.KY,$CLJS.U],null));if($CLJS.n(c))return c;c=$CLJS.Gz($CLJS.zx);if($CLJS.n($CLJS.Fz("metabase.lib.field",c))){var d=$CLJS.iD("Invalid :field clause: column {0} does not exist. Found: {1}",$CLJS.H([$CLJS.Oh.l($CLJS.H([a])),$CLJS.Oh.l($CLJS.H([$CLJS.jk.g($CLJS.KY,b)]))]));d instanceof Error?$CLJS.Ez("metabase.lib.field",c,$CLJS.vv(),d):$CLJS.Ez("metabase.lib.field",
c,$CLJS.vv.l($CLJS.H([d])),null)}return null};
Osa=function(a,b,c){if($CLJS.n(O6))return null;var d=O6;O6=!0;try{var e=$CLJS.l1(a,b),f=$CLJS.n(e)?$CLJS.DV(a,e):$CLJS.DV(a,b),k=function(){var m=$CLJS.P6.h(f);if($CLJS.n(m))return m;m=$CLJS.wz(f,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.lU,$CLJS.AV],null));if($CLJS.n(m))return m;m=$CLJS.n(function(){var u=$CLJS.MU.h(f);if($CLJS.n(u))return u;u=$CLJS.cO.h(f);if($CLJS.n(u))return u;u=$CLJS.XO.h(f);return $CLJS.n(u)?u:$CLJS.TD.h(f)}())?$CLJS.P_.j(a,b,f):null;if($CLJS.n(m))return m;m=$CLJS.Gz($CLJS.zx);if($CLJS.n($CLJS.Fz("metabase.lib.field",
m))){var t=$CLJS.iD("Cannot resolve column {0}: stage has no metadata",$CLJS.H([$CLJS.Oh.l($CLJS.H([c]))]));return t instanceof Error?$CLJS.Ez("metabase.lib.field",m,$CLJS.vv(),t):$CLJS.Ez("metabase.lib.field",m,$CLJS.vv.l($CLJS.H([t])),null)}return null}(),l=function(){var m=$CLJS.y(k);return m?Nsa(c,k):m}();return $CLJS.n(l)?$CLJS.n(e)?$CLJS.T.j($CLJS.T.j($CLJS.X2($CLJS.ak.l(l,$CLJS.Si,$CLJS.H([$CLJS.XJ,$CLJS.NV,$CLJS.HV])),null),$CLJS.U,function(){var m=$CLJS.KY.h(l);return $CLJS.n(m)?m:$CLJS.U.h(l)}()),
$CLJS.IJ,$CLJS.wY):l:null}finally{O6=d}};
Q6=function(a,b,c){$CLJS.I(c,0,null);var d=$CLJS.I(c,1,null),e=$CLJS.O(d);d=$CLJS.J.g(e,$CLJS.rO);var f=$CLJS.I(c,2,null);c=$CLJS.zk.l($CLJS.H([function(){var k=$CLJS.nA.h(e);return $CLJS.n(k)?new $CLJS.h(null,1,[$CLJS.nA,k],null):null}(),function(){var k=$CLJS.uz($CLJS.Ci,$CLJS.nA)(e);return $CLJS.n(k)?new $CLJS.h(null,1,[$CLJS.Ci,k],null):null}(),function(){var k=$CLJS.rQ.h(e);return $CLJS.n(k)?new $CLJS.h(null,1,[$CLJS.NV,k],null):null}(),function(){var k=$CLJS.rF.h(e);return $CLJS.n(k)?new $CLJS.h(null,
1,[$CLJS.HV,k],null):null}(),$CLJS.Gd(f)?function(){var k=$CLJS.r1(a,b,f);return $CLJS.n(k)?k:new $CLJS.h(null,2,[$CLJS.Us,$CLJS.GJ,$CLJS.U,$CLJS.p.h(f)],null)}():$CLJS.n(d)?new $CLJS.h(null,2,[$CLJS.Us,$CLJS.GJ,$CLJS.U,$CLJS.p.h(f)],null):function(){var k=Osa(a,b,f);return $CLJS.n(k)?k:new $CLJS.h(null,2,[$CLJS.Us,$CLJS.GJ,$CLJS.U,$CLJS.p.h(f)],null)}()]));return $CLJS.n(d)?$CLJS.X2(c,d):c};
R6=function(a){a=$CLJS.O(a);var b=$CLJS.J.g(a,$CLJS.HV);return $CLJS.n($CLJS.n(b)?$CLJS.Jd($CLJS.oG,b):b)?$CLJS.hj:$CLJS.uz($CLJS.Ci,$CLJS.nA)(a)};
$CLJS.S6=function(a,b,c,d){$CLJS.I(d,0,null);var e=$CLJS.I(d,1,null),f=$CLJS.O(e),k=$CLJS.J.g(f,$CLJS.AD),l=$CLJS.J.g(f,$CLJS.nA),m=$CLJS.J.g(f,$CLJS.rQ),t=$CLJS.J.g(f,$CLJS.Ci);e=$CLJS.J.g(f,$CLJS.rO);var u=$CLJS.J.g(f,$CLJS.CM),v=$CLJS.J.g(f,$CLJS.rF),x=$CLJS.zk.l;k=new $CLJS.h(null,2,[$CLJS.Us,$CLJS.GJ,$CLJS.t0,k],null);f=$CLJS.nD.h(f);a=$CLJS.n(f)?f:$CLJS.e_.j(a,b,d);c=x.call($CLJS.zk,$CLJS.H([k,c,new $CLJS.h(null,1,[$CLJS.nD,a],null)]));c=$CLJS.n(t)?$CLJS.T.j(c,$CLJS.Ci,t):c;l=$CLJS.n(l)?$CLJS.T.j(c,
$CLJS.nA,l):c;v=$CLJS.n(v)?$CLJS.T.j(l,$CLJS.HV,v):l;m=$CLJS.n(m)?$CLJS.T.j(v,$CLJS.NV,m):v;u=$CLJS.n(u)?$CLJS.T.j(m,$CLJS.WJ,u):m;return $CLJS.n(e)?$CLJS.X2(u,e):u};T6=function(a,b,c){return $CLJS.n($CLJS.Ue(function(d){return $CLJS.E.g($CLJS.Ek.h(d),c)},a))?$CLJS.jk.g(function(d){var e=$CLJS.Jd(d,b)?$CLJS.ak.l(d,d,$CLJS.H([b])):d;return $CLJS.E.g($CLJS.Ek.h(d),c)?$CLJS.T.j(e,b,!0):e},a):a};
U6=function(a){var b=$CLJS.n($CLJS.f1.h(a))?null:function(){var d=$CLJS.IJ.h(a),e=new $CLJS.ch(null,new $CLJS.h(null,3,[$CLJS.NY,null,$CLJS.UY,null,$CLJS.wY,null],null),null);return e.h?e.h(d):e.call(null,d)}(),c=$CLJS.zk.l($CLJS.H([new $CLJS.h(null,3,[$CLJS.AD,$CLJS.p.h($CLJS.KD()),$CLJS.nA,$CLJS.nA.h(a),$CLJS.Ci,R6(a)],null),function(){var d=$CLJS.Z0(a);return $CLJS.n(d)?new $CLJS.h(null,1,[$CLJS.rO,d],null):null}(),function(){var d=$CLJS.HV.h(a);return $CLJS.n(d)?new $CLJS.h(null,1,[$CLJS.rF,d],
null):null}(),function(){var d=$CLJS.LV.h(a);return $CLJS.n(d)?new $CLJS.h(null,1,[$CLJS.LV,d],null):null}(),function(){var d=$CLJS.NV.h(a);return $CLJS.n(d)?new $CLJS.h(null,1,[$CLJS.rQ,d],null):null}(),function(){var d=$CLJS.WJ.h(a);return $CLJS.n(d)?new $CLJS.h(null,1,[$CLJS.CM,d],null):null}()]));b=($CLJS.n(b)?$CLJS.uz($CLJS.KY,$CLJS.U):$CLJS.uz($CLJS.Si,$CLJS.U))(a);return new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.lF,c,b],null)};
Psa=function(a,b){return $CLJS.nf(function(c){return $CLJS.E.g($CLJS.IJ.h(c),$CLJS.EY)},$CLJS.P_.v(a,b,$CLJS.DV(a,b),new $CLJS.h(null,3,[$CLJS.x_,!1,$CLJS.D_,!0,$CLJS.t_,!1],null)))};Qsa=new $CLJS.M("metabase.lib.field","field-values-search-info","metabase.lib.field/field-values-search-info",-468454179);$CLJS.V6=new $CLJS.M(null,"search-field-id","search-field-id",-699326724);
W6=new $CLJS.M("metabase.lib.field","field-values-search-info.has-field-values","metabase.lib.field/field-values-search-info.has-field-values",1753198226);X6=new $CLJS.M(null,"parent-id","parent-id",-1400729131);$CLJS.P6=new $CLJS.M("metabase.lib.stage","cached-metadata","metabase.lib.stage/cached-metadata",-1406479151);Rsa=new $CLJS.M(null,"earliest","earliest",-1928154382);Ssa=new $CLJS.M(null,"latest","latest",24323665);$CLJS.H0.m(null,$CLJS.lF,function(a){var b=$CLJS.I(a,0,null),c=$CLJS.I(a,1,null);a=$CLJS.I(a,2,null);return new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.Bh.h(b),$CLJS.G0(c,new $CLJS.h(null,2,[$CLJS.rF,$CLJS.Bh,$CLJS.rQ,Msa],null)),a],null)});var O6=!1,Y6=function Y6(a,b){var d=$CLJS.Q0(a,X6.h(b));a=$CLJS.n(X6.h(d))?Y6.g?Y6.g(a,d):Y6.call(null,a,d):d;a=$CLJS.O(a);var e=$CLJS.J.g(a,$CLJS.U);return $CLJS.kk.j(b,$CLJS.U,function(f){return[$CLJS.p.h(e),".",$CLJS.p.h(f)].join("")})};
$CLJS.I_.m(null,$CLJS.GJ,function(a,b,c){return R6(c)});$CLJS.I_.m(null,$CLJS.lF,function(a,b,c){$CLJS.I(c,0,null);var d=$CLJS.I(c,1,null);d=$CLJS.O(d);d=$CLJS.J.g(d,$CLJS.rF);$CLJS.I(c,2,null);c=Q6(a,b,c);c=$CLJS.n(d)?$CLJS.T.j(c,$CLJS.HV,d):c;return $CLJS.J_.j(a,b,c)});$CLJS.K_.m(null,$CLJS.GJ,function(a,b,c){a=$CLJS.O(c);b=$CLJS.J.g(a,$CLJS.U);return $CLJS.T.j(a,$CLJS.U,b)});$CLJS.K_.m(null,$CLJS.lF,function(a,b,c){var d=Q6(a,b,c);b=$CLJS.S6(a,b,d,c);return $CLJS.n(X6.h(b))?Y6(a,b):b});
$CLJS.E_.m(null,$CLJS.GJ,function(a,b,c,d){c=$CLJS.O(c);var e=$CLJS.J.g(c,$CLJS.nD),f=$CLJS.J.g(c,$CLJS.U),k=$CLJS.J.g(c,$CLJS.Ek),l=$CLJS.J.g(c,$CLJS.NV),m=$CLJS.J.g(c,$CLJS.YY),t=$CLJS.J.g(c,$CLJS.WJ),u=$CLJS.J.g(c,$CLJS.XJ);e=$CLJS.n(e)?e:"string"===typeof f?$CLJS.X0.g($CLJS.W0,f):$CLJS.p.h(f);$CLJS.E.g(d,$CLJS.f_)&&-1==e.indexOf(" → ")?($CLJS.n(t)?(t=$CLJS.Q0(a,t),$CLJS.n(t)?a=(0,$CLJS.na)($CLJS.Az($CLJS.nD.h($CLJS.h_.j(a,b,t)),$CLJS.QV,"")):(u=$CLJS.Y0(a,u),a=$CLJS.e_.v(a,b,u,d))):a=null,m=$CLJS.n(a)?
a:$CLJS.n(m)?m:$CLJS.Z0(c)):m=null;m=$CLJS.n(m)?[$CLJS.p.h(m)," → ",$CLJS.p.h(e)].join(""):e;return $CLJS.n(k)?(c=$CLJS.Xz($CLJS.Az($CLJS.ih(k),"-"," ")),$CLJS.ia.j?$CLJS.ia.j("%s: %s",m,c):$CLJS.ia.call(null,"%s: %s",m,c)):$CLJS.n(l)?(c=$CLJS.K4(l,c),$CLJS.ia.j?$CLJS.ia.j("%s: %s",m,c):$CLJS.ia.call(null,"%s: %s",m,c)):m});
$CLJS.E_.m(null,$CLJS.lF,function(a,b,c,d){$CLJS.I(c,0,null);var e=$CLJS.I(c,1,null),f=$CLJS.O(e);e=$CLJS.J.g(f,$CLJS.rQ);var k=$CLJS.J.g(f,$CLJS.rO),l=$CLJS.J.g(f,$CLJS.rF);f=$CLJS.J.g(f,$CLJS.CM);$CLJS.I(c,2,null);c=Q6(a,b,c);c=$CLJS.n(k)?$CLJS.T.j(c,$CLJS.YY,k):c;l=$CLJS.n(l)?$CLJS.T.j(c,$CLJS.Ek,l):c;e=$CLJS.n(e)?$CLJS.T.j(l,$CLJS.NV,e):l;e=$CLJS.n(f)?$CLJS.T.j(e,$CLJS.WJ,f):e;return $CLJS.n(e)?$CLJS.e_.v(a,b,e,d):$CLJS.LD("[Unknown Field]")});
$CLJS.F_.m(null,$CLJS.GJ,function(a,b,c){a=$CLJS.O(c);return $CLJS.J.g(a,$CLJS.U)});$CLJS.F_.m(null,$CLJS.lF,function(a,b,c){$CLJS.I(c,0,null);$CLJS.I(c,1,null);c=Q6(a,b,c);return $CLJS.n(c)?$CLJS.G_.j(a,b,c):"unknown_field"});
$CLJS.L_.m(null,$CLJS.GJ,function(a,b,c){return $CLJS.zk.l($CLJS.H([function(){var d=$CLJS.kH($CLJS.L_,$CLJS.ei);return d.j?d.j(a,b,c):d.call(null,a,b,c)}(),$CLJS.E.g($CLJS.IJ.h(c),$CLJS.NY)?function(){var d=$CLJS.XY.h(c);return $CLJS.n(d)?(d=$CLJS.$Z(a,d),$CLJS.n(d)?new $CLJS.h(null,1,[$CLJS.MV,new $CLJS.h(null,2,[$CLJS.U,$CLJS.U.h(d),$CLJS.nD,$CLJS.U.h(d)],null)],null):null):null}():null]))});$CLJS.k0.m(null,$CLJS.lF,function(a){$CLJS.I(a,0,null);var b=$CLJS.I(a,1,null);$CLJS.I(a,2,null);return $CLJS.rF.h(b)});
$CLJS.k0.m(null,$CLJS.GJ,function(a){return $CLJS.HV.h(a)});
$CLJS.j0.m(null,$CLJS.lF,function(a,b){$CLJS.I(a,0,null);var c=$CLJS.I(a,1,null);a=$CLJS.I(a,2,null);if($CLJS.n(b)){var d=$CLJS.Jd($CLJS.oG,b),e=$CLJS.lB($CLJS.LV,$CLJS.Ci,$CLJS.nA)(c);c=$CLJS.T.l(c,$CLJS.rF,b,$CLJS.H([$CLJS.Ci,d?$CLJS.hj:e,$CLJS.LV,e]));return new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.lF,c,a],null)}b=$CLJS.LV.h(c);c=$CLJS.n(b)?$CLJS.ak.g($CLJS.T.j(c,$CLJS.Ci,b),$CLJS.LV):c;c=$CLJS.ak.g(c,$CLJS.rF);return new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.lF,c,a],null)});
$CLJS.j0.m(null,$CLJS.GJ,function(a,b){return $CLJS.n(b)?$CLJS.T.l(a,$CLJS.HV,b,$CLJS.H([$CLJS.LV,$CLJS.lB($CLJS.LV,$CLJS.Ci,$CLJS.nA)(a)])):$CLJS.ak.l(a,$CLJS.HV,$CLJS.H([$CLJS.LV]))});$CLJS.m0.m(null,$CLJS.lF,function(a,b,c){return $CLJS.n0.j(a,b,Q6(a,b,c))});
$CLJS.m0.m(null,$CLJS.GJ,function(a,b,c){if($CLJS.gk.g($CLJS.IJ.h(c),$CLJS.EY)){a=$CLJS.uz($CLJS.Ci,$CLJS.nA)(c);b=null==c?null:$CLJS.QM.h(c);if(null==b)var d=null;else try{var e=$CLJS.oC.h($CLJS.aj.h(b));if($CLJS.n(e)){var f=$CLJS.O(e),k=$CLJS.J.g(f,Rsa),l=$CLJS.J.g(f,Ssa),m=$CLJS.Toa.l($CLJS.H([$CLJS.h0.h(k),$CLJS.h0.h(l)]));d=isNaN(m)?null:$CLJS.n($CLJS.Dq.g?$CLJS.Dq.g(1,m):$CLJS.Dq.call(null,1,m))?$CLJS.Ik:$CLJS.n($CLJS.Dq.g?$CLJS.Dq.g(31,m):$CLJS.Dq.call(null,31,m))?$CLJS.Qk:$CLJS.n($CLJS.Dq.g?
$CLJS.Dq.g(365,m):$CLJS.Dq.call(null,365,m))?$CLJS.cj:$CLJS.ij}else d=null}catch(t){if(t instanceof Error)d=null;else throw t;}e=$CLJS.nB(a,$CLJS.oC)?$CLJS.cpa:$CLJS.nB(a,$CLJS.OB)?$CLJS.bpa:$CLJS.nB(a,$CLJS.OC)?$CLJS.apa:$CLJS.Ef;d=$CLJS.n(d)?T6(e,$CLJS.ei,d):e;return $CLJS.n($CLJS.HV.h(c))?T6(d,$CLJS.m_,$CLJS.HV.h(c)):d}return $CLJS.Ef});
$CLJS.N4.m(null,$CLJS.lF,function(a){var b=null==a?null:$CLJS.HD(a);b=null==b?null:$CLJS.rQ.h(b);return null==b?null:$CLJS.T.l(b,$CLJS.Us,$CLJS.M4,$CLJS.H([$CLJS.L4,function(c,d){return Q6(c,d,a)}]))});$CLJS.N4.m(null,$CLJS.GJ,function(a){var b=null==a?null:$CLJS.NV.h(a);return null==b?null:$CLJS.T.l(b,$CLJS.Us,$CLJS.M4,$CLJS.H([$CLJS.L4,$CLJS.We(a)]))});$CLJS.H4.m(null,$CLJS.lF,function(a,b){return $CLJS.ID(a,$CLJS.GD,$CLJS.H([$CLJS.rQ,b]))});
$CLJS.H4.m(null,$CLJS.GJ,function(a,b){return $CLJS.GD(a,$CLJS.NV,b)});$CLJS.O4.m(null,$CLJS.lF,function(a,b,c){return $CLJS.P4.j(a,b,Q6(a,b,c))});
$CLJS.O4.m(null,$CLJS.GJ,function(a,b,c){b=$CLJS.O(c);c=$CLJS.J.g(b,$CLJS.Ci);var d=$CLJS.J.g(b,$CLJS.QM),e=$CLJS.J.g(b,$CLJS.yj);if($CLJS.gk.g($CLJS.IJ.h(b),$CLJS.EY)){var f=function(){var m=null==a?null:$CLJS.P0(a);m=null==m?null:$CLJS.az.h(m);return null==m?null:$CLJS.Jd(m,$CLJS.rQ)}(),k=$CLJS.wz(d,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.aj,$CLJS.uj],null)),l=$CLJS.L6(b);return function u(t){return new $CLJS.pe(null,function(){for(;;){var v=$CLJS.y(t);if(v){if($CLJS.Bd(v)){var x=$CLJS.mc(v),A=$CLJS.D(x),
C=$CLJS.se(A);return function(){for(var K=0;;)if(K<A){var S=$CLJS.ld(x,K),X=C,ba=S;S=N6(S,l)?$CLJS.T.j(ba,$CLJS.m_,!0):ba;X.add(S);K+=1}else return!0}()?$CLJS.ve($CLJS.xe(C),u($CLJS.nc(v))):$CLJS.ve($CLJS.xe(C),null)}var G=$CLJS.z(v);return $CLJS.ge(function(){var K=G;return N6(G,l)?$CLJS.T.j(K,$CLJS.m_,!0):K}(),u($CLJS.Mc(v)))}return null}},null,null)}($CLJS.Wa(function(){if($CLJS.n(f)){var t=$CLJS.ln.h(k);return $CLJS.n(t)?$CLJS.Hj.h(k):t}return f}())?null:$CLJS.nB(e,$CLJS.jj)?$CLJS.jk.g(M6,new $CLJS.Q(null,
5,5,$CLJS.R,[$CLJS.J4(),new $CLJS.h(null,2,[$CLJS.nD,$CLJS.LD("Bin every 0.1 degrees"),$CLJS.mD,new $CLJS.h(null,2,[$CLJS.ED,$CLJS.DD,$CLJS.DD,.1],null)],null),new $CLJS.h(null,2,[$CLJS.nD,$CLJS.LD("Bin every 1 degree"),$CLJS.mD,new $CLJS.h(null,2,[$CLJS.ED,$CLJS.DD,$CLJS.DD,1],null)],null),new $CLJS.h(null,2,[$CLJS.nD,$CLJS.LD("Bin every 10 degrees"),$CLJS.mD,new $CLJS.h(null,2,[$CLJS.ED,$CLJS.DD,$CLJS.DD,10],null)],null),new $CLJS.h(null,2,[$CLJS.nD,$CLJS.LD("Bin every 20 degrees"),$CLJS.mD,new $CLJS.h(null,
2,[$CLJS.ED,$CLJS.DD,$CLJS.DD,20],null)],null)],null)):$CLJS.nB(c,$CLJS.uj)&&!$CLJS.nB(e,$CLJS.oi)?$CLJS.jk.g(M6,new $CLJS.Q(null,4,5,$CLJS.R,[$CLJS.J4(),new $CLJS.h(null,2,[$CLJS.nD,$CLJS.LD("10 bins"),$CLJS.mD,new $CLJS.h(null,2,[$CLJS.ED,$CLJS.lD,$CLJS.lD,10],null)],null),new $CLJS.h(null,2,[$CLJS.nD,$CLJS.LD("50 bins"),$CLJS.mD,new $CLJS.h(null,2,[$CLJS.ED,$CLJS.lD,$CLJS.lD,50],null)],null),new $CLJS.h(null,2,[$CLJS.nD,$CLJS.LD("100 bins"),$CLJS.mD,new $CLJS.h(null,2,[$CLJS.ED,$CLJS.lD,$CLJS.lD,
100],null)],null)],null)):null)}return $CLJS.Ef});$CLJS.mV.m(null,$CLJS.lF,function(a){return a});
$CLJS.mV.m(null,$CLJS.GJ,function(a){a=$CLJS.O(a);var b=$CLJS.J.g(a,$CLJS.IJ);switch(b instanceof $CLJS.M?b.S:null){case "source/aggregations":return b=new $CLJS.h(null,2,[$CLJS.AD,$CLJS.p.h($CLJS.KD()),$CLJS.Ci,$CLJS.uz($CLJS.Ci,$CLJS.nA)(a)],null),a=$CLJS.t0.h(a),new $CLJS.Q(null,3,5,$CLJS.R,[$CLJS.aF,b,a],null);case "source/expressions":return K6(a);case "source/fields":case "source/breakouts":return $CLJS.n($CLJS.rD.h(a))?K6(a):U6(a);default:return U6(a)}});
$CLJS.Tsa=function(){function a(e,f,k){k=$CLJS.Ie($CLJS.jk.g($CLJS.oV,k));var l=Psa(e,f),m=$CLJS.gg.j($CLJS.dh,$CLJS.zl(function(t){return $CLJS.x1.v(e,f,t,l)}),$CLJS.n(k)?k:$CLJS.Ef);m=$CLJS.ik.g(m,l);k=$CLJS.n(k)?$CLJS.gg.j(k,$CLJS.kf.h($CLJS.oV),m):null;return $CLJS.PV.l(e,f,$CLJS.GD,$CLJS.H([$CLJS.TD,k]))}function b(e,f){return d.j?d.j(e,-1,f):d.call(null,e,-1,f)}function c(e){return function(f,k){return d.j?d.j(f,k,e):d.call(null,f,k,e)}}var d=null;d=function(e,f,k){switch(arguments.length){case 1:return c.call(this,
e);case 2:return b.call(this,e,f);case 3:return a.call(this,e,f,k)}throw Error("Invalid arity: "+arguments.length);};d.h=c;d.g=b;d.j=a;return d}();$CLJS.Z6=function(){function a(d,e){return $CLJS.TD.h($CLJS.DV(d,e))}function b(d){return c.g?c.g(d,-1):c.call(null,d,-1)}var c=null;c=function(d,e){switch(arguments.length){case 1:return b.call(this,d);case 2:return a.call(this,d,e)}throw Error("Invalid arity: "+arguments.length);};c.h=b;c.g=a;return c}();
$CLJS.Usa=function(){function a(d,e){var f=$CLJS.P_.v(d,e,$CLJS.DV(d,e),new $CLJS.h(null,3,[$CLJS.x_,!1,$CLJS.D_,!1,$CLJS.t_,!1],null)),k=$CLJS.Z6.g(d,e);return $CLJS.ud(k)?$CLJS.jk.g(function(l){return $CLJS.T.j(l,$CLJS.LY,!0)},f):$CLJS.V2(d,e,f,k)}function b(d){return c.g?c.g(d,-1):c.call(null,d,-1)}var c=null;c=function(d,e){switch(arguments.length){case 1:return b.call(this,d);case 2:return a.call(this,d,e)}throw Error("Invalid arity: "+arguments.length);};c.h=b;c.g=a;return c}();
$CLJS.Y(W6,new $CLJS.Q(null,4,5,$CLJS.R,[$CLJS.cr,$CLJS.mj,$CLJS.zY,$CLJS.$y],null));
$CLJS.Y(Qsa,new $CLJS.Q(null,4,5,$CLJS.R,[$CLJS.Gj,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.RJ,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.er,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.eK],null)],null)],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.V6,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.er,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,$CLJS.eK],null)],null)],null),new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.TY,new $CLJS.Q(null,2,5,$CLJS.R,[$CLJS.W,W6],null)],null)],null));